API-14243: Only allow requests to developer-portal-backend from developer-portal frontend
department-of-veterans-affairs/developer-portal pull request #1011
Opened 2022-03-23 21:54 UTC by SlakrHakr

### Description

Adding forgery protection to form submissions submitting to new Lighthouse Consumer Management Service in the future.

2022-03-23 22:03 UTC, SlakrHakr commented on package.json
> +  "proxy": "https://blue.prod.lighthouse.va.gov/",
ok, it looks like this configuration only works in development
hoping there is a way in aws to proxy routes over to LCMS?

2022-04-11 14:32 UTC, gileswells requested changes

2022-04-12 14:33 UTC, SlakrHakr commented on src/containers/consumerOnboarding/ProductionAccess.tsx
> +                                          .substring(2);
The protection comes from both the frontend and backend having access to the same session (being on the same domain).

1. Frontend adds a random string to it's session
2. Frontend passes same random string to the backend in the header of the request
3. Backend validates passed in header against the string in session (that the frontend put there)

2022-04-12 14:35 UTC, SlakrHakr commented on src/containers/consumerOnboarding/ProductionAccess.tsx
> +                                          .substring(2);
I used rails' implementation of CSRF protection as inspiration for this:
https://medium.com/rubyinside/a-deep-dive-into-csrf-protection-in-rails-19fa0a42c0ef

2022-04-13 14:49 UTC, gileswells commented on src/containers/consumerOnboarding/ProductionAccess.tsx
> +                                          .substring(2);
I derped on this. 👍

2022-04-13 15:00 UTC, merged