API-17064: Update existing version and API select dropdown to match new design from UX
department-of-veterans-affairs/developer-portal pull request #1089
Opened 2022-07-05 21:48 UTC by SlakrHakr

### Description

Updates "Update page" functionality on both OAuth pages (Selecting the API) and API documentation pages (selecting the API version).

![image](https://user-images.githubusercontent.com/31224301/177422312-15297b4e-446e-4f17-86cf-bd6bb85d1ca4.png)
![image](https://user-images.githubusercontent.com/31224301/177422357-0307178f-738e-408c-b516-bbb63d7ca938.png)

Updates the text on the button to make it clear the entire page is being updated by this action.

Moves the button below the dropdown selector on smaller resolutions.

Button is now disabled initially and enabled when a selection next to it is made.

Tooltip was added when button is pressed on the OAuth pages. This tooltip was not added on the API documentation pages as it seems like swagger-ui is re-rendering the entire page at that point? Hoping that is ok as the entire page shows a loading indicator but wanted to mention it here.

2022-07-06 19:23 UTC, gileswells requested changes
There are some user flow things that feel off to me.

2022-07-06 19:23 UTC, gileswells commented on src/components/apiSelector/APISelector.tsx
> +              disabled={apiSelectionButtonDisabled}
This should start as disabled so that there isn't a flash of color when initially loading the page.

2022-07-06 19:23 UTC, gileswells commented on src/components/apiSelector/APISelector.tsx
> +              data-delay-hide="5000"
The tooltip doesn't go away on it's own, you have to scroll away. Additionally, even if there is no scroll or the timer hasn't expired, the tooltip should definitely self close if the user opens the dropdown again to start selecting a new option regardless of how long it's been visible.

Currently, if I never scroll the ACG page I can continue to keep changing APIs and it will leave the "Page updated" tooltip visible the entire time.

2022-07-07 14:46 UTC, SlakrHakr commented on src/components/apiSelector/APISelector.tsx
> +              data-delay-hide="5000"
I went this route because I couldnt figure out a way to make the tooltip only appear on click of the button but disappear on click of anything else. I might have to sync up with you on how youd suggest doing something like this.

2022-07-07 14:48 UTC, SlakrHakr commented on src/components/apiSelector/APISelector.tsx
> +              disabled={apiSelectionButtonDisabled}
ok, i thought `React.useEffect(() => {` would do it immediately on load, without a flash of anything.
i'll look into this one.

2022-07-07 18:27 UTC, SlakrHakr commented on src/components/apiSelector/APISelector.tsx
> +              disabled={apiSelectionButtonDisabled}
ok, this should be fixed now:
https://github.com/department-of-veterans-affairs/developer-portal/pull/1089/commits/d122a4008e62ad6f0945b2615b0c605dc1eda16a

2022-07-12 17:46 UTC, SlakrHakr commented on src/components/apiSelector/APISelector.tsx
> +              data-delay-hide="5000"
ok, i think everything here should be addressed now.

> the tooltip should definitely self close if the user opens the dropdown again to start selecting a new option regardless of how long it's been visible

it doesn't quite do exactly this, but the tooltip hides when a new selection has been made in this scenario. The tooltip should hide on any click within the window after it has been shown.

2022-07-12 18:16 UTC, SlakrHakr commented
Looking into why the unit tests are failing...

> SyntaxError: Cannot use import statement outside a module

i also get the error if i switch back to master and run unit tests locally interestingly

2022-07-19 17:18 UTC, gileswells approved these changes
LGTM

2022-07-19 17:34 UTC, merged