August 11 _lastUpdated Update
department-of-veterans-affairs/developer-portal pull request #1107
Opened 2022-08-08 14:39 UTC by kbratti-va

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2022-08-08 14:50 UTC, SlakrHakr approved these changes
LGTM once UX approves

2022-08-08 15:02 UTC, joeabraun requested changes
Besides adding the extra paragraph, it looks good!

2022-08-08 15:02 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +
I would also just include this paragraph that we had in the previous two release notes, for consistency.
```suggestion
The _lastUpdated sort parameter lets you specify the arrangement of responses in ascending or descending order based on the last time they were changed. This parameter can be used alone or in conjunction with other sort parameters listed in the [Patient Health API (FHIR) OpenAPI specification](https://api.va.gov/internal/docs/fhir-r4/v0/openapi.json) to customize the order of responses to best meet your use case.
```

2022-08-08 19:12 UTC, joeabraun approved these changes
UX approved!

2022-08-09 13:37 UTC, SlakrHakr approved these changes
LGTM

2022-08-09 17:00 UTC, merged