Api 17066/add copy to clipboard button
department-of-veterans-affairs/developer-portal pull request #1152
Opened 2022-12-13 15:42 UTC by imcgonigle

### Description
[API-17066 Add "copy to clipboard" functionality within code blocks on the authentication documentation pages](https://vajira.max.gov/browse/API-17066)

This PR adds a "Copy code to clipboard" button to the code blocks on the authentication documentation pages.

NOTE: I had a different PR open for this ticket, but I wasn't update the visual regression tests in that branch. I've revised the code on this branch to reduce the scope of the changes which, I'm hoping, will make it easier to get the build to pass.

2023-01-05 16:49 UTC, gileswells requested changes
Smaller semantic changes but nothing structural to fix. Small fixes and likely a re-run of the visual regressions.

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/PKCEAuthContent.tsx
> +    "scope": ${scopes},
Missing quotes around these scopes. Properly included further up the page.
```suggestion
    "scope": "${scopes}",
```

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +      />
Something in here is causing an extra line break at the top of the code sample.

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/ccg/GeneratingJWTContent.tsx
> +  "jti": "23f8f614-72c3-4267-b0da-b8b067662c74"
Other instances of just a JSON objects within the auth docs have 4 spaces rather than 2. Either way works for me but we should stick to one or the other. Without putting much thought into it I kinda want to lean toward 2 spaces as that would match our indentation spec for our own files.

Edit: with more thought I think that 2 spaces is the way to go. I'll add comments to other spots we have 4 spaces to potentially address but it looks like we've mostly standardized on 2 spaces in most places.

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +    "scope": "${scopes}",
This JSON should have 2 spaces of indent to match the others on CCG auth page (and our coding style)

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +        code={`\
JSON should have 2 space indent

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +        code={`\
JSON should have 2 space indent

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/PKCEAuthContent.tsx
> +    "scope": ${scopes},
Also this JSON should have 2 space indent

2023-01-05 16:49 UTC, gileswells commented on src/components/oauthDocs/acg/PKCEAuthContent.tsx
> +        code={`\
JSON should have 2 space indent

2023-01-05 17:57 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +      />
was trailing space on 244

2023-01-06 19:34 UTC, gileswells approved these changes
LGTM

2023-01-26 22:25 UTC, gileswells reviewed
LGTM

2023-01-26 22:25 UTC, gileswells approved these changes
LGTM

2023-02-08 01:05 UTC, imcgonigle commented on src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
> +            )}
I think I picked this up while resolving merge conflicts. I'm going to remove it from this PR

2023-03-16 15:11 UTC, jw81 approved these changes
You probably should also get approval from an experienced React dev, but this looks really good to me!  😄   I pulled it down locally and tried it out and I think it's great! 👍

2023-03-16 22:32 UTC, merged