[API-24014] explore row layout
department-of-veterans-affairs/developer-portal pull request #1245
Opened 2023-06-16 16:22 UTC by Cgfor3

### Description

- Add logic to iterate through each category and pass categoryName to each API within the category
- Add faLock to appropriate tags
- Add restricted access to a static list of APIs

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2023-06-16 18:58 UTC, gileswells requested changes
Some thoughts on how to handle the loop and where to do category tag logic.

2023-06-16 18:58 UTC, gileswells commented on src/containers/documentation/ExploreRoot.tsx
> +];
I'm not a huge fan of this BUT provided that we create a ticket to account for removing this by adding support to LPB on a per API basis after IA launch I'm ok with it.

2023-06-16 18:58 UTC, gileswells commented on src/containers/documentation/ExploreRoot.tsx
> +      const categoryName = apiDefs[apiCategory].urlSlug;
I feel like the logic for getting the category name, because it's specifically needed for the ExploreApiCard component, should be handled within the component. Passing in just the api variable through a single parameter (with a second parameter being the key) should be more than enough. Basically let the component handle its own logic rather than depend on an external process.

If this component ever needed to get added elsewhere then we'd have to duplicate this logic to that location as well.

2023-06-16 18:58 UTC, gileswells commented on src/containers/documentation/ExploreRoot.tsx
> +          {getApiList()}
I get wanting to bundle up all the logic in a method but if the suggestion to move the category logic into the ExploreApiCard component is adopted then I would rather the loop just be here rather than as a method being called as it is here.

2023-06-16 19:47 UTC, Cgfor3 commented on src/containers/documentation/ExploreRoot.tsx
> +];
Agreed - LPB currently exposes "restrictedAccessDetails" (string) and "restrictedAccessToggle" (boolean) with each API, so could we leverage that? AFAIK these are all set to false for the moment. If that attribute is intended for something else, then we can create another attribute

2023-06-16 19:52 UTC, Cgfor3 commented on src/containers/documentation/ExploreRoot.tsx
> +          {getApiList()}
On it

2023-06-16 21:35 UTC, Cgfor3 commented on src/components/exploreApiCard/ExploreApiCard.tsx
> +
@gileswells let me know if this is more inline with what you were thinking

2023-06-20 15:58 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiCard.tsx
> +
Are there instances where we won't have access to api.categoryUrlFragment? If we have that then you could utilize lookupApiCategory(api.categoryUrlFragment) as a much simpler option, right?

2023-06-20 15:59 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiCard.tsx
> +
Yes moving the logic into the component is the goal so it's self contained but overall I think we already have this logic within the query.ts file so we should leverage it.

2023-06-21 15:15 UTC, Cgfor3 commented on src/components/exploreApiCard/ExploreApiCard.tsx
> +
The mapping does not seem to work for every API on my end. I'm using `lookupApiCategoryBySlug` since I'm not seeing `categoryUrlFragment` passed from LPB and I'm still only seeing a select few of the categories returned 
<img width="787" alt="Screen Shot 2023-06-21 at 11 14 30 AM" src="https://github.com/department-of-veterans-affairs/developer-portal/assets/81174472/667b242e-690f-4895-8920-a9d0efe746ea">

2023-06-21 20:14 UTC, gileswells requested changes
Minor things but no big functional changes from here.

2023-06-21 20:14 UTC, gileswells commented on src/actions/index.ts
> +  console.log(apis);
Remove

```suggestion
```

2023-06-21 20:14 UTC, gileswells commented on src/apiDefs/query.ts
>    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
This line can likely be removed since there's no more `?? null` conditional.

2023-06-21 20:14 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiCard.tsx
> +export const ExploreApiCard = ({ api }: { api: APIDescription }): JSX.Element => (
Absolutely love how much simpler this component is now. 🥰

2023-06-21 20:14 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiTags.tsx
> +export const ExploreApiTags = ({ api }: { api: APIDescription }): JSX.Element => {
I am slightly conflicted here. Because we only use this under the `/explore` top level folder the name of `ExploreApiTags` makes sense but the naming of this as just `ApiTags` seems like another viable option because we will have these utilized on an API's detail page that isn't directly part of the "Explore" page.

This is just a thought and I'm ok with it either way. Change if you think this rationale makes sense enough to rename it.

2023-06-21 20:14 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiCard.scss
>    }
It might be best to move these CSS rules out to their own file / not have then within the `.explore-api-card-container` so that they can be dropped into the [API Overview page](https://www.figma.com/file/ufpSfFIB56bvfwAHjrkM8H/Portal-ReVAMP?type=design&node-id=1452-47183&mode=design&t=UWLX5WbTolcZjbBL-0) without issue.

2023-06-21 20:24 UTC, Cgfor3 commented on src/components/exploreApiCard/ExploreApiTags.tsx
> +export const ExploreApiTags = ({ api }: { api: APIDescription }): JSX.Element => {
My only concern is that ApiTags already exists and I'm not sure what the differences are or where the existing component is used

2023-06-21 20:29 UTC, Cgfor3 commented on src/components/exploreApiCard/ExploreApiTags.tsx
> +export const ExploreApiTags = ({ api }: { api: APIDescription }): JSX.Element => {
IF this work has already been done two years ago I'm gonna be real sad

2023-06-21 20:36 UTC, gileswells commented on src/components/exploreApiCard/ExploreApiTags.tsx
> +export const ExploreApiTags = ({ api }: { api: APIDescription }): JSX.Element => {
I knew the name sounded familiar. It was kinda done previously but not with this styling and definitely not with this granularity. https://developer.va.gov/onboarding/production-access-application This is the last place that I can see it exists. Likely a future consideration to revise how we do the visible tags on the prod access form.

2023-06-22 16:43 UTC, gileswells approved these changes
Just fixed the unit test since last approval of Calvin's code.

2023-06-22 16:43 UTC, merged