Update API overview page to use updated content
department-of-veterans-affairs/developer-portal pull request #1257
Opened 2023-06-28 19:38 UTC by imcgonigle

### Description
[Jira Ticket (API-23999)](https://jira.devops.va.gov/browse/API-23999?filter=-1)

This PR updates the API Overview page to display the overview page content that was added to LPB in this PR [LPB PR](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/pull/286#:~:text=Jira%20Ticket%20(API%2D23999))

2023-06-28 20:14 UTC, gileswells requested changes
Has there also been testing / styling implemented on these pages that includes other markup like lists, tables, links, paragraphs, and different heading levels besides the "Default overview page content" you have for all of them?

2023-06-28 20:14 UTC, gileswells commented on src/__mocks__/fakeCategories.tsx
> +        overviewPageContent: '## Default overview pag content',
Small annoyance but typo repeated down all the `overviewPageContent` blocks.

2023-06-28 20:14 UTC, gileswells commented on src/apiDefs/query.ts
> +
This can be removed. We have enforced the inclusion of the `categoryUrlFragment` and `categoryUrlSlug` into the `APIDescription` definition. With that you can just use `lookupApiCategory(api.categoryUrlFragment)` to get the same result.

2023-06-28 20:14 UTC, gileswells commented on src/containers/documentation/ApiOverviewPage.tsx
> +import { lookupCategoryByApi } from '../../apiDefs/query';
Replace `lookupCategoryByApi` with `lookupApiCategory`.
```suggestion
import { lookupApiCategory } from '../../apiDefs/query';
```

2023-06-28 20:14 UTC, gileswells commented on src/containers/documentation/ApiOverviewPage.tsx
> +  const apiCategory = lookupCategoryByApi(api);
Replace `lookupCategoryByApi` with `lookupApiCategory`.
```suggestion
  const apiCategory = lookupApiCategory(api.categoryUrlFragment);
```

2023-06-28 20:14 UTC, gileswells commented on src/containers/documentation/ApiOverviewPage.tsx
> +const APITags = ({ api }: { api: APIDescription }): JSX.Element => {
Spotted the `lookupCategoryByApi` before this but this feels like doing the same thing as `<ExploreApiTags api={api} />` but is missing the lock icons on the names as needed. Try swapping to using this existing (but still new) component.

2023-06-28 20:17 UTC, imcgonigle commented on src/containers/documentation/ApiOverviewPage.tsx
> +const APITags = ({ api }: { api: APIDescription }): JSX.Element => {
Oh awesome I didn't realize that was a thing. I'll switch it right now

2023-06-28 20:19 UTC, imcgonigle commented
I'm finishing up tests right now. I didn't think to add styles for elements that weren't in the API overview document. I'll add those too

2023-06-29 18:47 UTC, gileswells approved these changes
Looks good

2023-07-03 14:19 UTC, gileswells approved these changes

2023-07-05 19:12 UTC, gileswells approved these changes
Looks good overall

2023-07-05 19:28 UTC, merged