Only display active APIs on explore page
department-of-veterans-affairs/developer-portal pull request #1268
Opened 2023-07-03 18:31 UTC by imcgonigle

### Description
This PR removes deprecated APIs from explore page

2023-07-03 18:33 UTC, gileswells submitted a review, later dismissed
I don't think you _needed_ to update the variable name but looks good nonetheless.

2023-07-03 19:34 UTC, gileswells requested changes
Should be the last change

2023-07-03 19:34 UTC, gileswells commented on src/containers/documentation/ExploreRoot.test.tsx
> +    expect(apiCount).toBe(7);
String formatting
```suggestion
    expect(apiCount).toBe('7');
```

2023-07-03 19:36 UTC, gileswells submitted a review, later dismissed
LGTM

2023-07-05 02:46 UTC, andresriveratoro approved these changes

2023-07-05 15:06 UTC, andresriveratoro approved these changes
LGTM

2023-07-05 15:33 UTC, merged