Replace production access form API labels
department-of-veterans-affairs/developer-portal pull request #1316
Opened 2023-08-02 22:07 UTC by andresriveratoro

### Description
[API-28416](https://jira.devops.va.gov/browse/API-28416)

This PR replaces the API labels on the production access form with the same labels used for the Explore API page

### Requested feedback

2023-08-03 19:59 UTC, gileswells requested changes
Curious about the `<ApiTags />` component remaining vs expanding the scope of `<ExploreApiTags />` as an alternative option.

2023-08-03 19:59 UTC, gileswells commented on src/components/apiTags/ApiTags.test.tsx
> +    screen.debug();
Should this be removed?

2023-08-03 19:59 UTC, gileswells commented on src/components/apiTags/ApiTags.tsx
> +    {props.openData && <ExploreApiTag tagName="Open Data" />}
Does it make more sense to include a full component (`ApiTags` in this case) or would it make more sense to allow for `<ExploreApiTags />` to allow for a property where someone can block certain tag types from being shown. For instance, what if `ApiTags` was removed entirely and we just had `<ExploreApiTags api={api} skip={['topic']} />` where this would allow for all the same tags and layout to be used but would skip the topic tag from rendering? I put this as an array as we could potentially want to have skips setup for all of the types (`'auth'|'lock'|'restricted'|'topic'`) and potentially multiple at once.

Not convinced either way but curious for your thoughts.

2023-08-04 16:08 UTC, andresriveratoro commented on src/components/apiTags/ApiTags.tsx
> +    {props.openData && <ExploreApiTag tagName="Open Data" />}
I ended up removing the old ApiTags component. I don't think we need an ApiTags component or to expand the ExploreApiTags component for a component this simple. I extracted the ExploreApiTag component out of ExploreApiTags to further signal that ApiTag is a generic component that can be used elsewhere.

2023-08-04 17:14 UTC, gileswells commented on src/components/apiTags/ApiTags.tsx
> +    {props.openData && <ExploreApiTag tagName="Open Data" />}
I like it. Solve the CI tests and I'll re-review the PR.

2023-08-07 15:34 UTC, gileswells submitted a review, later dismissed
LGTM

2023-08-08 15:04 UTC, gileswells submitted a review, later dismissed
LGTM

2023-08-11 21:26 UTC, Cgfor3 approved these changes
:shipit:

2023-08-14 14:35 UTC, merged