React router 6 upgrade
department-of-veterans-affairs/developer-portal pull request #1339
Opened 2023-08-18 21:48 UTC by Cgfor3

### Description

- Migrate from RR 5.1+ -> RR6
- Implement ScrollRestoration to manage scroll preservation
- Update SandboxAccessForm package to resolve nested router errors
- Fix unit and cypress tests
-  
### Requested feedback

2023-08-24 15:02 UTC, gileswells reviewed
Overall looks very good. Just a question around the APIs that would have conditionally disabled pages and how we're supporting those.

2023-08-25 20:11 UTC, Cgfor3 commented on src/Routes.tsx
> +      <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />
Yes! We can leverage the params in the Route loader definition and perform the necessary checks using the return value. My next change will include this

https://reactrouter.com/en/main/route/loader

https://reactrouter.com/en/main/hooks/use-loader-data#useloaderdata

2023-08-25 20:47 UTC, Cgfor3 commented on src/Routes.tsx
> +      <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />
On second thought, there is a better alternative that would navigate to the 404 immediately rather than render the component, do more logic, and then navigate away.

2023-08-25 21:17 UTC, Cgfor3 commented on src/Routes.tsx
> +      <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />
I assume moving this logic out of DocumentationRoot is preferable as well so it's not duplicating effort.

https://github.com/department-of-veterans-affairs/developer-portal/pull/1339/files/b652335667330ce97e07c0e86b4094411f33d904#diff-dd0e239cae3d3167df537028b596a3c127980625c59a6035035f13902d6783e7L89-L103

2023-08-28 14:33 UTC, gileswells commented on src/Routes.tsx
> +      <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />
> On second thought, there is a better alternative that would navigate to the 404 immediately rather than render the component, do more logic, and then navigate away.

So the preferred method of showing a 404 is for it to happen on the url that the user intended to visit. This means that navigating to `/404` for example is considered a bad practice. From what I am seeing the redirect method is what most people are using to break out from the nested routes and allow a 404 page to be loaded. 🤔 I'm going to do a little digging to see if there's a better solution that fits more in line with what the expected behavior for a 404 page where it gives the response from the url that the user visited.

2023-08-28 14:50 UTC, gileswells requested changes

2023-08-28 14:50 UTC, gileswells commented on src/Routes.tsx
> +        {hasCCG && <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />}
Unfortunately this isn't working. I'm getting 404 pages 100% of the time when loading APIs that should have a page here. My guess is these routes are already created before the APIs load in from LPB and they'll always have a false value. I think that we'll need to handle the 404 logic, at least the triggering of loading a 404, within each child routes' component.

2023-08-28 16:47 UTC, Cgfor3 commented on src/Routes.tsx
> +        {hasCCG && <Route path="client-credentials" element={<ClientCredentialsGrantDocs />} />}
Yeah, resorting to the ErrorBoundary works well for this so we're still avoiding any potential flickering by handling it inside the DocumentationRoot component

2023-09-14 18:16 UTC, gileswells approved these changes
LGTM. Great work on this.

2023-09-14 18:21 UTC, merged