[API-29795] - Focus errored field on submit
department-of-veterans-affairs/developer-portal pull request #1364
Opened 2023-09-26 14:33 UTC by andresriveratoro

### Description
https://jira.devops.va.gov/browse/API-29795

### Requested feedback

2023-09-26 15:26 UTC, gileswells requested changes

2023-09-26 15:27 UTC, gileswells commented on src/containers/support/ContactUsForm/ContactUsForm.tsx
> +          <button type="submit" className="vads-u-width--auto" onClick={handleSubmit}>
Also would be good to add a test that ensures that we are focusing on the right element after an errored submission.

2023-09-27 15:04 UTC, andresriveratoro commented on src/containers/support/ContactUsForm/ContactUsForm.tsx
> +          <button type="submit" className="vads-u-width--auto" onClick={handleSubmit}>
I moved the focusing to the hook we were already using because Formik's onSubmit doesn't fire if there are any validation errors.

2023-10-18 17:09 UTC, gileswells approved these changes

2023-10-19 00:35 UTC, merged