[API-31131] Update CCG Launch Description
department-of-veterans-affairs/developer-portal pull request #1393
Opened 2023-10-23 17:23 UTC by Cgfor3

### Description

- Update description for Guaranty Remittance and Loan Review APIs

### Requested feedback

2023-10-23 17:59 UTC, gileswells requested changes
Some changes. I wouldn't be opposed to setting the JSON object earlier in the switch statement and then using `JSON.stringify(object)` and `btoa(JSON.stringify(object))`. This would be a good first step toward the likely inevitable switch to this object coming down from LPB's `oauth_info` field.

2023-10-23 17:59 UTC, gileswells commented on src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
> +            <code>LWIgeyJwYXRpZW50IjoiMTAwMDcyMDEwMFYyNzEzODcifQo==</code>
This is not the base64 encoded string of `{ "portal_id": "TEST1234567890SERVICE"}`.

2023-10-23 17:59 UTC, gileswells commented on src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
> +            The format of the object will be: <code>{'{ "patient": "1000720100V271387"}'}</code>
Same thing here with the space before the "patient" property. Would also likely need to update the base64 string below to match.

2023-10-23 17:59 UTC, gileswells commented on src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
> +            <code>{'{ "portal_id": "TEST1234567890SERVICE"}'}</code>
I'd ideally like to see us format this JSON a little better. Specifically looking at that arbitrary space before the "portal_id" property name.

2023-10-23 18:08 UTC, Cgfor3 commented on src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
> +            <code>LWIgeyJwYXRpZW50IjoiMTAwMDcyMDEwMFYyNzEzODcifQo==</code>
Good catch they didn't provide the encoded string, and I didn't think to generate it. 

Is there a preferred method of getting this? Or is using any online base64 encoder fine? I got `eyAicG9ydGFsX2lkIjogIlRFU1QxMjM0NTY3ODkwU0VSVklDRSJ9` as the encoded string

2023-10-23 19:25 UTC, Cgfor3 commented on src/utils/ccgLaunchContextHelper.tsx
> +      const [portalStringData, portalEncodedData] = createContextData(portalData);
@gileswells is this closer to what you had in mind? It's using the stringify method you described and starting with the object outside the template string resolves the issue of having extra random spaces

2023-10-23 20:09 UTC, gileswells approved these changes
I like the idea of making this content more variable driven but might not be overly possible.

2023-10-23 20:09 UTC, gileswells commented on src/utils/ccgLaunchContextHelper.tsx
> +      const [portalStringData, portalEncodedData] = createContextData(portalData);
Yes. The similarities of the blocks of text give me a desire to add more things as variables vs large blocks of html code so that we can keep the content uniform with just swapping in like `patient's ICN` or `lender ID`. The pure simplicity of just swapping out a name / field here and there does kinda run afoul with the middle paragraph so maybe not so much a possibility as my desires might have.

2023-10-24 20:13 UTC, jw81 approved these changes
LGTM 👍 
The code makes sense to me and when I look at Guaranty Remittance and Loan Guaranty CCG docs in the review instance, they look like they should.  
Also looked at the Patient Health CCG docs in the review instance and they too looked as they should.

2023-10-26 00:44 UTC, merged