[API-31520] - Implement Touchpoint Survey (revisited)
department-of-veterans-affairs/developer-portal pull request #1425
Opened 2023-12-13 18:57 UTC by jw81

### Description

Original Issue :: [API-31520](https://jira.devops.va.gov/browse/API-31520)
- Adds the UX-designed Touchpoint survey to the DevPortal.

2023-12-14 15:37 UTC, gileswells requested changes

2023-12-14 15:37 UTC, gileswells commented on cypress/e2e/containers/documentation/DocumentationRoot.cy.js
> +    cy.get('[href="/explore/api/appeals/sandbox-access').should('not.exist');
I think I would rather see this left as `appeals-status` and then we update the legacy.json file to use the url that matches what's in production. Overall it's not necessary but if we're making a change, I'd rather we make it to be in line with what we have on prod.

2023-12-14 15:37 UTC, gileswells commented on src/components/pageContent/PageContent.tsx
> +    };
So this debounce is waiting 100ms after the event finishes to run just one time. I feel like the experience shown to the user would be better if it was setup to run at most every 100ms instead of wait at least 100ms after the scrolling event stops firing.

2023-12-14 15:59 UTC, jw81 commented on cypress/e2e/containers/documentation/DocumentationRoot.cy.js
> +    cy.get('[href="/explore/api/appeals/sandbox-access').should('not.exist');
Updated [here](https://github.com/department-of-veterans-affairs/developer-portal/pull/1425/commits/47b88160ff642285e6184c380efce1a9c231f4a3).

2023-12-14 16:59 UTC, jw81 commented on src/components/pageContent/PageContent.tsx
> +    };
Switched over to a "throttle" approach [here](https://github.com/department-of-veterans-affairs/developer-portal/pull/1425/commits/3f3107c9c37b6ab968881d0d570cb0cd6f29d5b8).  LMK if it's not quite what you were thinking.

2023-12-14 18:40 UTC, gileswells requested changes
I like the change to throttle(), just concerned about best practice on the dom queries.

2023-12-14 18:40 UTC, gileswells commented on src/components/pageContent/PageContent.tsx
> +      const footer = document.querySelector('footer');
I think that these can be moved outside of this function. In general, dom queries are more expensive in terms of performance and since these elements don't actually change we shouldn't need to query to find them again each time we adjust the button position.

2023-12-14 18:51 UTC, jw81 commented on src/components/pageContent/PageContent.tsx
> +      const footer = document.querySelector('footer');
Ah, that's a really good point!  Only need to find them once.
I'll update this.

2023-12-14 19:43 UTC, jw81 commented on src/components/pageContent/PageContent.tsx
> +      const footer = document.querySelector('footer');
Updated that code [here](https://github.com/department-of-veterans-affairs/developer-portal/pull/1425/commits/0a92c683e4b432ed25452bd7cc2024ce704ff09c).

2023-12-29 22:02 UTC, jw81 reviewed
Added a quick note about just removing the logo from Touchpoints vs adding CSS to programmatically hide the logo.

2024-01-09 18:33 UTC, jw81 commented on src/components/pageContent/PageContent.tsx
> +      const footer = document.querySelector('footer');
All that custom Javascript has been removed since UX has decided to go with a sticky experience for the button.

2024-01-09 21:04 UTC, jw81 commented on cypress/e2e/containers/documentation/DocumentationRoot.cy.js
> +    cy.get('[href="/explore/api/appeals/sandbox-access').should('not.exist');
The custom JS was removed since UX decided to go with a more "static" experience.

2024-01-09 21:04 UTC, jw81 commented on src/components/pageContent/PageContent.tsx
> +    };
The custom JS was removed since UX decided to go with a more "static" experience.

2024-01-09 22:07 UTC, andresriveratoro approved these changes
LGTM

2024-01-10 19:46 UTC, gileswells approved these changes

2024-01-10 19:47 UTC, merged