Add attestation to production access and sandbox access form
department-of-veterans-affairs/developer-portal pull request #1466
Opened 2024-03-16 13:58 UTC by andresriveratoro

### Description

### Requested feedback

2024-03-18 15:29 UTC, gileswells commented on src/containers/consumerOnboarding/validationSchema.ts
> +export const productionAttestationApis = ['apikey/benefits'];
Are we expecting to have a different list between production and sandbox attestation requirements?

2024-03-18 15:45 UTC, andresriveratoro commented on src/containers/documentation/components/sandbox/validateForm.ts
> +  }
Thanks for catching this!

2024-03-18 22:16 UTC, andresriveratoro commented on src/containers/consumerOnboarding/Attestation.tsx
> +  api: string;
I moved the logic to find the API details outside of the attestation modal and instead pass in the API object.

2024-03-19 15:31 UTC, gileswells requested changes

2024-03-19 15:31 UTC, gileswells commented on src/containers/documentation/components/sandbox/SandboxAccessForm.tsx
> +  );
I'd prefer, especially because it is recreated identically in another file, to see this moved to the query.ts file. I believe that we used to have a `lookupApiByAltId` method in that file as well or it might have just been the `lookupApiByFragment` that still exists but I would like rather see this search moved into the query.ts file as well for potential reuse.

2024-03-21 04:01 UTC, gileswells reviewed
LGTM

2024-03-21 04:01 UTC, gileswells approved these changes

2024-03-21 15:35 UTC, merged