Replace jest-fetch-mock with Mock Service Worker's Node implementation
department-of-veterans-affairs/developer-portal pull request #414
Opened 2020-08-31 15:33 UTC by mjlumetta

### Description

in support of [API-1317](https://vajira.max.gov/browse/API-1317).

this test changes the HTTP request mocking for Apply and Contact Us tests to use [Mock Service Worker's](https://mswjs.io/docs/) `setupServer` rather than using `jest-fetch-mock`. the motivation for this change is to mock requests in a way that is agnostic to the specific mechanism for making the HTTP request, as well as being a bit more expressive in terms of what it can offer (mocking multiple endpoints/resources in a more natural way).

### Process

- [X] Tests added or updated for change
  * the whole ticket is updating tests
- [ ] Docs updated
  * going to do a wrap-up docs PR for API-1317
- [ ] Accessibility concerns have been considered and addressed
  * n/a, no UI changes

### Requested feedback

2020-08-31 15:35 UTC, mjlumetta commented on src/actions/apply.spec.ts
> +          return res(context.status(500, 'KABOOM'));
the docs say you should be able to omit the status text, but i couldn't get it to work after semi-extensive debugging. extremely annoying but fine for tests.

2020-08-31 15:36 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.test.tsx
> -    process.nextTick(() => {
this broke once i switched things over to the non-mocked version. unsure why, think it has to do with the Node loop, gonna try to figure it out.

2020-09-15 15:51 UTC, anthony-kopczyk commented on src/actions/apply.spec.ts
> +          return res(context.status(500, 'KABOOM'));
Sounds good, but curious - Is this a typescript typing issue where it doesn't have that parameter as optional or does it fail during runtime?

2020-09-15 15:54 UTC, anthony-kopczyk commented on src/actions/apply.ts
> +        'content-type': 'application/json',
Does this need to be capitalized like in a sent HTTP request - 'Content-Type'?

2020-09-15 16:15 UTC, anthony-kopczyk commented on src/types/constants/index.ts
> +}/internal/developer-portal-backend/developer_application`;
This looks the same as the apply url. Should it be /apply or something similar?

2020-09-15 17:29 UTC, nathanbwright commented on src/containers/support/SupportContactUsForm.tsx
> +    );
Can this conditional be simplified?

2020-09-15 19:12 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    );
I'm not thinking of anything for making the content of the method simpler, but maybe rename the method as isFormValid or something to reflect the check itself would help with readability and add enough context to make the content easier to understand?

2020-09-15 20:51 UTC, mjlumetta commented on src/actions/apply.spec.ts
> +          return res(context.status(500, 'KABOOM'));
it fails during runtime. it also uses the default `'OK'` instead of `'Internal Server Error'` or what have you.  i could not figure out why, which is annoying, but i was planning to let this one slide.

2020-09-15 20:51 UTC, mjlumetta commented on src/types/constants/index.ts
> +}/internal/developer-portal-backend/developer_application`;
oh shoot good catch, thank you, i should have tested this

2020-09-15 21:21 UTC, mjlumetta commented on src/actions/apply.ts
> +        'content-type': 'application/json',
so, HTTP headers are [case insensitive](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive) - which, like, had to look that up because i didn't remember. i'm okay with either as long as they're consistent in this object, but i would default to not changing anything where the changes were all from Prettier.

2020-09-15 21:33 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.tsx
> +    );
okay, fixed this one. used Anthony's suggestion about `isFormValid`, and also wrote a tiny helper for each field.

for the `validation` property, it's a string with an error message. check out `src/utils/validators.ts` and the `validatePresence` and `validateEmail` functions. you can see those used in the `onChange` handlers.

2020-09-16 12:16 UTC, anthony-kopczyk commented on src/actions/apply.ts
> +        'content-type': 'application/json',
What?! That's insane! I had no idea. haha. Yeah. We can leave as is, especially if the changes came from Prettier.

2020-09-16 12:20 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    );
The helper really cleans it up as well.

2020-09-16 12:23 UTC, anthony-kopczyk requested changes
It all looks good to me except the sections where there is '!!'.

2020-09-16 12:23 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
Is the !! on purpose? Or maybe remnants of a previous version of the code?

2020-09-16 12:24 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
```suggestion
    const validateField = (field: IErrorableInput): boolean => field.value && !field.validation;
```

2020-09-16 13:58 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
it changes the type signature of the function from `(field: IErrorableInput) => boolean` to `(field: IErrorableInput) => boolean | string`, so it's a no-go on that. tried that first

2020-09-16 14:13 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
Didn't even think about return type. Pulled it down a fiddled with it. There might be a more verbose way to make it so we don't need  `!!` but it's immediately obvious that the typing isn't going to place. This is good. No changes needed.

2020-09-16 14:13 UTC, anthony-kopczyk submitted a review, later dismissed

2020-09-17 20:54 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
circling back to this: would you prefer if it were `!!(field.value && !field.validation)`? might be equally confusing, but then you can kinda see that's it's forcing the whole result to a boolean. can push that if there are more changes based on other feedback.

2020-09-17 21:22 UTC, anthony-kopczyk commented on src/containers/support/SupportContactUsForm.tsx
> +    const validateField = (field: IErrorableInput): boolean => !!field.value && !field.validation;
I think that way might actually be more confusing for me. haha. Because then I'd be looking at the entire output rather than the `field.value` piece.

I did some googling on this, and it seems like the `!!field` approach is pretty standard. I just haven't seen it or forgot I've seen it. I think we can leave it as is and if it comes up again in the future while someone is coding we can revisit the it.

2020-09-18 16:32 UTC, nathanbwright commented on src/containers/support/SupportContactUsForm.tsx
> +    // );
I'm assuming this is just a left over from a previous iteration, right?

2020-09-18 17:02 UTC, nathanbwright approved these changes
Don't have a ton of experience with react but it looks good to me.

2020-09-18 17:14 UTC, merged