Api 1978 address validation faq
department-of-veterans-affairs/developer-portal pull request #422
Opened 2020-09-11 13:42 UTC by charleystran

### Description
This PR adds a Question/Answer for how to gain address to the address validation sandbox API.  Text has been approved in this ticket https://vajira.max.gov/browse/API-225 and the corresponding https://vajira.max.gov/browse/API-1978.

2020-09-11 16:07 UTC, rtravitz commented
Showing zero files changed on this one. What am I missing?

2020-09-11 19:23 UTC, Eallan919 commented
same...I don't see an update with the new copy

2020-09-11 19:37 UTC, anthony-kopczyk requested changes
Cross referenced with the main Jira ticket. Some formatting needs updated to match, or maybe the Jira ticket's description needs updated.

2020-09-11 19:37 UTC, anthony-kopczyk commented on src/containers/support/SupportFAQ.tsx
> +          <li>Any IP addresses or subnets outside the VA intranet from which you require developer access (permitted in sandbox only)</li>
The text _outside the VA internet_ is in italics on the associated Jira ticket.

I'm being a stickler because I'm new. :)

2020-09-11 19:37 UTC, anthony-kopczyk commented on src/containers/support/SupportFAQ.tsx
> +          <li>When indicating your desired production date, note that we require at least one week's notice before a demo can be scheduled, and that it may take up to a week after the demo to grant y
The Jira ticket shows this as being a separate paragraph rather than part of the bulleted list.

2020-09-11 19:41 UTC, mjlumetta requested changes
couple of copy questions, but the main thing is that it looks like you can't nest a `ul` inside a `p`, so we're probably going to have to make these elements siblings. hopefully this is a quick fix

2020-09-11 19:41 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +        <ul>
nesting this `ul` inside the `p` isn't allowed, apparently. there's a console warning from React:

```
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
```

here's [a StackOverflow post](https://stackoverflow.com/questions/7168723/unordered-list-in-a-paragraph-element) to the same effect. so seems like we'd have to go with paragraph, unordered list, paragraph within a `React.Fragment`. that sound right?

also, would you mind wrapping the text for some of the long lines? we should be able to do that because we're in JSX without breaking it. to be fair, i always forget which contacts you can't wrap in, so maybe that's not correct.

2020-09-11 19:41 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +          <li>When indicating your desired production date, note that we require at least one week's notice before a demo can be scheduled, and that it may take up to a week after the demo to grant y
should this be a list item? looks like it's formatted as a paragraph in the ticket, but maybe that's not right.

2020-09-11 19:41 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +          <li>Any IP addresses or subnets outside the VA intranet from which you require developer access (permitted in sandbox only)</li>
```suggestion
          <li>Any IP addresses or subnets <em>outside the VA intranet</em> from which you require developer access (permitted in sandbox only)</li>
```

looks like that might be italicized?

2020-09-14 16:58 UTC, charleystran commented on src/containers/support/SupportFAQ.tsx
> +          <li>When indicating your desired production date, note that we require at least one week's notice before a demo can be scheduled, and that it may take up to a week after the demo to grant y
I wouldnt take the ticket as the markup requirements as it was just written by support over engineers. I think we can get a final review once its up and make adjustments.

2020-09-15 13:23 UTC, anthony-kopczyk approved these changes

2020-09-15 13:24 UTC, anthony-kopczyk commented
I went ahead and approved my review because Mike's review covers the potential changing points in mine --- although it did now count it as an approval, which I wasn't expecting.

2020-09-15 17:33 UTC, ediiotero reviewed
Just had a question about p tags vs divs and using ul's

2020-09-15 17:33 UTC, ediiotero commented on src/containers/support/SupportFAQ.tsx
> +  },
Looks good but had a question:
I understand the p tag shouldn't have li children but is you made them div's you should be able to use an unordered list. Just curious if p tags had to be used for every answer or if there is something I'm missing as a pattern or accessibility?

2020-09-15 21:45 UTC, mjlumetta reviewed
had a suggestion about the list/paragraph issue, but the issue's fixed right now. would also want to get a review from UX/product/Ryan Link to give the final approval on the content like you'd talked about earlier.

2020-09-15 21:45 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +        <br />
i was picturing this going the other way in terms of using that list but taking it out of the paragraph and making it next to the paragraphs. so 2 paragraphs and a list nested inside some container. this is the element hierarchy i'm imagining that could fix that constraint and preserve the list:

```
<React.Fragment>
  <p />
  <ul />
  <p />
</React.Fragment>
```

2020-09-16 13:32 UTC, charleystran commented on src/containers/support/SupportFAQ.tsx
> +          <li>Any IP addresses or subnets outside the VA intranet from which you require developer access (permitted in sandbox only)</li>
this is done

2020-09-16 13:34 UTC, charleystran commented on src/containers/support/SupportFAQ.tsx
> +  },
I think there is a lot to be refactored here especially as we move to dynamic content.So I dont have a great answer, but you bring up a good point as we iterate on this.

2020-09-18 14:49 UTC, ryanlink submitted a review, later dismissed
can we somehow bullet the AV list items?  otherwise LGTM

2020-09-21 15:42 UTC, mjlumetta approved these changes
💯 🚀

2020-09-21 15:46 UTC, merged