[DRAFT] Add buildspec-release.yml for automated releases.
department-of-veterans-affairs/developer-portal pull request #433
Opened 2020-09-21 20:14 UTC by duganth-va

### Description
Adds buildspec-release.yml for automated release jobs.

### Process
- [ ] Tests added or updated for change
- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed

### Requested feedback
Developer feedback on the release process.

2020-09-30 15:50 UTC, mjlumetta reviewed
looks good so far, left a few comments. same as the CI PR, haven't done any extensive testing but will circle back to that later. also, big fan of the `gh` CLI tool 💯

2020-09-30 15:50 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +      - echo ${ci_status}
tiny detail, but would probably suggest adding a little more on the log message. like "Commit status: $(ci_status)"

2020-09-30 15:50 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +    ENVS: "dev staging production"
how does the dev/staging auto-release work in this case again? i know you've talked about this at some point, but i can't remember how it's supposed to go 😅

2020-10-01 09:42 UTC, duganth-va commented on cicd/buildspec-release.yml
> +      - echo ${ci_status}
more details the better, sounds good.

2020-10-01 09:42 UTC, duganth-va commented on cicd/buildspec-release.yml
> +      - gh config set git_protocol ssh
I like that mantra of over referencing external docs, I'll adopt. Here are the relevant links:
https://github.com/cli/cli
https://cli.github.com/manual/gh_config_set

2020-10-01 09:57 UTC, duganth-va commented on cicd/buildspec-release.yml
> +    ENVS: "dev staging production"
The ENVS variable here is just a list of the assets we will post to the release tag. These assets are pulled from the S3 archive bucket. 

There's been a change in how we are going to operationalize this and worth discussing. 

First I was going to have this release job run like the Jenkins job on a schedule and then trigger the deploy jobs to prod automatically. However, when we move this pipeline Gabe wants to introduce this opportunity to introduce the MR process. This means that prod and sandbox deploys will have to happen under a MR process which I'll link in the readme.  The consequence of this operationally shift would result in changing the file based upon how the team would like to handle release/deploy functionality. It's going to be a discussion we will need to have but either of those scenarios are easy enough to build in CodeBuild. 

The original idea was to mimic Jenkins:
Cron job -> release job -> deploy job to production

Here are the laid out:
Deploy Scenarios
CI on PR -> deploy to review bucket
CI on master -> archive build artifacts for release -> deploy job to dev and staging 
? release
? prod deploy

2020-10-01 17:57 UTC, gileswells requested changes
Looks solid but just a couple questions.

2020-10-01 18:08 UTC, duganth-va commented on cicd/buildspec-release.yml
> +          echo ${ci_status}
Will do!

2020-10-01 18:11 UTC, duganth-va commented on cicd/buildspec-release.yml
> +      if [[ CODEBUILD_BUILD_SUCCEEDING -eq 0 ]]; then
Yes I think a release notification makes sense for successes

2020-10-13 14:08 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +        fi
does this block need to be commented out when merged pending #457, similarly to the block for this release job in the CI buildspec?

... and, now that i'm mentioning it, should that block be uncommented in this PR?

2020-10-13 14:12 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +          gh release upload ${NEW_TAG} "release/developer-portal-${env}-${VERSION}.tar.bz2#${NEW_TAG}_${env}.tar.bz2"
this is perhaps a "i need to read the docs more carefully" comment, but it took me a really long time to figure out what the # was doing in this command. might be worth calling out in a comment or something that the string after the "#" is the display name of the asset. that said, you could dismiss this as me needing to read the whole docs page before trying to understand the thing.

... also makes me wonder why they couldn't make the display name be its own optional arg, but that's neither here nor there

2020-10-13 14:13 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +#  - slackpost.sh
tiny thing, but do you want to call out `increment.sh` here?

2020-10-13 14:40 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +          aws codebuild start-build --project-name developer-portal-deploy --environment-variables-override name=RELEASE,value=${NEW_TAG}
does the `developer-portal-deploy` project still need to be created in Terrraform?

2020-10-13 14:58 UTC, duganth-va commented on cicd/buildspec-release.yml
> +          gh release upload ${NEW_TAG} "release/developer-portal-${env}-${VERSION}.tar.bz2#${NEW_TAG}_${env}.tar.bz2"
I throughly enjoy comments to explain tools in the context in which they are used so this is valuable to me and I'll add the comment.  Especially since the `#` in line 72 is serving a completely different purpose it may cause much confusion. thanks!

2020-10-13 15:00 UTC, duganth-va commented on cicd/buildspec-release.yml
> +          aws codebuild start-build --project-name developer-portal-deploy --environment-variables-override name=RELEASE,value=${NEW_TAG}
no all the Terraform infrastructure has been created so i'll comment this out prior to merge! I'll add a comment here as well!

2020-10-13 15:04 UTC, duganth-va commented on cicd/buildspec-release.yml
> +        fi
Yeah we will uncomment this until we transition to deployments with codebuild.

Yes we should thanks uncomment that in this PR thanks!!

2020-10-14 17:03 UTC, mjlumetta approved these changes
💯 ✨

2020-10-14 17:05 UTC, mjlumetta commented on cicd/buildspec-release.yml
> +      - OLD_TAG=$(git tag --sort=-creatordate | grep cb- | head -1)
that seems great to me! thanks for the clarification here

2020-10-14 17:20 UTC, duganth-va commented on cicd/buildspec-release.yml
> +    ENVS: "dev staging production"
its undergoing a change right now,  when the new documentation comes out (should be shortly) I'll add to docs and update in slack.

2020-10-14 20:05 UTC, gileswells approved these changes
LGTM

2020-10-14 22:53 UTC, rtravitz submitted a review, later dismissed
Makes sense ✨

2020-10-16 15:54 UTC, anthony-kopczyk reviewed
This looks good to me. Most of the questions I had were already answered on previous reviews and discussions.

@gileswells I'm good with approval on this PR, like the other one, as long as you are too.

2020-10-16 15:54 UTC, anthony-kopczyk commented on cicd/buildspec-ci.yml
> +        fi
Nothing to change, but are we going to be renaming branches to `main`? This will require an update at that point. Might be good to point in a jira ticket now for it or added to another jira ticket if there isn't already one.

2020-10-16 15:54 UTC, anthony-kopczyk commented on cicd/buildspec-release.yml
> +          gh release upload ${NEW_TAG} "release/developer-portal-${env}-${VERSION}.tar.bz2#${NEW_TAG}_${env}.tar.bz2"
I like the comment, and I don't think a change is needed. For readability I think it might be more clear if the comment is moved to within the for loop, so it's closer to that line. Even seeing you were going to add a comment, I still didn't realize it was there until I looked around for it more. That's not necessary though before merging, and maybe there's a reason not to move it into the for loop for similar readability reasons - would kind of clutter the for loop.

2020-10-16 16:16 UTC, gileswells approved these changes
LGTM

2020-10-16 17:15 UTC, rtravitz approved these changes

2020-10-16 18:01 UTC, merged