Api 2543: Hook migration for PageContent
department-of-veterans-affairs/developer-portal pull request #449
Opened 2020-10-01 14:58 UTC by anthony-kopczyk

### Description
Jira Ticket: https://vajira.max.gov/browse/API-2543

This upgrades the PageContent component to use react hooks.

This component uses Location, but until we upgrade react-router and react-router-dom we can't use those associated react hooks. We'll have to revisit this component to update it to use the routing hooks in another PR after the upgrades.

### Process
- [N/A] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed

### Requested feedback
I tried to exactly mimic the previous functionality where it only scrolls when the component updates, not on the initial render. I can change it to also scroll on initial render, but that causes an issue in the unit tests. I'd like feedback on that.

2020-10-01 15:59 UTC, gileswells requested changes

2020-10-01 15:59 UTC, gileswells commented on src/components/PageContent.tsx
> +const focusAndScroll = (elementToFocus?: HTMLElement | null) => {
Is there a reason that you're made this optional and have a null option available? From what I can tell there's no instance where the PageContent component is rendered that the `<main>` element isn't included.

2020-10-01 16:49 UTC, mjlumetta requested changes
there's an issue with the conditional checking that should be fixed. other than that, got some general refactor questions about how this component works, but nothing that needs to be addressed.

i think running `useEffect` equivalently on the initial render and subsequent renders is part of the idea behind the hook, right? or what you're encouraged to do. anyway, i think using the ref is a fine solution for that. or maybe even a boolean for that if we don't need the value? dunno.

2020-10-01 16:49 UTC, mjlumetta commented on src/components/PageContent.tsx
> +    const currentPath = location.pathname && location.hash;
i'm a bit confused by how this works. wouldn't this always be the value of the `hash`?

2020-10-01 16:49 UTC, mjlumetta commented on src/components/PageContent.tsx
> +    const prevLocation: string | null = prevLocationRef.current;
haven't entirely wrapped my head around this one yet, but is this ref entirely necessary? i wonder if it could be eliminated by using more precise dependencies for `useEffect` - so `location.pathname`, basically. talking through this...

- the old condition was "do not execute if the old path and new path are the same and there is a hash". negated, it's "do execute if the old path and the new path are different or if they are the same but there is no hash". so the old behavior _almost_ forks on whether or not `location.pathname` has changed.
- the hash piece, when there is a hash, means that if we've navigated to an anchor link in the same page, we don't want to set the focus on the main content. including it, as opposed to leaving the condition as `props.location.pathname !== prevProps.location.pathname`, means that the focus + scroll _should_ happen if we are on the same page but navigate from a URL for the page with a hash anchor to one without one. my question for you and other reviewers is, is that exception meaningful, or should we stop worrying about the hash entirely and say this effect always happens if the `pathname` changes?

on the other hand, maybe we do need the ref to distinguish between the initial render vs subsequent renders... meh. but we could cut out the rest of the conditional where the explicit path check happens.

2020-10-01 16:49 UTC, mjlumetta commented on src/components/PageContent.tsx
> +    <main id="main" ref={mainRef} tabIndex={-1}>
could conceivably get rid of the `mainRef` ref if we wanted and replace it with `document.getElementById('main')?.focus()` or `document.querySelector('main')?.focus()`. we've used that more vanilla JS approach elsewhere for skip nav links, although those had to jump between multiple components, so it was more necessary. worth considering but no changes necessary

2020-10-01 16:49 UTC, mjlumetta commented on src/components/PageContent.tsx
> +  window.scrollTo(0, 0);
should we actually be scrolling to the top of the page or to the top of main? i don't think it super matters here given the size of the header, but wanted to ask

2020-10-01 16:49 UTC, mjlumetta commented on src/components/PageContent.tsx
> +    const currentPath = location.pathname && location.hash;
tested and confirmed. this value doesn't ever reflect the path, and it causes `focusAndScroll` to execute in every render (unless i guess you go to the same anchor? or maybe the same anchor on a different page? didn't try these). the focus and scroll for same page anchor links still works though, it appears; guessing that's because those are implemented via click handlers farther on? unsure.

2020-10-01 19:50 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +const focusAndScroll = (elementToFocus?: HTMLElement | null) => {
I'll look into it. I think React was complaining that it was possibly not initialized, but that could have been due to another bug.

2020-10-01 19:55 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +  window.scrollTo(0, 0);
I don't know. This is from the previous code too. As a user I generally prefer that it would scroll to the top when navigating if it's effectively loading a different page. Maybe we need to reevaluate this code completely? I really don't know why it's here, but assumed I'd leave everything functionally equivalent.

2020-10-01 19:57 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const currentPath = location.pathname && location.hash;
Yes. I had the same question. This is a direct copy from the preexisting code. I didn't look into it specifically but assumed it was due to compatibility with an older browser or something that might not have hash defined. Will look into this further.

2020-10-01 20:01 UTC, mjlumetta commented on src/components/PageContent.tsx
> +  window.scrollTo(0, 0);
i think it works. i agree that you're right not to change it, and i believe that is the intended functionality. was confusing myself a bit with the focus and scrolling (since those are really different things - scroll to top of the body, focus on main).

2020-10-01 20:04 UTC, mjlumetta commented on src/components/PageContent.tsx
> +    const currentPath = location.pathname && location.hash;
i think there's an order of operations thing going on here. the old condition is `prevProps.location.pathname === location.pathname && location.hash`. in that conditional, the `===` gets evaluated first and then the `&&`. so the condition is the same as `(prevProps.location.pathname === location.pathname) && location.hash`.

2020-10-02 13:44 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const currentPath = location.pathname && location.hash;
Ooh. Good eye! Thanks!

2020-10-02 13:46 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    <main id="main" ref={mainRef} tabIndex={-1}>
For this case I'll leave it with the ref for now. My thinking is to use hooks wherever it is easy-ish. But, definitely will keep that in mind for other situations like the skip nav links.

2020-10-02 13:49 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const prevLocation: string | null = prevLocationRef.current;
I'll reevaluate the need for the logic. My intent was to keep everything that was originally there, but the logic doesn't make a whole lot of sense to me either. - and then it's a little bit more confusing because we have other links that scroll down for hashlinks that basically overrides this behavior.

2020-10-02 18:03 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +const focusAndScroll = (elementToFocus?: HTMLElement | null) => {
Should be fixed in the latest commit. I think I got confused and thought mainRef had a chance to be undefined, which really doesn't make any sense now that I look at it again.

2020-10-02 18:15 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const prevLocation: string | null = prevLocationRef.current;
I think we do want the distinction. If you navigate into API documentation and want to back to the top of the page using the left side nav, it doesn't navigate up without the `scroll and focus when there is no hash`

2020-10-02 18:17 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const prevLocation: string | null = prevLocationRef.current;
I think the issues with this are likely resolved in the latest commit. I restructured to use two effects, one for when the pathname changes and one for when the hash changes.

2020-10-02 18:19 UTC, anthony-kopczyk commented
I added a fix for ModalController to this. I can move it into a separate PR if we think this one might take more before being able to approve.

2020-10-02 18:21 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +  }, [location.hash]);
These effects are going to cause unnecessary re-renders right? I'm not sure how to really resolve that right now, but I think this matches the previous existing functionality.

2020-10-02 19:43 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    const prevLocation: string | null = prevLocationRef.current;
I went ahead and restructured back to a single effect with fixing the condition.

I think the separate effects may have worked but for the sake of getting this PR through I switched back to make the review easier.

I tried to break the logic into a When/If.
- When the location changes, if the path changes we focus and scroll.
- When the location changes, if there is no hash we focus and scroll.

2020-10-02 20:11 UTC, johanna-adhoc commented on src/components/PageContent.tsx
> +    if (prevLocationRef.current) {
The PR looks good. The only thing left to change is that this condition should be checking mainRef object instead of prevLocationRef. This condition seems to be there just to make sure the DOM element exists before attempting to focus it, but because the method focusAndScroll already does that, this condition can be totally removed and the method called directly.

2020-10-05 12:44 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    if (prevLocationRef.current) {
Oh. My intent behind this was to keep it from triggering on the initial component load. Though, I suppose it shouldn't matter if this kicks off at that point. I'll take that out.

2020-10-05 13:04 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    if (prevLocationRef.current) {
Should be resolved now. Removing that caused an issue with the tests. When the App test tried to render, it runs `focusAndScroll` and `window.scrollTo` wasn't defined. I set it as a jest mock for now. I'm not sure where we'd want to put that kind of thing or maybe there's a package somewhere that we could use instead.

2020-10-05 16:38 UTC, anthony-kopczyk commented on src/hooks/ModalController.tsx
> +
Wondering if I should have kept this as it was previously and just added modalVisible as a dependency to `useEffect`. But then that would require redefining that function every time modalVisible updates, and that doesn't seem right to me. But, with using the ref, I have the overhead of adding a ref and also creating the extra setter. I'm wondering what is more efficient.

When modalVisible changes it has to re-render anyway, so. I guess I'm going to be looking into some react docs. If anyone has thoughts, please comment!

2020-10-05 19:22 UTC, TS000 commented on src/hooks/ModalController.tsx
> +
I like the idea of adding modalVisible to useEffect.

2020-10-07 13:50 UTC, johanna-adhoc submitted a review, later dismissed
LGTM

2020-10-07 17:33 UTC, johanna-adhoc submitted a review, later dismissed
💯

2020-10-07 18:50 UTC, mjlumetta requested changes
focus is getting set on main on the initial page load, and i think we want that to still be set to body. can be fixed with a check on that ref, i believe. other than that it looks ready.

2020-10-07 18:50 UTC, mjlumetta commented on setupJest.ts
> +import 'jest';
is `jest` not globally defined here?

2020-10-07 18:50 UTC, mjlumetta commented on src/components/pageContent/PageContent.tsx
> +  const prevLocationRef = React.useRef<string | null>(null);
would suggest naming this `prevPathRef` if you make another commit but def don't make another commit for that (motivation is specifically from just having refactored some path/hash logic in the side nav)

2020-10-07 18:50 UTC, mjlumetta commented on src/hooks/ModalController.tsx
> +
did you happen to find any references informing the ref decision? would love to learn from those and/or have something linked in a comment, if there was anything external informing this decision

2020-10-07 18:50 UTC, mjlumetta commented on src/components/pageContent/PageContent.tsx
> +    if (prevLocationRef.current !== location.pathname || location.hash) {
i think we also still need a `prevLocationRef.current != null` check here. focus skips the header on initial page load, which isn't what we want, i don't think.

2020-10-07 19:43 UTC, gileswells requested changes
Still can slim down the `focusAndScroll` params in my view.

2020-10-07 19:43 UTC, gileswells commented on src/components/pageContent/PageContent.tsx
> +const focusAndScroll = (elementToFocus: HTMLElement | null) => {
I cannot find a way that that you'd need null as an option. There is no condition on `<main>` so it would never be null.

2020-10-07 19:43 UTC, gileswells commented on src/components/pageContent/PageContent.tsx
> +  if (elementToFocus) {
Without the above null option there is no need for this conditional.

2020-10-08 11:51 UTC, anthony-kopczyk commented on src/components/pageContent/PageContent.tsx
> +const focusAndScroll = (elementToFocus: HTMLElement | null) => {
I agree that I don't think it can actually be null where it's called, but when I try to remove `| null` from the method, I get lint errors in my IDE that `mainRef.current` could be null.

2020-10-08 11:55 UTC, anthony-kopczyk commented on src/components/pageContent/PageContent.tsx
> +    if (prevLocationRef.current !== location.pathname || location.hash) {
Shoot. I knew that I had that there for a reason!

2020-10-08 12:10 UTC, anthony-kopczyk commented on src/hooks/ModalController.tsx
> +
I didn't find anything on specifics of using an effect or a ref. But I am definitely debating the efficiency of one or the other. I need to get deep into react with when it renders and those kinds of things.

I think, unless people have strong feelings, I'm going to leave it as it is now, and might revisit it later.

2020-10-08 12:13 UTC, anthony-kopczyk commented on src/components/PageContent.tsx
> +    if (prevLocationRef.current) {
Mike pointed out that without this the header doesn't get focus on initial page load. So we have to have something checking if `prevRef.current` is null to determine if it's initial page load or not. I added this back in in the latest commit.

2020-10-08 12:14 UTC, anthony-kopczyk commented on setupJest.ts
> +import 'jest';
It is defined globally. I ended up reverting the changes to this file. With the PageContent effect only happening when it's not an initial page load, the tests don't trigger `scrollTo` at the moment.

2020-10-08 12:15 UTC, anthony-kopczyk commented on src/components/pageContent/PageContent.tsx
> +    if (prevLocationRef.current !== location.pathname || location.hash) {
Should be fixed in the latest commit.

2020-10-08 12:19 UTC, anthony-kopczyk commented on src/components/pageContent/PageContent.tsx
> +  const prevLocationRef = React.useRef<string | null>(null);
I went ahead and made this change. The ref is storing pathname not the entire location object as well, so this is cleaner.

2020-10-08 12:19 UTC, anthony-kopczyk commented on src/components/pageContent/PageContent.tsx
> +    if (prevLocationRef.current !== location.pathname || location.hash) {
Should be fixed in the latest commit.

2020-10-08 12:22 UTC, anthony-kopczyk commented on src/hooks/ModalController.tsx
> +
If we use effect, then we need to pass in the `modalVisible` field as a dependency. So every time it toggles the modal will need a re-render (which I guess it would anyway?). But then with the ref, we don't need to pass that as a dependency, so it doesn't need to redefine the effect on re-renders - but the ref is an extra variable to consider. The pros/cons seem about even to me at the moment.

2020-10-08 15:57 UTC, johanna-adhoc approved these changes

2020-10-09 18:09 UTC, gileswells commented on src/components/pageContent/PageContent.tsx
> +const focusAndScroll = (elementToFocus: HTMLElement | null) => {
`const mainRef = React.useRef() as React.MutableRefObject<HTMLElement>;` That would resolve the issue with the | null but in the grand scheme of things that's literally what I just found Googling on SO so I'm not sure this would the "right" answer as much as it is an answer.

If you wish to use it or not I will leave entirely up to you. I no longer have a strong opinion either way at this stage.

2020-10-09 18:15 UTC, gileswells submitted a review, later dismissed
LGTM :shipit:

2020-10-09 18:23 UTC, mjlumetta submitted a review, later dismissed
✨ 🚀

2020-10-09 18:32 UTC, johanna-adhoc approved these changes

2020-10-09 18:32 UTC, TS000 approved these changes

2020-10-09 18:42 UTC, merged