Fix ESLint checks for Support components
department-of-veterans-affairs/developer-portal pull request #458
Opened 2020-10-05 14:28 UTC by mjlumetta

### Description

in support of [API-1323](https://vajira.max.gov/browse/API-1323). fixes ESLint errors in `src/containers/support`.

see #452 for the opening PR for configuring ESLint. that PR also includes adding ESLint to the Jenkins CI job. i can add that here as well if this one ends up going first for whatever reason, but going to default to letting that PR get merged first.

### Process

- [n/a] Tests added or updated for change
  - 
- [n/a] Docs updated
- [n/a] Accessibility concerns have been considered and addressed
  - no UI changes

### Requested feedback

- what rules would you like to see turned on right now that aren't there?
- would you like to see different config for rules that are there? could go either way on some of these rules, so if you want to toggle any on or off, please let me know.
- how would you like to handle situations where we have to do some kind of patching and/or disabling rules? there are some that we aren't set up for well yet (example: using functions for all React components will make some things easier once hooks are done) or where the rule doesn't work well (example: `@typescript-eslint/indent`).

2020-10-05 19:31 UTC, gileswells requested changes

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +        {' '}
Extra space should be removed

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +        visit the <a href="http://www.va.gov">US Department of Veterans Affairs website</a> to
Linking off site should include a `target="blank"`

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +        <a href="https://iris.custhelp.va.gov/app/answers/list">(IRIS)</a>.
Linking off site should include a `target="blank"`

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +          <a href="https://developer.va.gov/apply">API key for the Facilities API</a>. Once
This should use a `<Link>` tag for an internal link

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportOverview.tsx
> +  props: ISupportOverviewProps,
Shouldn't we update this `I` named interface since we're touching it?

2020-10-05 19:31 UTC, gileswells commented on src/containers/support/SupportOverview.tsx
> +      {props.sections.map((section: ISection) => (
Another `I` named interface that could be updated

2020-10-05 19:31 UTC, gileswells commented on tslint.json
> +    "jsx-boolean-value": false
I like this change. I am assuming this will only apply to a parameter that would have been set to `attr={true}` and not something like `attr={foo === bar}` correct?

2020-10-07 21:16 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.tsx
> +  public constructor(props: ISupportContactUsFormProps) {
yes, good point. i put that rule in #452 but not here. will add.

2020-10-07 21:24 UTC, mjlumetta commented on tslint.json
> +    "jsx-boolean-value": false
yeah. this specifically isn't making the change - the TSLint rule conflicts with the ESLint rule, so this is shutting the TSLint rule off. but yes, i believe anything that's calculated at runtime shouldn't be covered by the rule.

you can see the TSLint `jsx-boolean-value` rule in [`tslint-react`](https://github.com/palantir/tslint-react#rules) and the ESLint rule `jsx-boolean-value` in [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md). the TSLint rule defaults to "always" (as in always specify `attr={true}`) and the ESLint rule defaults to "never". so yeah, we'll go with the "never" default, unless anyone feels strongly to the contrary. glad you like it, anyway.

2020-10-07 21:28 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +        {' '}
good catch! fixed

2020-10-07 21:29 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +          <a href="https://developer.va.gov/apply">API key for the Facilities API</a>. Once
good catch, thanks! also updating to be an internal URL

2020-10-07 21:40 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +        visit the <a href="http://www.va.gov">US Department of Veterans Affairs website</a> to
i would prefer not to do this as a blanket rule for the general kinds of reasons articulated in [this article](https://css-tricks.com/use-target_blank/) - mainly, that the default behavior is usually appropriate, and that users can choose to override that default behavior with a modifier key if they choose. if you or others feel strongly about it, though, i can change it.

2020-10-08 15:46 UTC, gileswells requested changes
Couple small naming comments but overall looks great.

2020-10-08 15:46 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> +interface ContactUsFormState {
Why did you drop `Support` off the front of the interface name? I'd prefer we stick with the pattern that is `ComponentName(State|Props)`

2020-10-08 15:46 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +        visit the <a href="http://www.va.gov">US Department of Veterans Affairs website</a> to
Based on my history on some seriously competitive SEO ranking sites this was true there. That being said doing more research with your link and others I would tend to agree that as a blanket rule it's not the greatest. I concede by position. 👍

2020-10-08 15:46 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +  const content: IPanelContent[] = props.questions.map((q: SupportQuestion) => ({
I missed this `I` named interface in my previous review.

2020-10-08 18:55 UTC, gileswells requested changes
Add back Support prefix

2020-10-08 18:55 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> +interface ContactUsFormState {
```suggestion
interface SupportContactUsFormState {
```

2020-10-08 18:55 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> +interface ContactUsFormProps {
```suggestion
interface SupportContactUsFormProps {
```

2020-10-08 18:55 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> +  ContactUsFormProps,
```suggestion
  SupportContactUsFormProps,
```

2020-10-08 18:55 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> +  ContactUsFormState
```suggestion
  SupportContactUsFormState
```

2020-10-08 18:58 UTC, mjlumetta commented on src/containers/support/SupportFAQ.tsx
> +  const content: IPanelContent[] = props.questions.map((q: SupportQuestion) => ({
fixed. i think it didn't lint for this since it was defined in a different file? anyway, no longer a problem

2020-10-08 19:31 UTC, gileswells approved these changes

2020-10-08 19:31 UTC, gileswells commented on src/components/GroupedAccordions.tsx
> +  IGroupedAccordionsProps,
Just leave a mental note for these two. Not worth dealing with now. Rather get it merged.

2020-10-08 19:31 UTC, gileswells approved these changes

2020-10-08 19:33 UTC, mjlumetta commented on src/components/GroupedAccordions.tsx
> +  IGroupedAccordionsProps,
yeah... would rather deal with it in-scope, should be on #452. merging now.

2020-10-08 19:33 UTC, merged