2527/hooks migration
department-of-veterans-affairs/developer-portal pull request #462
Opened 2020-10-05 16:23 UTC by TS000

### Description
Jira Ticket: https://vajira.max.gov/browse/API-2527

Moved the Class component to modern React Hooks component: 
* ApiKeyAuth: ✔️   
* CategoryPage: ✖️ 
* AuthorizationDocs: ✖️ 

Both CategoryPage and AuthorizationDocs use a React Router version (v4) that is not compatible with React Hooks so no changes were made to those files.

### Process

- [N/A] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed

### Requested feedback
Is there a source of truth for ReactRouter of which features work and which don't with Hooks? I'd like feedback on if I approached CategoryPage and AuthorizationDocs correctly.

2020-10-05 16:43 UTC, anthony-kopczyk requested changes
Think this may be as a result of our conversation earlier when I said about not switching some files to hooks that are dependent.

What you have looks good. While we can't get them switched over to use hooks, we can go ahead and switch over components to be functional even if we need to still pass in routing properties as props instead of using hooks.

Can you make changes to the other two files, even thought we'll still be passing in the routing as props?

2020-10-05 17:32 UTC, TS000 commented
All set @anthony-kopczyk. I agree converting them to functional is the way to get them closer to hooks without breaking React Router.

2020-10-05 19:48 UTC, anthony-kopczyk requested changes
Similar to the other PR. We've been adding return types to the functions `JSX.Element`. For the eslinting rules we'll eventually enable, we also want to enforce arrow hooks as long as possible.

2020-10-06 17:37 UTC, anthony-kopczyk requested changes
There are two files that we should switch to arrow functions, and then a few things that can address but don't necessarily need to address.

2020-10-06 17:37 UTC, anthony-kopczyk commented on src/containers/Home.tsx
> +const HomeSection = ({ariaLabel, imageSrc, title, children} : {ariaLabel: string; imageSrc: string; title: string; children: React.ReactNode}): JSX.Element => (
I think this is only used here, so doesn't need done. But this would be a little cleaner if the type was pulled out into an interface. Again, I think this is the only place that it's used, so probably not necessary. Or, thoughts on doing it this way?

```
const HomeSection = (props: {
  ariaLabel: string;
  imageSrc: string;
  title: string;
  children: React.ReactNode}
): JSX.Element => (
```

This way we'd need to access everything via `props.prop` or have a separate line
`const { ariaLabel, imageSrc, title, children } = props;`

Not sure best way to write it.

2020-10-06 17:37 UTC, anthony-kopczyk commented on src/containers/Home.tsx
> +          </h2>
Thoughts on changing this to `<h2>{ title }</h2>`? This is another, I'm not sure which way would be better. haha! Maybe we already have a lint rule defined for this.

2020-10-06 17:37 UTC, anthony-kopczyk commented on src/containers/documentation/AuthorizationDocs.tsx
> +export function AuthorizationDocs({ match }: RouteComponentProps<IApiNameParam>): JSX.Element {
Our eslint rules (there's a plugin on vscode that you should be able to install that will highlight things), prefer arrow functions. Can you update this to an arrow function?

2020-10-06 17:37 UTC, anthony-kopczyk commented on src/containers/documentation/CategoryPage.tsx
> +export default function CategoryPage({ match }: RouteComponentProps<IApiNameParam>): JSX.Element {
Same as the other file. Can you update this to an arrow function?

2020-10-07 12:09 UTC, anthony-kopczyk approved these changes
I scanned through again and don't see anything else. Everything else that's been mentioned has been addressed. Good to go!

2020-10-07 13:39 UTC, merged