Api 1899/upgrade react router
department-of-veterans-affairs/developer-portal pull request #468
Opened 2020-10-07 16:35 UTC by mjlumetta

### Description

supports [API-1899](https://vajira.max.gov/browse/API-1899).

does some package upgrades: 
- `react-router` from 4.3.1 to 5.2.0
- `react-router-dom` from 4.3.1 to 5.2.0
- `@types/react-router` from 4.4.3 to 5.1.8
- `@types/react-router-dom` from 4.3.1 to 5.1.6
- `react-router-hash-link` from 1.2.1 to 2.1.0

as a result of the React Router upgrade, path matching in nav links changed, so i updated the `SideNavEntry` component accordingly. while i was touching that component, i refactored its tests and the `navHashLinkIsActive` function (a) to be more readable and (b) to allow an "exact" match when there's a hash that represents shared site anchor (so `#main` and `#page-header`.
- to achieve the second outcome, i added a `sharedAnchors` prop. ideally, we'll never need to explicitly set this prop and can always rely on the default prop value, but who knows. seeking feedback on this approach.

### Process

- [X] Tests added or updated for change
  - refactored and updated tests in `SideNav.test.tsx`
- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed

comprehensively tested the active nav link highlighting manually. reviewers should probably try this out themselves.

### Requested feedback

- is the refactoring for `SideNavEntry`, both the source code and tests, useful? what could be improved?

2020-10-07 16:36 UTC, mjlumetta commented on src/components/MainNavItem.tsx
> +  isActive: (match: Match | null) => boolean;
this is the functional change here

2020-10-07 16:38 UTC, mjlumetta commented on src/components/NavBar.tsx
> +  private checkActiveNavLink = (match: Match | null) => {
this is the functional change here

2020-10-07 18:24 UTC, anthony-kopczyk reviewed
Everything I looked at so far seems good. I didn't get a look at the test file though.

2020-10-07 18:24 UTC, anthony-kopczyk commented on SitemapBuilderWebpackPlugin.js
> +      );
Was this a result of prettier column size? It looks odd to me, but if it's column size related then I'm cool with it.

2020-10-07 18:24 UTC, anthony-kopczyk commented on SitemapBuilderWebpackPlugin.js
> +const MemoryFileSystem = require('memory-fs');
It's cool we're using this. I used this package once on a project I never fully got off the ground to write some files to end users without needing to put them on disk. Nice to see the package gets used.

2020-10-07 18:24 UTC, anthony-kopczyk commented on SitemapBuilderWebpackPlugin.js
>            .catch(err => this.finishWithError(err, compilation, callback));
I haven't looked at all. Guessing we can't change this to async/await? Not sure what version this js file is running.

2020-10-07 18:24 UTC, anthony-kopczyk commented on SitemapBuilderWebpackPlugin.js
> +      .save(path.join(paths.appBuild, 'sitemap.xml')).sitemaps[0].cache;
I like the old way this was written with the extra set of parentheses. It makes it more obvious that this was being set to the cache and kind of separates it from the filter/applyParams/build/save methods.

2020-10-07 18:24 UTC, anthony-kopczyk commented on src/components/SideNav.tsx
> +  };
Good comments!

2020-10-07 18:35 UTC, mjlumetta commented on SitemapBuilderWebpackPlugin.js
> +      const vmContext = dom.getInternalVMContext();
new API for this in JSDOM 16: https://github.com/jsdom/jsdom#interfacing-with-the-nodejs-vm-module-using-getinternalvmcontext

2020-10-07 19:01 UTC, mjlumetta commented on SitemapBuilderWebpackPlugin.js
> +      );
yes i'm pretty sure that was it. we do need to do some standardization on our prettier setup so we don't constantly get these noisy changes (that said, this one would've happened anyway because this file rarely gets updated)

2020-10-07 19:02 UTC, mjlumetta commented on SitemapBuilderWebpackPlugin.js
> +const MemoryFileSystem = require('memory-fs');
all credit goes to @nfasulo!!

2020-10-07 19:05 UTC, mjlumetta commented on SitemapBuilderWebpackPlugin.js
> +      .save(path.join(paths.appBuild, 'sitemap.xml')).sitemaps[0].cache;
how about this rewrite:

```
const todoNameThis = new Sitemap(sitemapConfig.topLevelRoutes())
      .filterPaths(sitemapConfig.pathFilter)
      .applyParams(sitemapConfig.paramsConfig)
      .build(prodURL)
      .save(path.join(paths.appBuild, 'sitemap.xml'));
const sitemap = todoNameThis.sitemaps[0].cache;
```

2020-10-07 19:13 UTC, mjlumetta commented on SitemapBuilderWebpackPlugin.js
>            .catch(err => this.finishWithError(err, compilation, callback));
that's a good question, i'm not sure. in general, i'd prefer not to refactor this too much because i'm not super familiar with how the webpack plugin works. i can if you'd like me to look into it, though.

2020-10-08 18:37 UTC, gileswells requested changes

2020-10-08 18:37 UTC, gileswells commented on src/components/NavBar.tsx
> +              inMenu={true}
is this an tslint requirement till the eslint stuff gets merged and chalks this up as a fault?

2020-10-08 19:16 UTC, mjlumetta commented on src/components/NavBar.tsx
> +              inMenu={true}
yeah, exactly. i don't really want to mess with the ESLint stuff until the PR for each file/directory/whatever is merged, and then `npm run eslint` should enforce that for everything that's been covered so far. this is on #452, so it should be fixed soon, i'll just have to deal with the many, many merge conflicts

2020-10-08 19:54 UTC, mjlumetta commented on package-lock.json
> +          "resolved": "http://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz",
i took a look and it and i cannot figure out why. i found [this thread](https://registry.npmjs.org/) from 2ish years ago about basically this issue that says it was a bug in `npm` related to misconfig on the part of the package auathors, but it also says it was fixed? also, apparently NPM uses HTTPS regardless of what `package-lock.json` says? confusing. anyway, in my environment, the result of `npm config get registry` is `https://registry.npmjs.org/`, and my `npm` is version 6.14.8. i deleted my `node_modules`, checked out `package-lock.json` from master, cleared the cache, and reinstalled, and it still had some `http`s in there.

i can keep looking into this if you want. if it's okay with you, though, i'd say that this kind of churn is acceptable when we're actually updating `package.json`, although not otherwise. one thing i've learned recently that i've found useful is `npm install --no-save` for when i need to download already installed packages, which installs packages without updating `package.json` or the lockfile. that prevents those noisy lockfile-only commits. thoughts on this? will keep investigating if you'd like to try to resolve it. let me know and we can go from there.

2020-10-12 14:58 UTC, gileswells approved these changes
Looks good to go. Ideally we'd get a higher version that 5.2.0 but there hasn't been even a comment on my issue asking for a new release. https://github.com/ReactTraining/react-router/issues/7647

2020-10-12 15:26 UTC, merged