Updates for sentry 10
department-of-veterans-affairs/developer-portal pull request #472
Opened 2020-10-08 18:16 UTC by charleystran

### Description
This PR updates the DSN Settings for sentry so that the portal works properly with sentry 10. 

The sentry project for the dev portal frontend lives at http://sentry10.vfs.va.gov/organizations/vsp/issues/?project=6

2020-10-08 18:25 UTC, kfrz requested changes
Looks good but I forgot we have to use `*sentry10_internal*` instead

2020-10-08 18:25 UTC, kfrz commented on .env.dev
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```

2020-10-08 18:25 UTC, kfrz commented on .env.production
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```

2020-10-08 18:25 UTC, kfrz commented on .env.staging
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```

2020-10-08 18:42 UTC, kfrz approved these changes
:+1: Thank you for the update!

2020-10-08 23:19 UTC, rtravitz submitted a review, later dismissed
This looks good to me ✨

2020-10-09 00:08 UTC, nathanbwright approved these changes

2020-10-09 00:41 UTC, kfrz requested changes
Sorry, not sure how I screwed that up, it's `sentry10-internal` not `sentry10_internal` 

:face_with_head_bandage: 

Suggestions made

2020-10-09 00:41 UTC, kfrz commented on .env.dev
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
```

2020-10-09 00:41 UTC, kfrz commented on .env.production
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
```

2020-10-09 00:41 UTC, kfrz commented on .env.staging
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10_internal.vfs.va.gov/6
```suggestion
REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
```

2020-10-09 00:42 UTC, kfrz approved these changes

2020-10-09 13:10 UTC, mjlumetta approved these changes
looks good to me. my only question is, for the environments, it doesn't appear those have been created yet. will they be created dynamically as errors come in, or should we create them proactively?

2020-10-09 13:10 UTC, mjlumetta commented on .env.staging
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
what's up with the `-internal` parts of the subdomain? don't see that on the DSN in the UI

2020-10-09 19:38 UTC, kfrz commented on .env.staging
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
Yeah - this is something that's required so that client browsers can access tools from the VPN via `sentry10.vfs.va.gov`. This DNS will point at the private ENI directly. See [here](https://github.com/department-of-veterans-affairs/devops/pull/7763) for more context.

2020-10-09 19:38 UTC, kfrz commented on .env.staging
> +REACT_APP_SENTRY_DSN=http://d5646ae5a407485d97122de7224039b2@sentry10-internal.vfs.va.gov/6
The environments will be created dynamically to answer your parent question.

2020-10-12 14:47 UTC, merged