API-2497: Hooks Migration Navbar & HoverImage Components
department-of-veterans-affairs/developer-portal pull request #473
Opened 2020-10-08 18:46 UTC by alexandervalencia

### Story [API-2497](https://vajira.max.gov/browse/API-2497)

Migration of NavBar and HoverImage components from classes to hooks/arrow functions.

### Process

- [x] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed

### Requested feedback

All feedback welcome.

2020-10-08 19:57 UTC, anthony-kopczyk requested changes
Looks good overall. We can add the components to `components/index.ts`. Other than that though, I don't have any comments besides "It's probably a good idea to get somebody else to look over the test files"

2020-10-08 19:57 UTC, anthony-kopczyk commented on src/components/NavBar/NavBar.tsx
> +  const [visibleSubNavs, setVisibleSubNavs] = React.useState({ documentation: false });
I know this was preexisting functionality and was maybe intended for scalability, but it's weird to me we have `visibleSubNavs` but it only contains data about `documentation`. Makes me think we should only have `documentationVisibility` and `setDocumentationVisibility`. But, I really don't think it's worth changing. Just a comment more than anything.

2020-10-08 19:57 UTC, anthony-kopczyk commented on src/components/NavBar/NavBar.test.tsx
> +import '@testing-library/jest-dom/extend-expect';
I haven't gotten a chance to get familiar with the react testing library things, so if somebody can please review this for me!

I have no comments other than it looks good.

2020-10-08 19:57 UTC, anthony-kopczyk commented on src/components/hoverImage/HoverImage.tsx
> +        alt=""
I know  this is from old code too, but I wonder if we should even be specifying an `alt` value if it's going to be blank. Maybe there's some guidance in 508 compliance on this.

2020-10-08 19:57 UTC, anthony-kopczyk commented on src/containers/News.tsx
> +import HoverImage from '../components/hoverImage/HoverImage';
Can you add the hover image to the `components/index.ts` file so we can use `import { HoverImage } from '../components';`? There should be a few other components in there to use as an example.

2020-10-08 19:57 UTC, anthony-kopczyk commented on src/containers/News.tsx
> +import HoverImage from '../components/hoverImage/HoverImage';
Same goes for the other components that have been updated if they aren't there as well.

2020-10-09 13:32 UTC, alexandervalencia commented on src/components/hoverImage/HoverImage.tsx
> +        alt=""
A11y rules say an alt should always be present, even if it's blank. Ref: https://www.w3.org/WAI/tutorials/images/decorative/

2020-10-09 13:33 UTC, alexandervalencia commented on src/containers/News.tsx
> +import HoverImage from '../components/hoverImage/HoverImage';
Will do! 👍

2020-10-09 15:52 UTC, gileswells requested changes
Overall I think the conversion to hooks looks to be on the right path but I'd like to have a larger discussion about `HoverImage` as a whole in the near future. There's a simple requested change for now to improve it for accessibility reasons included in my review.

2020-10-09 15:52 UTC, gileswells commented on src/components/header/Header.tsx
> +import NavBar from '../navBar/NavBar';
This needs to be updated as it doesn't match the case of the path.
```suggestion
import NavBar from '../NavBar/NavBar';
```

2020-10-09 15:52 UTC, gileswells commented on src/containers/News.tsx
> +import HoverImage from '../components/hoverImage/HoverImage';
This also needs to have the properly cased `HoverImage` on the import

2020-10-09 15:52 UTC, gileswells commented on src/components/hoverImage/HoverImage.tsx
> +      alt=""
We should be passing the alt in from the props so that it can be set. It can be optional if we want but it should be able to be set. Leaving it as always blank is not good accessibility.

2020-10-09 19:58 UTC, alexandervalencia commented on src/components/header/Header.tsx
> +import NavBar from '../navBar/NavBar';
Good catch, somehow the folder name didn't properly update to `navBar`

2020-10-09 20:02 UTC, alexandervalencia commented on src/components/hoverImage/HoverImage.tsx
> +      alt=""
While I agree with you, that wouldn't be considered part of this migration process. We're not trying to update/change any functionality, just conversion from class to function based component.

2020-10-12 13:01 UTC, anthony-kopczyk approved these changes
Looks like the requested changes were addressed.

2020-10-12 13:01 UTC, anthony-kopczyk commented on src/components/navBar/NavBar.test.tsx
> +import { noop } from 'lodash';
Not sure what others think on this. With ES6 we can replace a lot of lodash functionality. Is this preexisting? If it is we don't need to worry about it, but we could replace noop with () => undefined to go pure ES6.

2020-10-13 13:58 UTC, johanna-adhoc approved these changes
LGTM 🚀

2020-10-14 19:01 UTC, gileswells approved these changes
LGTM

2020-10-14 19:09 UTC, johanna-adhoc approved these changes
LGTM

2020-10-14 21:20 UTC, gileswells approved these changes
LGTM

2020-10-14 21:28 UTC, merged