Define specific Swagger UI types and fix ESLint errors in CurlForm
department-of-veterans-affairs/developer-portal pull request #474
Opened 2020-10-09 17:19 UTC by mjlumetta

### Description

fixes ESLint errors in `CurlForm` in support of [API-1323](https://vajira.max.gov/browse/API-1323).

- adds types to `swagger-ui.d.ts`
- refactoring `CurlForm` a bit as part of removing ESLint errors
- adding `CurlForm` tests
  - these use real OpenAPI Specs i've downloaded to `src/__mocks__/openAPIData`. i didn't want to go to the length of defining fake data to cover all the cases. seeking feedback on this decision.

### Process

- [X] Tests added or updated for change
  - added unit tests for `CurlForm`
- [ ] Docs updated
- [X] Accessibility concerns have been considered and addressed
  - labeled environment select, no other changes

### Requested feedback

- is refactoring the `CurlForm` tests so they're faster a prerequisite for merging this PR?
- is it alright to use real OAS data downloaded to JSON files in `src/__mocks__`?

2020-10-09 17:46 UTC, anthony-kopczyk reviewed
Looks good to me, but probably good to get some more sets of eyes on this.

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/__mocks__/fakeCategories.tsx
>  import * as React from 'react';
Do these changes mean we could use `import React from 'react'`?

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +// some tests in this file are long-running because of the expense of rendering Swagger UI,
Hmm. is this why the `ApiDocumentation` test sometimes fails on my laptop if I have a bunch of things running?

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(operationTagHeader.nextElementSibling).not.toBeNull();
Can we use `.toBeTruthy()` here?

I read this a week or two ago and they touch on some jest `expect` conditions that I don't fully understand. But if it came back undefined (can it?) this wouldn't evaluate properly.
https://github.com/adobe/brackets/issues/5479

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(curlHeading.nextElementSibling).not.toBeNull();
Same thing with `.not.toBeNull()`

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +      expect(bodyHeading.nextElementSibling).not.toBeNull();
`.not.toBeNull`

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +});
I think this is good? It's a long file. In the future, might be beneficial, even if we leave CurlForm.tsx intact as is, to split this test file out into multiple chunks.

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
Never heard of fortAwesome. Had to do a few takes to see that fontawesome is from fortawesome. 👍

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +} from 'swagger-ui';
I like the goal of adding these types.

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/types/swagger-ui.d.ts
> +/**
Already said elsewhere, but I like this.

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/types/index.ts
>  export interface IApiVersioning {
Change this to `ApiVersioning`?

2020-10-09 17:46 UTC, anthony-kopczyk commented on src/types/index.ts
>  export interface IApiVersioning {
Or maybe not. This might be large enough scope to do in a different PR.

2020-10-09 17:56 UTC, anthony-kopczyk commented on src/components/GroupedAccordions.tsx
> +import classNames from 'classnames';
You might have to manually remake this change due to my moving this file to a folder the wrong way.

https://lighthouseva.slack.com/archives/CAZF880HW/p1602262623210500

2020-10-09 18:00 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +// some tests in this file are long-running because of the expense of rendering Swagger UI,
that's a good question... probably, yeah?

2020-10-09 18:04 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +} from 'swagger-ui';
yeah, it's good to have them 😌 and we kind of need them for these ESLint checks. now if only Swagger UI would actually define their own types...

2020-10-09 18:05 UTC, mjlumetta commented on src/types/index.ts
>  export interface IApiVersioning {
yes, if we start fixing every file that gets touched by fixing another file, it'll snowball pretty quick. i had a branch where i tried to go further on the Swagger stuff and it ended up being a colossal mess

2020-10-09 18:10 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(operationTagHeader.nextElementSibling).not.toBeNull();
yeah... this is a good point, i think, but i also think this is an acceptable case for using `.not.toBeNull()`. the reason i think that it's acceptable here is that the signature of `el.nextElementSibling` (and `previousElementSibling`, etc) is `HTMLElement | null`. therefore, if it's somehow undefined, i'd be okay with it blowing up on the next line because that isn't a failure we could predict. lmk what you think.

2020-10-09 18:16 UTC, mjlumetta commented on src/__mocks__/fakeCategories.tsx
>  import * as React from 'react';
umm yeah i think we can, but i'd prefer not to change it here, if that's alright. it's only _necessary_ to change the import syntax if the export is callable or otherwise not an object. we can change that going forward, but i would prefer to keep the footprint of the PR from expanding unless it needs to.

2020-10-09 18:24 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +          OauthFlow: token ? {
try FHIR on this branch vs FHIR in production

2020-10-13 13:48 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(operationTagHeader.nextElementSibling).not.toBeNull();
With the current code, we'd miss the case where it's somehow undefined. `toBeTruthy` will make sure it's both not null and it's not undefined.

If we trust the library not to return undefined I'm on board leaving this as is.

2020-10-13 13:50 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(operationTagHeader.nextElementSibling).not.toBeNull();
Oh I see. Yeah. The next line should prevent `undefined` from being an issue. Yeah. I'm on board leaving this as is.

2020-10-13 14:18 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
> +  expect(operationTagHeader.nextElementSibling).not.toBeNull();
okay, cool! in terms of the trust that this returns null, i would say i have a high degree of trust. if it were a library we had installed from NPM, no matter how broadly used, i would say that's a good reason for distrust there and for using `toBeTruthy()` - but since we're dealing with the core DOM APIs, i do feel pretty comfortable asserting null.

2020-10-13 17:28 UTC, anthony-kopczyk submitted a review, later dismissed
This looks good to me.

2020-10-13 17:28 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +              Don&apos;t have an API Key? <a href="/apply"> Get One </a>
I don't have answers to the two questions in the original requested review, so might be worth getting input from someone those before merging.

2020-10-13 17:30 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +              Don&apos;t have an API Key? <a href="/apply"> Get One </a>
I guess, to spew some thoughts

> is refactoring the CurlForm tests so they're faster a prerequisite for merging this PR?

I don't think we need to, as long as it can pass in jenkins. Maybe we can put in a jira ticket for it if we know this is something we'll want to do

> is it alright to use real OAS data downloaded to JSON files in src/__mocks__?

I want to say 'no', but my mind is telling me to follow that up with 'idea'.

2020-10-13 17:54 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +              Don&apos;t have an API Key? <a href="/apply"> Get One </a>
various responses:

- yeah, the `&apos;` was an ESLint rule check that i am fine with enforcing, but also fine with turning off if people would prefer. 
- i don't think there is any documentation to update, no. but thanks for bringing that up!

2020-10-13 19:10 UTC, anthony-kopczyk commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +              Don&apos;t have an API Key? <a href="/apply"> Get One </a>
I was trying to be clever and say 'no idea' without writing it out that way. :)

But my gut does say no, just because I don't know what all information is really in there and on precedence of the question being thought, that makes me think you may have been thinking no as well.

Like you suggested, the best way is to probably use what's there (because we want it to be similar to the real structure) but renaming things to be obviously fake. I don't know the details on the information, how sensitive it is, and such.

2020-10-13 19:50 UTC, gileswells requested changes
Some questions on thought process and a sneaky interface name to be renamed.

2020-10-13 19:50 UTC, gileswells commented on src/actions/index.ts
>  export interface ISetInitialVersioning extends Action {
I named interface

2020-10-13 19:50 UTC, gileswells commented on src/actions/index.ts
> +  metadata: any,
Shouldn't this now be `APIMetadata`?

2020-10-13 19:50 UTC, gileswells commented on src/containers/documentation/ApiDocumentation.test.tsx
> +import * as openAPIData from '../../__mocks__/openAPIData/openAPIData.test.json';
Is this able to rename to just `import openAPIData` as well or is that just for JS files?

2020-10-13 19:50 UTC, gileswells commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +                this.setState({ apiKey: e.target.value });
Why did you opt to change up the `handleInputChange()` method? Just trying to get your thinking behind this.

2020-10-13 19:55 UTC, mjlumetta commented on src/actions/index.ts
>  export interface ISetInitialVersioning extends Action {
was planning not to fix in this PR to avoid snowballing. at some point, i'll open a PR that adds `src/actions` to `npm run eslint`, at which point it will have to be fixed. is that alright with you?

2020-10-13 19:56 UTC, mjlumetta commented on src/actions/index.ts
> +  metadata: any,
yes, it should. i may have left it as not that to avoid snowballing changes - if i can make it the right type without snowballing, i'll make the change. otherwise, though, would like to leave it as is. i think that regardless of this PR i will be doing some pretty substantial refactoring around the version metadata actions and reducers in subsequent PRs.

2020-10-13 19:57 UTC, mjlumetta commented on src/containers/documentation/ApiDocumentation.test.tsx
> +import * as openAPIData from '../../__mocks__/openAPIData/openAPIData.test.json';
i think we can do that, but it doesn't matter as much for objects. want me to make the change? i was planning not to make changes for object imports in this PR.

2020-10-13 19:58 UTC, gileswells commented on src/actions/index.ts
> +  metadata: any,
Seems logical to me. Much prefer a lack of snowballs.

2020-10-13 19:59 UTC, gileswells commented on src/containers/documentation/ApiDocumentation.test.tsx
> +import * as openAPIData from '../../__mocks__/openAPIData/openAPIData.test.json';
I can take it or leave it.

2020-10-13 20:39 UTC, mjlumetta commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +                this.setState({ apiKey: e.target.value });
the rationale i was working from goes like this:

1. we want to remove the arbitrary inputs (parameters, request body) from the top-level state so that the state can be properly typed. in other words, we don't want to assign `this.state.paramName = e.target.value`, which is what `handleInputChange()` previously did. 
2. to solve (1), i created `this.state.paramValues`. i updated `handleInputChange()` to assign input params to `state.paramValues`.
3. however, we still want to have known input values - API key, bearer token, and environment - at the top-level state instead of with arbitrary keys. therefore, `handleInputChange()` doesn't work for these inputs, so i replaced the event handler here with a direct call to `setState()`. my thought was that it's brief enough so as not to add length to the code, and it actually removes a bit of indirection while still satisfying all the constraints.

does this help?

2020-10-13 21:10 UTC, gileswells approved these changes

2020-10-13 21:10 UTC, gileswells commented on src/containers/documentation/swaggerPlugins/CurlForm.tsx
> +                this.setState({ apiKey: e.target.value });
That makes sense. There's a small part of me that wonders if it would have been better to add a condition into `handleInputChange()` that looks for those 3 known fields and applies them to the state differently but that adds complexity that's not needed. LGTM

2020-10-13 21:30 UTC, merged