API-2542: Hooks migration SideNav
department-of-veterans-affairs/developer-portal pull request #480
Opened 2020-10-12 18:59 UTC by johanna-adhoc

### Story [API-2542](https://vajira.max.gov/browse/API-2542)
Migration of component SideNav from class to Hooks.

### Process
- [X ] Tests added or updated for change

### Requested feedback
All feedback is welcome

2020-10-12 21:16 UTC, TS000 submitted a review, later dismissed
Looks great 🚀

2020-10-13 19:49 UTC, mjlumetta requested changes
looks good to go except there are some changes from the React Router upgrade, including some fixes to nav link highlighting, that didn't get picked up in the diff because of the side nav getting its own directory now. it's mostly in `navHashLinkIsActive` - linking the PR below. i hope it's easy to port the changes over, but let me know if you'd like to talk it through.

https://github.com/department-of-veterans-affairs/developer-portal/pull/468

2020-10-13 19:49 UTC, mjlumetta commented on src/components/sideNav/SideNavEntry.tsx
> +  const navHashLinkIsActive = (pathMatch: match, location: Location): boolean => {
i think this function looks pretty substantially different now as of the React Router updates, but it's not getting picked up in the diff by virtue of moving the file.

2020-10-16 04:26 UTC, TS000 approved these changes
Nice work!

2020-10-16 14:52 UTC, TS000 approved these changes
Looks great! For those curious, we are creating a ticket for updating the Router to use hooks.

2020-10-16 14:52 UTC, johanna-adhoc commented
Hey @mjlumetta !

This is the PR that we fixed the other day. Can you review it again when you have a chance? Thanks

2020-10-19 13:38 UTC, mjlumetta approved these changes
looks great, thanks @johanna-adhoc! 💅 🚀

2020-10-19 15:00 UTC, merged