Api 2908/update category page to use route hooks
department-of-veterans-affairs/developer-portal pull request #488
Opened 2020-10-14 18:34 UTC by TS000

### Description
Replaced React Router 4 prop based params with React Router 5 useParams 🎸 

- [ n/a ] Tests added or updated for change
- [ n/a ] Docs updated
- [ n/a ] Accessibility concerns have been considered and addressed

### Requested feedback
All feedback appreciated.

2020-10-14 19:43 UTC, anthony-kopczyk requested changes
1. I think maybe this was based off of the branch for updating authorizationDocs. Shouldn't be a big deal because that PR is ready to be merged already. But probably doin't want to merge this until that one is merged first
2. There's a duplicate import it looks like in `CategoryPage`
3. There's a line in `AuthorizationDocs` that might be able to be removed? Doesn't need to be in this PR though.

2020-10-14 19:43 UTC, anthony-kopczyk commented on src/containers/documentation/AuthorizationDocs.tsx
>  /* eslint-disable prefer-arrow/prefer-arrow-functions */
I haven't looked at the entire file. Is this still needed?

2020-10-14 19:43 UTC, anthony-kopczyk commented on src/containers/documentation/CategoryPage.tsx
> +import { Flag } from 'flag';
There's a duplicate `import { Flag }` but from a different file on line 9. I think line 9 is correct and this one can be removed but not certain.

2020-10-14 21:50 UTC, TS000 commented on src/containers/documentation/AuthorizationDocs.tsx
>  /* eslint-disable prefer-arrow/prefer-arrow-functions */
I'm confused as to why this file was part of my PR.

2020-10-15 18:52 UTC, anthony-kopczyk approved these changes
LGTM

2020-10-15 18:53 UTC, merged