API-1686: 404s on wildcard routes
department-of-veterans-affairs/developer-portal pull request #492
Opened 2020-10-15 20:59 UTC by gileswells

### Description
https://vajira.max.gov/browse/API-1686
Provide a better design for endpoint urls that do not exist over the current solution. The new implementation (seen at /explore/benefits/docs/cookie and other paths) also pulls in the list of available APIs under that category to list. Also the list will only show APIs that are currently active or depreciated but will skip any urls that have already been deactivated.

### Process
- [ ] Tests added or updated for change
- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed

### Requested feedback
Is there a desire to attempt to search via the url fragment to see if there's an API under a different category that matches that fragment and load that as a suggested link as well? Currently this would not be possible due to (https://vajira.max.gov/browse/API-2991) but it's something that could be done in the future once API-2991 is closed out.

2020-10-15 21:01 UTC, gileswells commented on src/styles/base.scss
> -.usa-alert::before {
This was previously used on the homepage for a sandbox migration alert in #311 but is not in use anymore and messes with the expected layout from the VA Design System.

2020-10-16 16:06 UTC, anthony-kopczyk requested changes
I think really there's just the update for using the react router hook `useParams` and updating the props that are currently receiving the params as props to no longer receive them.

2020-10-16 16:06 UTC, anthony-kopczyk commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +      <PageHeader header={category!.name} />
eslint will complain about the `!`. Is this meant to be a `?`. Or if it doesn't allow undefined values you can do something like `category?.name ?? null`. If it doesn't allow null values then we'll probably need to return a default.

2020-10-16 16:06 UTC, anthony-kopczyk commented on src/Routes.tsx
> -      <Route exact={true} path="/explore/:apiCategoryKey/docs/:apiName" />
I think I might be missing something. Why is this route gone? Does it get handled under the DocumentationRoot component?

2020-10-16 17:48 UTC, alexandervalencia approved these changes
LGTM, just had a small question 🚀

2020-10-16 18:40 UTC, TS000 commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +export default EndpointNotFoundPage;
Should we make a new ticket to convert this to hooks and merge with the current fixes?

2020-10-17 01:25 UTC, gileswells commented on src/Routes.tsx
> -      <Route exact={true} path="/explore/:apiCategoryKey/docs/:apiName" />
It is handled under the DocumentRoot component. Since the route above doesn't have exact included it won't ever get to this route since the one above is in essence a "starts with" path.

2020-10-17 01:27 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +  const { params } = props.match;
I hadn't thought of that BUT at the same time including the other url param allows us to match other APIs if we want to explore the option of searching for other APIs I put in the feedback section of the PR comment.

2020-10-19 14:21 UTC, mjlumetta reviewed
what you have looks really good - have a few questions, cleanup comments, etc, but nothing too significant there. i do have questions about some stuff that isn't covered yet.

category mismatches: we [redirect back to the documentation root](https://github.com/department-of-veterans-affairs/developer-portal/blob/master/src/containers/documentation/DocumentationRoot.tsx#L135) if we can't find a category. that seems kind of jarring to me. can we cover routes like `/explore/fake` and `/explore/fake/docs/cookie` here?

for release notes, it straight-up breaks with an error. Koala is adding error boundaries for the React app as a whole, but we should handle `/release-notes/fake` gracefully too.

2020-10-19 14:21 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +            return !item.deactivationInfo || item.deactivationInfo.deactivationDate.isAfter(now());
what's the motivation for using lodash's `now()` over `Date.now()`?

2020-10-19 14:21 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +export default EndpointNotFoundPage;
since this is a new component, would love to get whatever hooks changes we need in here. as far as the export pattern goes, i like the new pattern in `src/components`, but i think maybe we should work toward greater standardization (if that's what we're shooting for) from a more holistic code organization perspective. like, in the case of components, the new pattern supports being able to import any component from a single barrel file in `src/components`. personally, i'd be interested in revisiting the whole containers/components organization, bc i don't think it's particularly meaningful right now.

2020-10-19 14:21 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +EndpointNotFoundPage.propTypes = {};
currently, we do have the `match` prop... should that go in here?

2020-10-19 14:21 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +const EndpointNotFoundPage = (props: RouteComponentProps<APINameParam>): JSX.Element => {
i'd prefer to name this component `APINotFoundPage` instead of `EndpointNotFoundPage`, to reflect the domain entity we can't find instead of the route (especially since the route isn't technically an endpoint, bc SPA?), if others are amenable to that.

2020-10-19 14:21 UTC, mjlumetta commented on src/containers/documentation/Documentation.scss
> +      margin: 0!important;
truly annoying to have to use `!important`. should there be another space here? 

also, if this class is more broad than a deprecation alert, should it be rolled up outside of documentation? would default to no change, but figured i'd ask.

2020-10-19 14:38 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +export default EndpointNotFoundPage;
I don't have a strong opinion on this item either way right now but something to consider in the future.

2020-10-19 14:38 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +const EndpointNotFoundPage = (props: RouteComponentProps<APINameParam>): JSX.Element => {
I like how much cleaner it looks now.

2020-10-19 14:40 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +      <PageHeader header={category!.name} />
`<PageHeader />` being that it's the `h1` of the page doesn't really lend itself to having a header default value since it's visible to the users. I just changed it to omit if there isn't a category name even though I can't see an instance where that would be logically possible.

2020-10-19 14:42 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +            return !item.deactivationInfo || item.deactivationInfo.deactivationDate.isAfter(now());
There wasn't any motivation. I can change it.

2020-10-19 14:45 UTC, gileswells commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +import { APIDescription } from 'src/apiDefs/schema';
Should be. vscode was set to import absolute. Finally googled to find the setting to force relative pathing by default.

2020-10-19 14:56 UTC, gileswells commented on src/containers/documentation/Documentation.scss
> +      margin: 0!important;
There's no need to leave a space before `!important` and I've seen that there are some formatters that will remove it.

2020-10-19 15:28 UTC, anthony-kopczyk commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +const EndpointNotFoundPage = (props: RouteComponentProps<APINameParam>): JSX.Element => {
@mjlumetta Possibly. I don't know much about `connected-react-router` to give a 'yes' or 'no', but from the looks of it we don't need to connect to map the location data to a component. I'm not sure about the actual redux actions, if we need pieces from the library for those.

2020-10-19 15:32 UTC, anthony-kopczyk reviewed
Looks good to me with the latest changes. I'll let Mike approve once he gets a chance to review again.

2020-10-19 16:32 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +import { APIDescription } from 'src/apiDefs/schema';
hmm, i should probably do that too...

2020-10-19 16:33 UTC, mjlumetta commented on src/containers/documentation/Documentation.scss
> +      margin: 0!important;
interesting! learn something new every day

2020-10-19 16:39 UTC, mjlumetta commented on src/containers/documentation/EndpointNotFoundPage.tsx
> +const EndpointNotFoundPage = (props: RouteComponentProps<APINameParam>): JSX.Element => {
we don't use the Redux actions at all. i'm going to make a ticket for removing `connected-react-router` - i'm pretty sure `SwaggerDocs` is the only component using it.

2020-10-20 12:10 UTC, anthony-kopczyk approved these changes

2020-10-20 18:36 UTC, mjlumetta submitted a review, later dismissed
this PR looks good to go. i do have a request for either a follow-up PR or a follow-up ticket to complete the spirit of the original ticket - your call on which one to do.

2020-10-20 18:36 UTC, mjlumetta commented on src/containers/releaseNotes/CategoryReleaseNotes.tsx
> +    return <Redirect to="/release-notes" />;
do we have UX input on this choice? the reason i'm asking is that i'm not sure that this is the behavior we want. if you go to a URL that you expect to work - let's say i want to go to "/release-notes/claims" - and it redirects you to "/release-notes", you have no idea what happened except that it won't let you go to the page you want to go to. there may be accessibility concerns for this behavior as well - not sure, would have to research. that said, i'm fine with this behavior for now if we create a follow-up ticket to research that behavior (is it okay?) and/or design a new experience.

2020-10-20 18:56 UTC, gileswells commented on src/containers/releaseNotes/CategoryReleaseNotes.tsx
> +    return <Redirect to="/release-notes" />;
I think a toast message makes sense in this instance. That should also apply to `/explore/fakeCategory` because there we also just silently redirect to `/explore` but that would be something for a future ticket. I'll write it up.

2020-10-20 18:58 UTC, mjlumetta commented on src/containers/releaseNotes/CategoryReleaseNotes.tsx
> +    return <Redirect to="/release-notes" />;
yup, exactly - would like that to apply to the docs pages as well. sounds on point to me. thanks Giles!!

2020-10-20 19:36 UTC, mjlumetta reviewed
re-approving 💯

2020-10-20 19:37 UTC, mjlumetta approved these changes
actually re-approving 🤦 💯

2020-10-20 20:50 UTC, merged