Static content for new auth page
department-of-veterans-affairs/developer-portal pull request #553
Opened 2020-11-19 14:50 UTC by ediiotero

### Description
Static content for the new Authorization page.

Text and design for reference [API-3406](https://vajira.max.gov/browse/API-3406)

### Requested feedback
Looking at text and design, making sure I didn't miss anything

2020-11-20 15:58 UTC, gileswells approved these changes
Looks good to me

2020-11-20 17:20 UTC, mjlumetta requested changes
okay, ran through this. most of these comments are copy-editing, but there are a few questions on the engineering side. namely, focus for anchor links is broken because of the zenscroll bug, which is very bad. need to figure out how to address this problem.

i would also suggest that at least one person should test with a screen reader before we merge these changes. i can do that, but this would be a lot to commit without doing those checks.

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
> +| <span>client_id</span>             | **Required** | The client_id issued by the VA Lighthouse APIs team team
```suggestion
| <span>client_id</span>             | **Required** | The client_id issued by the VA API Platform team                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
```

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
> +[Return to top](#on-this-page)
since the header has a colon, this isn't the right anchor. we may want to explicitly define some ids here for longer headers that we need to have anchors. or, alternatively, we might alter the `slugify` function for the `markdown-it-anchor` (in the Webpack configs) so that it removes colons.

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
> +| openid                   | An id_token is available in the authorization code flow (response_type = code) token response when the 'openid' scope is used          |
```suggestion
| openid                   | An id_token is available in the authorization code flow (response_type = code) token response when the 'openid' scope is used.          |
```

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
> +The JWT's header has two fields alg and kid. alg indicates the algorithm that was used the sign the JWT, and kid identifies the key that was used to sign the JWT. Signing keys and associated metadata
```suggestion
The JWT's header has two fields, alg and kid. alg indicates the algorithm that was used the sign the JWT, and kid identifies the key that was used to sign the JWT. Signing keys and associated metadata are accessible from 
```

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
> +Some APIs require test users and test data. Most of the test data provided from the Lighthouse platform comes from internal VA systems, is not real data, and are reset based upon new recordings of un
need the link to the Github repo to follow here

2020-11-20 17:20 UTC, mjlumetta commented on src/content/apiDocs/oauthTechnical.mdx
>  ### HTTPS
not a q for you, but i don't get why the HTTPS section would be nested under Test Users. should check with Brent and Darcy

2020-11-20 20:53 UTC, ediiotero commented on src/content/apiDocs/oauthTechnical.mdx
> +---
Made it a bottom border, was easier with the new wrapper

2020-11-20 20:54 UTC, ediiotero commented on src/content/apiDocs/oauthTechnical.mdx
> +[Return to top](#on-this-page)
it works when I click on the link but maybe I'm missing something. Changed to #page-header in the wrapper and that seems to be work as well.

2020-11-24 19:57 UTC, mjlumetta reviewed
@ediiotero this looks great!! i did leave a ton of comments here, but the volume is mostly due to very detailed oriented stuff + flagging the same type of issue in multiple places. really love how great the split up sections are looking - this looks so much easier to work with. here are some of the themes that account for the volume:

1. the fix on the table of contents for the page is looking great 👌 but unfortunately there are a bunch of in-page anchor links that similarly need the click handler. so we've gotta make all of those HashLinks with click handlers, which is gonna be nasty... but i can't think of any other approach at the moment
2. fair amount of copy edits + questions for Brent and Darcy related to text and design
3. and then some more typical feedback, questions about structure and naming, stuff like that

but yeah, want to say that splitting up the markdown components is looking really nice, as is the HeadingWrapper component. great job on those parts in particular, and it's looking amazing overall 🎉 🙌

2020-11-24 19:57 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthTechnicalBuildingOpenId.mdx
> +### Initiating the Authorization Code Flow
going to need `tabindex="-1"` on this one and the PKCE header if they need to be linked in the table of contents

2020-11-24 19:57 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthTechnicalBuildingOpenId.mdx
> +- If you are unable to **safely store a client secret** such as a native mobile app, you will [use PKCE](link-to-PKCE-auth-on-this-page) to complete authentication.
dead links on these lines. also HashLink + click handler, sadly

2020-11-24 19:57 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthTechnicalBuildingOpenId.mdx
> +**NOTE:** We provide a sample [Node.JS](https://nodejs.org/en/) application for demonstrating how to get up and running with our OAuth system. You can find the complete source code for it on our [Git
```suggestion
**NOTE:** We provide a sample [Node.JS](https://nodejs.org/en/) application for demonstrating how to get up and running with our OAuth system. You can find the complete source code for it on our [GitHub](https://github.com/department-of-veterans-affairs/vets-api-clients/tree/master/samples/oauth_node).
```

2020-11-30 15:38 UTC, gileswells commented on src/content/apiDocs/oauth/oauthTechnical.mdx
> +imports:
I am going to second this notion. I'm having a fair bit of issues with trying to work through being able to setup the multi code wrapper for the different APIs while sticking it in through an imported markdown file. Personally I feel that we're going to be much better off not using markdown for the bulk of this page because you cannot even pass in a prop to the import and without that there's no way that I have yet found to keep the code snippets in sync down the page. I feel like `AuthorizationDocs.tsx` is going to have to be a lot more content focused than we have in other parts of the site.

2020-11-30 16:55 UTC, ediiotero commented on src/components/headingWrapper/HeadingWrapper.tsx
> +/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- required for keyboard scrolling */
yeah, that was copied over from the code wrapper, it's removed.

2020-11-30 16:57 UTC, ediiotero commented on src/components/headingWrapper/HeadingWrapper.tsx
> +      to="#page-header"
done

2020-11-30 16:57 UTC, ediiotero commented on src/components/headingWrapper/HeadingWrapper.tsx
> +const HeadingWrapper = (props: HeadingWrapperProps): JSX.Element => (
Went with SectionHeaderWrapper

2020-12-02 22:39 UTC, mjlumetta reviewed
liking where this is heading. there's some cleanup in terms of code that i think can be done, and there are still some outstanding issues to fix, but overall really good. lmk if you'd like to pair on this at any point later in the week - i'm available.

2020-12-02 22:39 UTC, mjlumetta commented on src/components/oauthBuildingOpenIdContent/OAuthBuildingOpenIdContent.tsx
> +import * as React from 'react';
a few thoughts about the file/directory structure on this file... one, i think that `oauthBuildingOpenIdContent` is very specific and pretty long as a name; what do you think about maybe something shorter like `oauth` or `oauthDocs`? we may also need additional files in this directory, which other comments might tie into. in terms of the file name, i would prefer to see the "Connect" along with "OpenId" because it's sort of a compound word/name of the standard. we could potentially trade that for dropping the "OAuth" prefix. tl;dr i am okay breaking the rigid `./componentName/ComponentName` structure in the `src/components` barrel file.

i also think we may want to consider including MDX files like `AuthCodeFlowTableContent` and `PKCETableContent` in this directory. might be time to use MDX files outside of `src/content`. i'll address that more in a different comment.

2020-12-02 22:39 UTC, mjlumetta commented on src/components/oauthBuildingOpenIdContent/OAuthBuildingOpenIdContent.tsx
> +      <pre>
i think we are going to want to leave the code blocks as markdown because it is going to be a big pain to maintain all the highlight.js classes manually; that is a huge benefit of the MDX magic. as i mentioned in an earlier comment, might be time to start defining MDX components outside the `src/content` directory. the question in my mind is, philosophically, does the "content" of `src/content` mean "non-React content, e.g. markdown" or "content that may be edited by non-engineers"? i would lean towards seeing the latter as the more useful interpretation. and, in that case, i don't see any reason not to include MDX components in `src/components`; after all, they are still React components, just written in a templated language.

2020-12-02 22:39 UTC, mjlumetta commented on src/components/oauthBuildingOpenIdContent/OAuthBuildingOpenIdContent.tsx
> +    <h3 tabIndex={-1} id="pkce-(proof-key-for-code-exchange)-authorization">
i would def suggest omitting the part in parens from this id

2020-12-02 22:39 UTC, mjlumetta commented on src/components/sectionHeaderWrapper/SectionHeaderWrapper.scss
> +.auth-heading-wrapper {
`section-heading-wrapper`?

2020-12-02 22:39 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +  span {
is this block still relevant?

2020-12-02 22:39 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.test.tsx
> +});
one other test that could be useful would be checking the table of contents. not gonna hold up this PR for getting the tests perfect though, but take that as you will.

2020-12-02 22:39 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.test.tsx
> +    const heading = screen.getByText('Building OpenID Connect Applications');
couple of small suggestions here:

1. i think `getByRole` is also appropriate here if you're cool with that. i have a small preference for `getByRole` because it ensures that we're actually looking at a heading; if at some point have the same text within the body of the docs, then this will be a false negative for what we say we're testing.
2. if we use `it.each` here, we can reuse this test for every second-level heading in the doc (or even the two big third-level ones). might be beneficial since it's the same code.

2020-12-02 22:39 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.tsx
> +import OAuthTestUsers from '../../content/apiDocs/oauth/oauthTechnicalTestUsers.mdx';
would prefer to see the `oauthTechnical` prefix removed from the file names and the `OAuth` one from the components, if you're okay with that. to me, the context and directory structure are probably already sufficient to communicate that info, although i'll defer to others if they find that language helpful.

2020-12-02 22:39 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthInitiatingAuthCodeFlowTable.mdx
> +| `nonce`         | Optional     | Using a `nonce` with JWTs prevents some kinds of replay attacks where a malicious party can attempt to resend an `id_token` request in order to impersonate a user o
```suggestion
| `nonce`         | Optional     | <p>Using a `nonce` with JWTs prevents some kinds of replay attacks where a malicious party can attempt to resend an `id_token` request in order to impersonate a user of your application.</p><p>A nonce should be generated on a per-session basis and stored on the user's client. If the user requested an id_token (by including the openid scope in the authorization request) then the <HashLink to="#payload" onClick={onHashAnchorClick}>payload of the id_token</HashLink> will contain a nonce value that should match the nonce value included in the authorization request.</p><p>The [OpenID Connect documentation](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes) offers the following suggestion for generating nonces:</p><p>The nonce parameter value needs to include per-session state and be unguessable to attackers. One method to achieve this for Web Server Clients is to store a cryptographically random value as an HttpOnly session cookie and use a cryptographic hash of the value as the nonce parameter. In that case, the nonce in the returned ID Token is compared to the hash of the session cookie to detect ID Token replay by third parties. A related method applicable to JavaScript Clients is to store the cryptographically random value in HTML5 local storage and use a cryptographic hash of this value. </p>                                                                      |
```

2020-12-02 22:39 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthTechnicalBuildingOpenId.mdx
> +<SectionHeaderWrapper heading="Building OpenID Connect Applications" id="building-openid"/>
this file can be deleted, right?

2020-12-02 22:39 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthTechnical.mdx
> +---
this file can be renamed, right? since it's no longer the main file. also looks like the MDX imports are no longer needed

2020-12-02 22:39 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthInitiatingAuthCodeFlowTable.mdx
> +| `state`         | **Required** | Ensures authorization flow integrity. See [security](#security-considerations).
still a dead link. to ask @darduda

2020-12-02 22:39 UTC, mjlumetta commented on src/content/apiDocs/oauth/oauthInitiatingAuthCodeFlowTable.mdx
> +| `nonce`         | Optional     | Using a `nonce` with JWTs prevents some kinds of replay attacks where a malicious party can attempt to resend an `id_token` request in order to impersonate a user o
focus handling is not working for me on the payload link, even though it looks correct 🤔 no idea why. so we're gonna need to figure that out

2020-12-03 21:59 UTC, ediiotero commented on src/content/apiDocs/oauth/oauthInitiatingAuthCodeFlowTable.mdx
> +| `nonce`         | Optional     | Using a `nonce` with JWTs prevents some kinds of replay attacks where a malicious party can attempt to resend an `id_token` request in order to impersonate a user o
not sure what happened but it seems to be working for me.

2020-12-03 22:00 UTC, ediiotero commented on src/content/apiDocs/oauth/oauthInitiatingAuthCodeFlowTable.mdx
> +| `state`         | **Required** | Ensures authorization flow integrity. See [security](#security-considerations).
not sure what to do there but I can reach out

2020-12-03 22:00 UTC, ediiotero commented on src/content/apiDocs/oauth/oauthTechnical.mdx
> +---
yup,changed

2020-12-03 22:01 UTC, ediiotero commented on src/content/apiDocs/oauth/oauthTechnicalBuildingOpenId.mdx
> +<SectionHeaderWrapper heading="Building OpenID Connect Applications" id="building-openid"/>
yes, done

2020-12-03 22:01 UTC, ediiotero commented on src/components/sectionHeaderWrapper/SectionHeaderWrapper.scss
> +.auth-heading-wrapper {
yes, I will change that

2020-12-08 15:06 UTC, mjlumetta reviewed
looks good overall... haven't done a retest of all the hash links minutia, etc, but they look good from here. code organization in terms of splitting is looking really good. 

outstanding things to address: there are a couple of stray comments from previous reviews that should be addressed still. i'd also like to maybe take a look at some of these component names and do a refresh on them to make sure that we have very clear names, esp for these repetitive code blocks. if you'd like to pair at some point later today or tomorrow, i'd be available to run through some of these smaller polish-level questions/suggestions to talk them through if that's easier than async.

2020-12-08 15:06 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +    padding-left: 4rem; // larger padding-left accounts for list-style
bump

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/BuildingOpenIdContent.tsx
> +  <div>
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/BuildingOpenIdContent.tsx
> +const BuildingOpenIdContent = (): JSX.Element => (
agreed went with OIDC

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/BuildingOpenIdContent.tsx
> +        <HashLink to="#initiating-the-authorization-code-flow" onClick={onHashAnchorClick}>
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/BuildingOpenIdContent.tsx
> +      response based on the <code>response_type</code> you requested
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/BuildingOpenIdContent.tsx
> +    <h3 tabIndex={-1} id="pkce-authorization">
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/OauthInitiatingAuthCodeFlowTable.mdx
> +| `state`         | **Required** | Ensures authorization flow integrity. See [security](#security-considerations).
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/OauthInitiatingAuthCodeFlowTable.mdx
> +| `prompt`        | Optional     | Supported prompts: `login`, `consent` and `none`.<p>If `login` is specified, the user will be forced to provide credentials regardless of session state. If omitted,
done

2020-12-08 19:57 UTC, ediiotero commented on src/components/oauthDocs/OauthPKCETable.mdx
> +| `prompt`                | Optional     | Supported prompts: `login`, `consent` and `none`.<p>If `login` is specified, the user will be forced to provide credentials regardless of session state. If
done

2020-12-08 19:57 UTC, ediiotero commented on src/content/apiDocs/oauth/oauthTechnicalPageLinks.mdx
> +- <HashLink to="#getting-started" onClick={onHashAnchorClick}>Getting Started, Initiating the Authorization Code Flow</HashLink>
done

2020-12-09 15:29 UTC, mjlumetta reviewed
ok, yup, this is really close. got a few id alignments, tabindex fixes, etc that still need to happen, plus the list styles on the table of contents. but yeah, really really close

2020-12-09 15:29 UTC, mjlumetta commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +    <SectionHeaderWrapper heading="Building OpenID Connect Applications" id="building-openid" />
since these anchors are visible to the user, i think including "connect" or the "oidc" acronym would probably be beneficial here.

```suggestion
    <SectionHeaderWrapper heading="Building OpenID Connect Applications" id="building-oidc-apps" />
```

2020-12-09 15:29 UTC, mjlumetta commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +  <section aria-labelledby="Building OpenID Connect Applications">
the `aria-labelledby` should match the id of the labeling element. easy to confuse with `aria-label`, which accepts the text content directly.

2020-12-09 15:29 UTC, mjlumetta commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +          to="#pkce-(proof-key-for-code-exchange)-authorization"
```suggestion
          to="#pkce-authorization"
```

2020-12-09 15:29 UTC, mjlumetta commented on src/components/oauthDocs/PKCEAuthContent.tsx
> +  <section aria-labelledby="pkce-authorizations">
```suggestion
  <section aria-labelledby="pkce-authorization">
```

2020-12-09 15:29 UTC, mjlumetta commented on src/content/apiDocs/oauth/GettingStarted.mdx
> +After you submit the form, we send you a client ID and secret, depending on whether you can safely store a client secret. If you cannot safely store a client secret, we will send you a client ID and
need to replace the PKCE link with a HashLink to `#pkce-authorization` here still

2020-12-09 15:29 UTC, mjlumetta commented on src/content/apiDocs/oauth/GettingStarted.mdx
> +If you have any questions please feel free to reach out to the VA API Platform team at api@va.gov. If you would like to report a bug or make a feature request, please open an issue through our [Suppo
```suggestion
If you have any questions please feel free to reach out to the VA API Platform team at api@va.gov. If you would like to report a bug or make a feature request, please open an issue through our [Support page](/support).
```

2020-12-09 15:29 UTC, mjlumetta commented on src/content/apiDocs/oauth/PageLinks.mdx
> +- <HashLink to="#building-openid" onClick={onHashAnchorClick}>Building OpenID Connect Applications</HashLink>
flagging in case we do change this anchor as suggested above

2020-12-09 15:29 UTC, mjlumetta commented on src/content/apiDocs/oauth/PageLinks.mdx
> +{.auth-page-links}
not sure that it's possible to apply the class styles like this... not sure how you're supposed to in this case, but i didn't see them get rendered in the browser this way. looks mostly correct once i added the `auth-page-links` class to the `<ul/>` in the browser tools.

the other thing here is that the auth code flow and PKCE links are at a different heading level and look like they need to be nested, so those will have to be indented and probably get an additional style (ie they need the right list-style back). 

the second thing we can fix in markdown, not sure about the first. if you can figure out how to do that, that'd be awesome. if not, we might want to consider doing this component in React as well. or we could also try to recreate what you had before and just make sure that that's the cleanest way of selecting this list to style.

2020-12-09 15:29 UTC, mjlumetta commented on src/content/apiDocs/oauth/IdToken.mdx
> +### Payload
need to have a `tabindex="-1"` here because there's a link to it in one of the query params tables that's currently not working

2020-12-09 15:29 UTC, mjlumetta commented
also, i do want to screen reader test before we merge this, but hopefully after everything else that'll be pretty straightforward.

2020-12-09 16:53 UTC, ediiotero commented on src/content/apiDocs/oauth/IdToken.mdx
> +### Payload
done

2020-12-09 16:54 UTC, ediiotero commented on src/content/apiDocs/oauth/PageLinks.mdx
> +- <HashLink to="#building-openid" onClick={onHashAnchorClick}>Building OpenID Connect Applications</HashLink>
done

2020-12-09 16:54 UTC, ediiotero commented on src/content/apiDocs/oauth/GettingStarted.mdx
> +If you have any questions please feel free to reach out to the VA API Platform team at api@va.gov. If you would like to report a bug or make a feature request, please open an issue through our [Suppo
done

2020-12-09 16:54 UTC, ediiotero commented on src/content/apiDocs/oauth/GettingStarted.mdx
> +After you submit the form, we send you a client ID and secret, depending on whether you can safely store a client secret. If you cannot safely store a client secret, we will send you a client ID and
done

2020-12-09 16:54 UTC, ediiotero commented on src/components/oauthDocs/PKCEAuthContent.tsx
> +  <section aria-labelledby="pkce-authorizations">
done

2020-12-09 16:54 UTC, ediiotero commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +          to="#pkce-(proof-key-for-code-exchange)-authorization"
done

2020-12-09 16:54 UTC, ediiotero commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +  <section aria-labelledby="Building OpenID Connect Applications">
changed, thanks

2020-12-09 16:55 UTC, ediiotero commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +    <SectionHeaderWrapper heading="Building OpenID Connect Applications" id="building-openid" />
done

2020-12-09 18:10 UTC, ediiotero commented on src/content/apiDocs/oauth/PageLinks.mdx
> +{.auth-page-links}
Looking through the docs, that is how they suggested adding a class to a `<ul>`. It's working on my local, but I'll take another look

2020-12-09 22:09 UTC, mjlumetta reviewed
ok, left 2 copy-edits, and we can talk about the list issue in the morning.

i did do my screen reader testing, and everything looks good to me except needing to address the nested list issue. i did think of two questions that i want to flag for future consideration but are more enhancement-level and therefore should not block these PRs.

1. i wonder if adding an `aria-label` to our code blocks would be helpful. whereas sighted users can sort of scan the whole code block and get the gist of the structure, i don't think screen reader users necessarily have an equivalent (although maybe that's not necessarily the case always, and i would guess screen reader users might have more skill reading in that way than i do, obviously). anyway, could be beneficial to give them the gist up front, especially since some of these blocks are pretty pseudo-codey.
2. wondering whether the disparity between the React components in the OIDC section and the pure Markdown components is an issue. the reason being is that the `section`s get read out as such, as regions, but the Markdown parts have no such grouping. might be weird to go back and forth in that way.

neither of these last two suggestions should be blocking. i'll copy them to the ticket for posterity, but they're outside of the scope of this PR (esp the code block bit, since Giles will more fully implement that).

2020-12-09 22:09 UTC, mjlumetta commented on src/content/apiDocs/oauth/IdToken.mdx
> +https://sandbox-api.va.gov/oauth2/.well-known/openid-configuration.
```suggestion
The JWT's header has two fields, `alg` and `kid`. `alg` indicates the algorithm that was used to sign the JWT, and `kid` identifies the key that was used to sign the JWT. Signing keys and associated metadata are accessible from  https://sandbox-api.va.gov/oauth2/.well-known/openid-configuration.
```

unfortunately, MDX isn't smart enough to handle newlines in Markdown as we hope might, i don't think. anyway, think we want to remove this newline here.

2020-12-09 22:09 UTC, mjlumetta commented on src/content/apiDocs/oauth/GettingStarted.mdx
> +If you have any questions please feel free to reach out to the VA API Platform team at api@va.gov. If you would like to report a bug or make a feature request, please open an issue through our [Suppo
```suggestion
If you have any questions please feel free to reach out to the VA API Platform team at [api@va.gov](mailto:api.va.gov). If you would like to report a bug or make a feature request, please open an issue through our [Support page](/support).
```

this appears to be a link, if I'm looking at the right source in the Google doc

2020-12-10 15:15 UTC, mjlumetta approved these changes
great job Eddie!! let's get it merged 🙌 🚀 ✨

2020-12-10 16:07 UTC, merged