Api 3786use semantic tags on main page
department-of-veterans-affairs/developer-portal pull request #562
Opened 2020-12-01 15:17 UTC by anthony-kopczyk

### Description
This switches some div tags that should be p tags.

Jira Ticket: https://vajira.max.gov/browse/API-3786

### Process
- [ ] Tests added or updated for change
- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed

### Requested feedback

2020-12-02 21:51 UTC, mjlumetta submitted a review, later dismissed
lgtm!!

i do have one question about the purpose of the ticket: "As a user navigating with a screen reader, I want paragraphs to use the html semantic p tag, so that I know the purpose of the content." is this supposed to make a functional change that the user will notice? i tested with VoiceOver on Mac and didn't see any difference; it regards both as text elements. it's possible that's not the case for JAWS or NVDA and what have you, of course. wondering if someone had been testing this and noticed it could be improved and, if so, what the environment was. with that said, this is more semantically correct regardless, so i think it's unequivocal that it is an improvement.

2020-12-02 21:51 UTC, mjlumetta commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
any particular reason this is a paragraph? my knowledge of where it is semantically correct to use `<p>` versus you don't necessarily have to when it gets down to these smaller snippets is not very clear at all. if you have any insight into the standards there, would love to learn more.

2020-12-03 13:56 UTC, anthony-kopczyk commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
I worked with JAWS a few years ago. The guy I learned it from used it primarily by navigating jumping through headings, paragraph tags, list tags, etc - whereas voiceover seems to want you to go through each element using the arrow keys. Since the text is in a div, I think JAWS users would miss it at first and need to go back. I think the most similar way to how you can use JAWS in the voiceover rotor. That said, JAWS also includes a next element like VoiceOver, so maybe not?

In regard to the small snippets, I didn't think about that for the title props. I think for users navigating by html landmarks/p/heading tags, having it as a p tag will be better than having it as a div. I'm interested in thoughts from other devs as well because I'm really not certain.

Hmm.. I just found some apple shortcuts that allow you to navigate via 'next heading' and such, which looks really similar to JAWS. Going to play around with that some. Looks like navigating to plain text doesn't care if it's a div or anything.

**Convenience Links**
- Voiceover Rotor: https://support.apple.com/en-us/HT204783
- JAWS Shortcuts/Commands: https://www.freedomscientific.com/SurfsUp/Quick_Keys.htm
- Apple Voiceover Shortcuts: https://www.apple.com/voiceover/info/guide/_1131.html

2020-12-03 14:39 UTC, anthony-kopczyk commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
Also, thank you for your comment so much! That got me looking for shortcuts for voiceover. Voiceover felt really awkward to use but with those other shortcuts, it's so much better for me!

2020-12-03 15:15 UTC, mjlumetta commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
thanks for all this detail Anthony!! this is so helpful. going to chalk up my initial impulse to being a novice with VoiceOver, or any screen reader 😂 this is a good reminder to use more of that functionality, ty

2020-12-03 15:30 UTC, TS000 submitted a review, later dismissed
Looks great 🥇

2020-12-03 16:13 UTC, johanna-adhoc requested changes
I noticed the prop name being "title" if the string displayed here is a title wouldn't the div tag be replaced by a heading? (not sure about the heading level though)

2020-12-03 18:02 UTC, mjlumetta commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
what do y'all think about using a different noun for this text besides "title"? i think that making it a true heading is awkward for the reasons Anthony raised, that it doesn't really that way in the document flow. maybe "lead"?

2020-12-03 19:15 UTC, johanna-adhoc commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
I don't think the issue is the name of the prop, the text is actually performing as a title for the description written below. 
The best approach I see is wrapping the title in an h1, BUT also replacing the outer div tag for an article tag. By doing this the h1 heading of the article is ignore for the main content hierarchy content so it will not introduce any issues. 
_the <h1>s inside the <article> elements “become” logical <h2>s, because <article>, like <section>, is a sectioning element._

This article has info about it!
https://www.smashingmagazine.com/2020/01/html5-article-section/

2020-12-03 21:31 UTC, mjlumetta commented on src/components/banner/Banner.tsx
> +      <p className="vads-u-font-weight--bold vads-u-margin--0">
oh wow that's really cool!! yeah, if that tests well, then that sounds great to me. one question that i still have is does wrapping something in an article at the top level with an h1 - so still a logical h1 to assistive technologies - violate the "one h1 per page" guideline? in any case, thanks for sharing that, that's super informative 🙏

2020-12-07 16:20 UTC, johanna-adhoc approved these changes
Approving this PR. Issues with the GuidandeBox component will be addressed with another story.

2020-12-10 15:18 UTC, johanna-adhoc approved these changes
LGTM

2020-12-14 16:02 UTC, merged