API-3757: Test for Hero Component
department-of-veterans-affairs/developer-portal pull request #573
Opened 2020-12-08 21:52 UTC by TS000

There isn't any logic in the hero component so other than testing that the component mounts I tested that the src.

- [ ☑️ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

If anyone has any other ideas for a test on this component I'm all ears👂👂.

2020-12-09 13:35 UTC, anthony-kopczyk submitted a review, later dismissed
Can we add a test to check for the 'Request an API key' link? Maybe one for the heading text too, but I'm not sure on that one.

2020-12-09 13:35 UTC, anthony-kopczyk commented on src/components/hero/Hero.test.tsx
> +    const { queryByRole } = render(<Router><Hero  /></Router>);
It looks like there's an extra space on the Hero tag

2020-12-09 13:37 UTC, anthony-kopczyk commented on src/components/hero/Hero.test.tsx
> +    const { queryByRole } = render(<Router><Hero  /></Router>);
Oh. When I was looking at react testing library things, I saw that you can use 'screen' instead of retrieving { getByRole } from render. I think screen is essentially an alias for the returned object. I'm not hardset on doing it one way or the other, but I think the testing-library way is to use screen. Feels odd using a global like that though.

2020-12-09 15:33 UTC, TS000 commented on src/components/hero/Hero.test.tsx
> +    const { queryByRole } = render(<Router><Hero  /></Router>);
Thanks! Added the more precise "screen" query provided by Testing-Library and fixed the extra space.

2020-12-09 18:19 UTC, TS000 commented
> Can we add a test to check for the 'Request an API key' link? Maybe one for the heading text too, but I'm not sure on that one.

I've added a test for the api url. I didnt think the Heading text needed a test since it's something that could be changed regularly.

2020-12-09 18:49 UTC, mjlumetta commented on src/components/hero/Hero.tsx
> +            role="link"
out of curiosity, what was the motivation for adding the role explicitly as opposed to using the implicit role?

2020-12-09 18:57 UTC, johanna-adhoc requested changes
> > Can we add a test to check for the 'Request an API key' link? Maybe one for the heading text too, but I'm not sure on that one.
> 
> I've added a test for the api url. I didnt think the Heading text needed a test since it's something that could be changed regularly.

And that is exactly why the text content needs regression testing, so any change made by a developer should be conscious enough to also involve update of the unit test of the component.

2020-12-09 19:35 UTC, TS000 commented on src/components/hero/Hero.tsx
> +            role="link"
I'm new to Testing-Library and saw that you could target by role. The role wasnt set so I added one after looking up a11y best practice for links.

> out of curiosity, what was the motivation for adding the role explicitly as opposed to using the implicit role?

Are you implying that the role will be implicitly set and I cant still search by role "link" and it will still work?

2020-12-09 19:36 UTC, TS000 commented on src/components/hero/Hero.test.tsx
> +});
Is my check for '/apply' done incorrectly?

2020-12-09 21:03 UTC, mjlumetta commented on src/components/hero/Hero.tsx
> +            role="link"
yeah, absolutely; this is probably a good thing to call out then, for Testing Library and ARIA roles in general. lots of elements have implicit roles based on the tag + sometimes other characteristics. for example, `a` tags have the link role implicitly _if_ they have an href, and otherwise no implicit role, and Testing Library will respect those implicit roles. they have a link from the `*ByRole` docs in the text of that body to [this table of roles in the ARIA spec](https://www.w3.org/TR/html-aria/#docconformance). it's been a super helpful reference for me while writing unit tests and learning about how these roles work in general.

2020-12-09 22:05 UTC, TS000 commented on src/components/hero/Hero.tsx
> +            role="link"
You're a legend, thank you!

2020-12-10 15:21 UTC, johanna-adhoc approved these changes

2020-12-11 16:04 UTC, anthony-kopczyk approved these changes
Looks good to me

2020-12-16 20:50 UTC, merged