Update styling of code blocks
department-of-veterans-affairs/developer-portal pull request #593
Opened 2020-12-24 20:48 UTC by ediiotero

### Update styling of code blocks

Add styling to API Selector in the new Auth docs. Added React Syntax Highlighter for code blocks. Removed React Markdown.

2020-12-28 14:39 UTC, gileswells requested changes
Just some structural changes to what the CSS is applied to.

2020-12-28 14:39 UTC, gileswells commented on src/containers/documentation/AuthorizationDocs.scss
> +        background-color:$color-gray;
I would prefer to see these styles on the `.api-selector` selector rather than on the select element. Reason being, while we're not implementing the copy button currently it feels more correct to me that the background and rounded corners and whatnot be on the container rather than an element within the container.

2021-01-04 19:39 UTC, gileswells requested changes
The 2 back to back code wrappers now have no gap between them.

2021-01-04 19:39 UTC, gileswells commented on src/components/codeWrapper/CodeWrapper.scss
> +  margin: 0;
This change here is what I believe is causing the 2 back to back code blocks to now have no gap between them at all. While the visual regressions pass with the new images I believe that the more correct solution is to update this change to account for when 2 code wrappers are siblings on the page. Perhaps something similar to this?

```css
.code-wrapper + .code-wrapper {
  margin-top: 16px;
}
```

2021-01-05 15:02 UTC, ediiotero commented on src/components/codeWrapper/CodeWrapper.scss
> +  margin: 0;
Thanks, I guess I missed that

2021-01-05 15:41 UTC, mjlumetta commented
something about the API selector looks broken? not sure why that is here.

2021-01-05 16:43 UTC, mjlumetta reviewed
overall this looks really great! couple of CSS tweaks suggested, etc. the one bigger question I'd like to address in this ticket is the syntax highlighter approach with the new module vs the old markdown approach. would like to have a discussion on the benefits of each; either could work, but I'd like for us to get a little clearer together on why we're making the decision we're making.

2021-01-05 16:43 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> +        <SyntaxHighlighter language="plaintext" style={syntaxColor}>
want to do a bit of a roundup with Okapi eng + any other frontend folks on the conversion from markdown to Javascript strings to discuss what direction we think is most beneficial here. I still have a preference for the markdown setup because it makes the code blocks more legible/editable/etc for me at least; don't know if others feel similarly or not. there are some wonky spacing issues with a couple of the code blocks (newlines, indentation) that I'm not sure whether it's due to being lost in those strings or due to something with `react-syntax-highlighter` that we should fix regardless of how we choose to approach this question. anyway, would like hear people's thoughts and get any other relevant info. like, for example, does React Syntax Highlighter give us better control of highlighting in some way? I'm good with whatever the team thinks is best, but I'm not entirely clear on what the rationale for React Syntax Highlighter over the markdown approach is at the moment.

2021-01-05 16:43 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> -    // Needs both due to covering of both code blocks and inline formatted code/parameter names
why was this block removed? I think this comment still applies. see here:

<img width="780" alt="NoBackgroundOnCodeBlockScroll" src="https://user-images.githubusercontent.com/3241493/103672467-58262080-4f4a-11eb-8eac-3018218c870b.png">

2021-01-05 18:48 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> -    // Needs both due to covering of both code blocks and inline formatted code/parameter names
sorry I missed that, thanks for catching it

2021-01-05 20:19 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +    border-top-right-radius: 0;
thanks fixed that

2021-01-05 20:19 UTC, ediiotero commented on src/components/apiSelector/APISelector.scss
> +        color: $color-white;
taking the color out of this file and using the AuthorizationDocs file to handle color

2021-01-05 20:19 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +        color: $color-black;
changed it to $color-base. 
Is that the color you're talking about?

2021-01-05 20:19 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +          color: $color-black;
was able to remove the background color but need to keep the font color for the options as we made the select fonts white

2021-01-05 20:20 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> +        <SyntaxHighlighter language="plaintext" style={syntaxColor}>
open to talking about it

2021-01-07 15:31 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +        color: $color-black;
yup, that looks like it!

2021-01-07 15:31 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +          color: $color-black;
cool cool, sounds good!

2021-01-07 15:52 UTC, mjlumetta reviewed
looking really good! all of these comments are pretty detail-oriented. think that the code blocks implementation is the main thing to look at in order to get this committed.

2021-01-07 15:52 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +        border: 1px solid $color-base;
can we make the border color `$color-gray`? trying to match it up with the default styles as seen in the version selector.

2021-01-07 15:52 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +    background-color: $color-gray;
wondering if this style and the corresponding override on line 75 might be better suited in the `select` block next to the text color... don't think it makes much of a difference functionally, but I think of those two things going together usually. if other people think about them similarly, might be worth grouping together for ease of reading.

2021-01-07 15:52 UTC, mjlumetta commented on src/components/codeWrapper/CodeWrapper.scss
> +  margin: 0;
if this margin is 0, can we cut this line with no change in behavior?

2021-01-07 15:52 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> +  const authUrl = `https://sandbox-api.va.gov${apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}/authorization?\n  client_id=0oa1c01m77heEXUZt2p7\n  &redirect_uri=<yourRedirectURL>\n  &response_type=code
not necessarily related to code blocks styles, but can we make the dummy val for the base path something like "/oauth2/{api}/v1"? I think we probably want to avoid giving the consumer the impression that the /oauth2 path on its own is a meaningful value.

2021-01-07 15:52 UTC, mjlumetta commented on src/components/codeWrapper/CodeWrapper.scss
> +.code-wrapper + .code-wrapper {
I don't think that this block is doing anything right now. the only back to back blocks we have right now have an API selector, so the selector doesn't apply. also think that this is something that can be handled by the auth docs stylesheet; the code wrapper should probably be agnostic to how it's positioned with respect to other code wrappers, or other elements in general, as long as it provides reasonable defaults.

2021-01-07 18:43 UTC, ediiotero commented on src/components/codeWrapper/CodeWrapper.scss
> +.code-wrapper + .code-wrapper {
this was added for the legacy auth docs to fix a visual regression failure. I moved it to the AuthorizationDocsLegacy.scss file

2021-01-07 21:38 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> +  const authUrl = `https://sandbox-api.va.gov${apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}/authorization?\n  client_id=0oa1c01m77heEXUZt2p7\n  &redirect_uri=<yourRedirectURL>\n  &response_type=code
will be addressed in another ticket, per our convo in the working session

2021-01-07 21:39 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +    background-color: $color-gray;
Thas as done because of @gileswells comment [above](https://github.com/department-of-veterans-affairs/developer-portal/pull/593#discussion_r549370662) I thought it made sense but can change if needed.

2021-01-07 21:39 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +        border: 1px solid $color-base;
done

2021-01-07 21:42 UTC, ediiotero commented on src/components/codeWrapper/CodeWrapper.scss
> +  margin: 0;
done

2021-01-08 17:21 UTC, mjlumetta commented on src/components/codeWrapper/CodeWrapper.scss
> +.code-wrapper + .code-wrapper {
ahhh I missed that, thanks for pointing that out. moving to AuthorizationDocsLegacy.scss sounds good!

2021-01-08 17:33 UTC, mjlumetta approved these changes
looks good to me! left one suggestion that you can take or leave; will re-approve if you make any more changes. nice work on this one 🚀 ✨

2021-01-08 17:33 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> +        <SyntaxHighlighter language="plaintext" style={syntaxColor}>
going to be resolved in a follow-up ticket. Eddie, would you mind creating a follow-up ticket in this epic before closing out API-3414?

2021-01-08 17:33 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +    background-color: $color-gray;
ahh I see. it's up to you where you want it to go, in that case. generally speaking, I feel like it can be beneficial to look at text and background color alongside each other, but that's more of a personal preference.

2021-01-08 17:33 UTC, mjlumetta commented on src/components/oauthDocs/ScopesContent.tsx
> +    <section className="scopes-content">
maybe add an `aria-labelledby="scopes"` on this section? although that's not strictly necessary because this is sort of inconsistent on this page due to the different implementations of MDX vs pure React. should probably straighten that out at some point to make it consistent for screen readers - not sure which way is preferable (ARIA role of "region" vs no role).

2021-01-08 21:53 UTC, ediiotero commented on src/components/oauthDocs/ScopesContent.tsx
> +    <section className="scopes-content">
Same here maybe we can talk about it during another working session

2021-01-08 21:54 UTC, merged