updated release notes for API-3044 feature
department-of-veterans-affairs/developer-portal pull request #601
Opened 2021-01-15 14:14 UTC by gpbowman-git

### Description
Updating Benefits Intake release notes tied to API-3044. This feature added PDF upload information to a DB column and included a JSON response in the status check related to the documents contained in the uploaded payload

https://vajira.max.gov/browse/API-3044

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-01-21 01:15 UTC, rtravitz submitted a review, later dismissed
Thanks for adding a release note. This works from a functional standpoint.

2021-01-21 02:28 UTC, ryanlink requested changes

2021-01-21 02:28 UTC, ryanlink commented on src/content/apiDocs/benefits/benefitsIntakeReleaseNotes.mdx
> +(v1) Added uploaded PDF metadata to the DB and in the HTTP response:
Sorry for the late review - may I suggest adding "(document count and page count)" after "metadata" so it's clear what metadata was added. Thx!

2021-01-22 17:22 UTC, gpbowman-git commented on src/content/apiDocs/benefits/benefitsIntakeReleaseNotes.mdx
> +(v1) Added uploaded PDF metadata to the DB and in the HTTP response:
I have added additional information in the description. Let me know if this works for you.

2021-01-22 17:42 UTC, ryanlink approved these changes
LGTM!

2021-01-22 17:45 UTC, mjlumetta approved these changes
lgtm, feel free to merge!

2021-01-25 14:44 UTC, merged