Api 4416/mdx props
department-of-veterans-affairs/developer-portal pull request #611
Opened 2021-01-25 16:58 UTC by ediiotero

### Using Props with MDX
Story: [API-4416](https://vajira.max.gov/browse/API-4416)

Using props with MDX files to be used with the new API selector in the new Auth docs page and remove the mdx files we are not using.

- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed
- [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

Had trouble getting syntax highlighting to work without the Syntax Highlighter component. The goal is to get it working as in the old auth docs and use props. Lost highlighting and some styling without Syntax Highlighter component in the MDX.

2021-01-26 14:53 UTC, gileswells requested changes
Looks solid overall. I wonder if now's the right time to consider bringing the code samples fully into the mdx files and relying less on the `propObj` to bring in the whole code sample but instead the base url and scopes (if markdown doesn't throw a fit of course).

2021-01-26 14:53 UTC, gileswells commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +  '{APISelector, CodeWrapper }': ../index
nitpicky space needed here
```suggestion
  '{ APISelector, CodeWrapper }': ../index
```

2021-01-26 14:53 UTC, gileswells commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +- Be sure to replace `< yourRedirectURL >` with the redirect URL that you provided during registration.
In other instances we've used `&lt;` and `&gt;` instead of adding spaces like this to prevent the markdown loader from trying to render a component. Does that not work here?

2021-01-26 14:53 UTC, gileswells commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +The authorization server will respond with an <HashLink to='#id-token'>access token</HashLink>. If you requested the `offline_access` scope, you will also receive a`refresh_token`. The response will
Do these `<HashLink />`s still hold the query string parameter for the selected API? I had an issue where I'd need to include the location object in order for these to work properly.

2021-01-26 14:53 UTC, gileswells commented on src/types/md.d.ts
>    }
I'd probably add a comment about why you're disabling the any check here just for clarity sake.

2021-01-26 21:53 UTC, ediiotero commented on src/types/md.d.ts
>    }
changed this to unknow, but yeah you're right. I'll add a comment

2021-01-26 21:53 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +The authorization server will respond with an <HashLink to='#id-token'>access token</HashLink>. If you requested the `offline_access` scope, you will also receive a`refresh_token`. The response will
seems to be working

2021-01-26 21:54 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +- Be sure to replace `< yourRedirectURL >` with the redirect URL that you provided during registration.
I removed the spaces and it seems to work fine. Maybe because of the backticks?

2021-01-29 18:56 UTC, mjlumetta reviewed
bunch of miscellaneous comments and questions, plus a few proofreading things not specific to this PR. looking good in general.

2021-01-29 18:56 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +POST {{props.propObj.apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}}/revoke HTTP/1.1
not part of this PR, but think this is actually the token endpoint

```suggestion
POST {{props.propObj.apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}}/token HTTP/1.1
```

2021-01-29 18:56 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +POST {{props.propObj.apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}}/token HTTP/1.1
```suggestion
POST {{props.propObj.apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}}/manage HTTP/1.1
```

2021-01-29 18:56 UTC, mjlumetta commented on src/components/oauthDocs/PKCEAuthContent.mdx
> +  '{ Prism }' : 'react-syntax-highlighter/dist/cjs/prism'
```suggestion
```

left over stuff

2021-01-29 18:56 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +    border-top-left-radius: 0;
what's the cause of the changes in this file, here and above?

2021-01-29 18:56 UTC, mjlumetta commented on src/types/md.d.ts
> +   * adding 'propObj' so the mdx files are open to any props that are passed
would you mind folding this sentence into the previous comment and updating the previous comment to reflect the current changes? they're addressing the same thing, and the previous comment is no longer accurate as of this change.

2021-01-29 18:56 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> -      <h3 id="authorization-code-flow" tabIndex={-1}>
if all of the markup for this component is in the MDX file now, do we still need this TSX file?

2021-01-29 18:56 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +The authorization server will respond with an <HashLink to='#id-token'>access token</HashLink>. If you requested the `offline_access` scope, you will also receive a`refresh_token`. The response will
yeah, this isn't working for me, although the issue isn't removing the query string per se. here's what i'm seeing:

1. link has an href to `/explore/authorization#id-token`.
2. clicking the link sets the URL to that path + hash.
3. the top-level `AuthorizationDocs` component re-renders, and the hook sets the query param to the currently selected API from the Redux store. in the process, it removes the hash, so the URL is `<host>/explore/authorization?api=claims` (or whichever API). so I think there is an issue to be addressed here, which would require using the `location` object.

2021-02-01 14:52 UTC, ediiotero commented on .babelrc
> +    "@babel/plugin-proposal-nullish-coalescing-operator"
They were needed for the optional chaining in props for the mdx files.

2021-02-01 14:52 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +  '{ Prism }' : 'react-syntax-highlighter/dist/cjs/prism'
thanks missed those

2021-02-01 14:53 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +  'AuthCodeFlowQueryParamsTable': ./AuthCodeFlowQueryParamsTable.mdx
yeah you're right I'll fix that

2021-02-01 14:53 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +https://sandbox-api.va.gov{{props.propObj.apiDef?.oAuthInfo?.baseAuthPath ?? '/oauth2'}}/authorization?
ok I'll make that change

2021-02-01 14:54 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +  Host: <yourRedirectHost>
I guess I missed this comment, the doc has been updated since I worked on the static content. I'll remove it

2021-02-01 14:54 UTC, ediiotero commented on src/components/oauthDocs/PKCEAuthContent.mdx
> +  '{ Prism }' : 'react-syntax-highlighter/dist/cjs/prism'
done

2021-02-01 14:54 UTC, ediiotero commented on src/containers/documentation/AuthorizationDocs.scss
> +    border-top-left-radius: 0;
removing the SyntaxHighlighter component removed the border-radius syles and had to adjust

2021-02-01 14:54 UTC, ediiotero commented on src/types/md.d.ts
> +   * adding 'propObj' so the mdx files are open to any props that are passed
done

2021-02-01 14:55 UTC, ediiotero commented on src/components/oauthDocs/AuthCodeFlowContent.tsx
> -      <h3 id="authorization-code-flow" tabIndex={-1}>
I'll work on merging this file and the PKCE content file into the Building OIDC Content file

2021-02-02 15:47 UTC, gileswells requested changes
Check the implementation for mdx props on #615 and consider changing over to that style with wildcard prop names.

2021-02-02 15:47 UTC, gileswells commented on src/types/md.d.ts
>    }
There's a different implementation method for this change in another PR and despite suggesting using a `propObj` param initially I think that I prefer the other method now having seen it.

https://github.com/department-of-veterans-affairs/developer-portal/pull/615/files?diff=unified&w=1#diff-38e9706b08e494d5b2d4e43026117b5e5091e090ddd07716508ba634334bdf95R10

2021-02-02 17:13 UTC, mjlumetta commented on .babelrc
> +    "@babel/plugin-proposal-nullish-coalescing-operator"
yeah, makes sense. feels strange to have to have it from Babel and TS, but that's fine

2021-02-03 17:38 UTC, mjlumetta approved these changes
I've got a couple general proofreading things for the auth docs, but your changes look good 💯

2021-02-03 21:40 UTC, mjlumetta commented
oh wait - should `react-syntax-highlighter` be uninstalled?

2021-02-04 15:22 UTC, gileswells approved these changes
LGTM Nice work on making this 1000% easier to manage going forward.

2021-02-04 16:57 UTC, mjlumetta commented
@gileswells ready for review whenever you're ready

2021-02-04 19:00 UTC, gileswells approved these changes
LGTM

2021-02-04 19:00 UTC, gileswells commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +client_id={client_id}&email={test account email}
My only thing that I don't particularly like is the use of `test account email` here. I'd prefer that it stick with the snake case we have of pseudo fields like `client_id`. Also if you're calling it `test_account_email` then I would argue that `test_account_client_id` would be a more harmonious variable name for `client_id` but my vote would just be to use `email_address` because even though these are sandbox examples I would think that `client_id` pairs with `email_address` better.

Not worth failing the review on this alone but just something I noted.

2021-02-04 19:05 UTC, mjlumetta commented on src/components/oauthDocs/AuthCodeFlowContent.mdx
> +client_id={client_id}&email={test account email}
it's a good point on the snake case. I don't think `test_account_client_id` makes much sense in that way because the client id isn't actually associated with a test user, although the email is.

2021-02-04 20:09 UTC, merged