Remove references to the vets-api-clients repo as a resource for getting platform support
department-of-veterans-affairs/developer-portal pull request #625
Opened 2021-02-08 17:29 UTC by mjlumetta

### Description

removes references to the `vets-api-clients` repo as a path for getting support per [API-3990](https://vajira.max.gov/browse/API-3990). documentation referring to sample apps and test accounts is unchanged.

### Process

- [ ] Tests added or updated for change
  - no changes. 
- [n/a] Docs updated
  - [n/a] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [n/a] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [X] Accessibility concerns have been considered and addressed
  
  - [X] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-02-08 18:12 UTC, brentschneider commented
@mjlumetta I've reviewed the changes removing the GitHub references, from my perspective they are spot on 👍

2021-02-09 15:42 UTC, ryanlink submitted a review, later dismissed
LGTM! 🚀

2021-02-09 15:50 UTC, gileswells requested changes
Overall very good but there's a couple touch ups I'd suggest.

2021-02-09 15:50 UTC, gileswells commented on src/containers/support/SupportContactUsForm.tsx
> -      <fieldset>
Semantically I would believe that the fieldset and legend tags should still be present here.

2021-02-09 15:50 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +        <Link to="/support/contact-us">the Contact Us form</Link>. We strive to reply with
For SEO purposes this Link tag should only include Contact Us to better match with the h1 of the target page.

2021-02-09 15:50 UTC, gileswells commented on src/containers/support/SupportOverview.tsx
> +    "Welcome to support for the VA Lighthouse API program. You can visit our FAQ page for answers to common questions. For general feedback use our 'Contact Us' form. Our customer support team is hap
This removes the wording for support requests entirely which we're now trying to funnel through the contact us form.

```suggestion
    "Welcome to support for the VA Lighthouse API program. You can visit our FAQ page for answers to common questions. For support and/or general feedback use our 'Contact Us' form. Our customer support team is happy to help and will respond within one business day.",
```

2021-02-09 15:52 UTC, ryanlink commented on src/containers/support/SupportOverview.tsx
> +    "Welcome to support for the VA Lighthouse API program. You can visit our FAQ page for answers to common questions. For general feedback use our 'Contact Us' form. Our customer support team is hap
good catch on this content!  I agree.

2021-02-12 15:13 UTC, mjlumetta commented on src/containers/support/SupportContactUsForm.tsx
> -      <fieldset>
Giles and I discussed this one; should be okay not to have fieldset, since it was wrapping the whole form. also, the changes in #622 will take precedence.

2021-02-15 19:29 UTC, gileswells reviewed
The link tag comment below is certainly our of scope but low hanging fruit if you're able to take a quick crack at it. The grammar question is more asking for direction. If there's a desire to keep it as is then I'm ok with it. Just feels off based on what I'm used to.

I'll re-review again once the visual test images are added.

2021-02-15 19:29 UTC, gileswells commented on src/containers/releaseNotes/ReleaseNotesOverview.tsx
>            <a href="/support/contact-us">contact us</a> with any questions or to request support.
Out of scope for this PR but if you've got to update the visuals anyways and want to update this to a `<Link />` tag so there isn't a hard reload of the app I would be in favor of it.

2021-02-15 19:29 UTC, gileswells commented on src/containers/support/SupportFAQ.tsx
> +    "We've compiled a list of FAQs for the VA API program; our goal is to get your question answered as soon as possible. If you need further help\u2014or have comments or feedback\u2014please contac
I don't know if there's a reason for using dashes here instead of commas because it's a piece of header text but I've always seen this style of aside in a sentence using commas to break it out.

```suggestion
    "We've compiled a list of FAQs for the VA API program; our goal is to get your question answered as soon as possible. If you need further help, or have comments or feedback, please contact us by using our short 'Contact Us' form. Our customer support team will be happy to help.",
```

2021-02-22 19:46 UTC, mjlumetta commented
closing in favor of #639.

2021-02-22 19:46 UTC, closed without merging