Api 5360 add dropdown and revise color ratio
department-of-veterans-affairs/developer-portal pull request #647
Opened 2021-02-25 15:33 UTC by charleystran

### Description
This PR adds the API dropdown selector to the top of the auth docs page. Additionally the PR changes the contrast ratio of the dropdown selector text and removed the rounded radius for the new API selector at the top of the page.

This PR related to https://vajira.max.gov/browse/API-5360

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

2021-02-25 16:37 UTC, TS000 approved these changes
All tests pass and the manual check looked great!

2021-02-26 14:53 UTC, mjlumetta requested changes
couple of small but important changes to suggest here. lmk if you have thoughts on those considerations

2021-02-26 14:53 UTC, mjlumetta commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +    <section aria-labelledby="building-oidc-apps" id="building-oidc-apps">
this id is also used by the section heading below. if we're using the section as the parent of all the code blocks, we need to choose a unique id here. we could also conceivably use a class, which is slightly preferable imo if we're using it only as a CSS selector (Scopes has a similar thing).

2021-02-26 14:53 UTC, mjlumetta commented on src/containers/documentation/AuthorizationDocs.scss
> +          color: #80f8a2;
this should remain `$color-base`, i believe. depends on your browser, but the option color can be what shows up when you open the select options. mine looks fine on Chrome, but here's what it looks like in Firefox:

<img width="860" alt="Screen Shot 2021-02-26 at 9 42 19 AM" src="https://user-images.githubusercontent.com/3241493/109314182-09448b00-7817-11eb-9b26-650aa0961217.png">

cc @ediiotero if you have any other explanation or context to add on the styling patterns here

2021-02-27 12:02 UTC, charleystran commented on src/containers/documentation/AuthorizationDocs.scss
> +          color: #80f8a2;
This has been been fixed

2021-02-27 12:03 UTC, charleystran commented on src/components/oauthDocs/BuildingOIDCContent.tsx
> +    <section aria-labelledby="building-oidc-apps" id="building-oidc-apps">
I changed to use a class instead.

2021-03-01 20:57 UTC, mjlumetta approved these changes

2021-03-02 15:31 UTC, gileswells approved these changes
LGTM

2021-03-02 16:42 UTC, merged