Api 5081/update apply form to formik
department-of-veterans-affairs/developer-portal pull request #661
Opened 2021-03-05 18:56 UTC by RockslideJr

### Description

[API-5081](https://vajira.max.gov/browse/API-5081). This PR updates the apply form to use Formik to manage its state. It also combines the apply page and the applied page into one page to better allow for data transmission. 

### Process

- [x] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [x] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

Are there any remaining components or utilities we can remove now that the forms are all using Formik?

2021-03-09 17:18 UTC, mjlumetta reviewed
haven't really done any testing yet, but i know you've been waiting for feedback on this one so i'm gonna leave these comments here. looks good overall, and exciting to cut so much stuff.

2021-03-09 17:18 UTC, mjlumetta commented on src/store.ts
> -const saveApplicationState = (state: RootState): void => {
are we cool with removing the saving-the-form functionality? i think that's probably fine to do, but want to clarify with everyone.

2021-03-09 17:18 UTC, mjlumetta commented on src/utils/validators.ts
> +const PARTIAL_URL_PATTER = /^http[s]?:[/][/][^/:?#]+(:[0-9]+)?([/][^?#]*)?$/;
missing the last N on "pattern"

2021-03-09 21:31 UTC, RockslideJr commented on src/components/formField/FormField.tsx
> +        !isCheckOrRadio(props) && <OtherField shouldDisplayErrors={shouldDisplayErrors} {...props} />
The intention was to simplify the use of the component (and of building forms). If you're building a form, you just need to use the `FormField` component, which takes care of determining the appearance of the component. It also mirrors the use of Formik's `Field` component, which is generic to all field types.

2021-03-09 21:45 UTC, RockslideJr commented on src/components/formField/components/OtherField.tsx
> +const OtherField: FC<OtherFieldProps & SubComponentProps> = ({ description, label, name, required, shouldDisplayErrors, ...props }) => {
Yeah i wasn't very confident about this naming. I didn't think about selects, but I did think about number and date types, which is why i shied away from just `TextField`; although given that those fallback to text fields it may be the right way to go.

If we stick with the generic `FormField` component to match Formik's generic `Field` component, I think i'll go back through and make sure all the potential form field types are handles.

2021-03-09 21:51 UTC, RockslideJr commented on src/containers/apply/ApplyHeader.tsx
> -    <p
yeah that was the reason, I'll go ahead and move the header information directly into `Apply`

2021-03-16 22:59 UTC, alexandervalencia reviewed
Huge ✂️ code cut! ✂️  I love it!

I think there's some adjustments to be made but others are welcome to give feedback

2021-03-16 22:59 UTC, alexandervalencia commented on src/components/formField/components/OtherField.tsx
> +  const fieldClass = props.as === 'textarea' ? classNames('vads-u-margin-top--2p5') : '';
I actually think this is fine since we are looking for consistency, if the fields are developed with the VA Design Guide in mind then I'm not sure we would want to allow people to choose styles that go outside that standard.

But feel free to push back on that thought

2021-03-16 22:59 UTC, alexandervalencia commented on src/containers/apply/ApplyForm.test.tsx
> +      </MemoryRouter>
no more store! 😄

2021-03-16 22:59 UTC, alexandervalencia commented on src/components/formField/components/CheckboxRadioField.tsx
> +  const fieldId = `${idReadyName}FormField${value ?? ''}`;
does `value` need to be `toHtmlId`-ified?

2021-03-16 22:59 UTC, alexandervalencia commented on src/containers/apply/ApplySuccess.tsx
> -        <title>Welcome to the VA API Platform</title>
New title: https://github.com/department-of-veterans-affairs/developer-portal/pull/661/files#diff-7cea5c02922ee30b89a472c2681730286f8facb4c7dc74865ff576616b8664bcR10

was this requested by Brent?

2021-03-16 22:59 UTC, alexandervalencia commented on src/containers/apply/OAuthAppInfo.tsx
> +      </a>, and apps that cannot will use the&nbsp;
non-breaking: aesthetically, I like `{' '}` over `&nbsp;` but, I don't think this really needs to change

2021-03-16 22:59 UTC, alexandervalencia commented on src/store.ts
> -const saveApplicationState = (state: RootState): void => {
Looks like there's a pretty easy-to-use package ready to go if we want to keep the functionality: https://github.com/jaredpalmer/formik-persist

Out of curiosity... what's the reasoning behind saving the form state in session storage? In case someone hits the back button on accident?

2021-03-18 13:23 UTC, mjlumetta commented on src/components/formField/FormField.tsx
> +        !isCheckOrRadio(props) && <OtherField shouldDisplayErrors={shouldDisplayErrors} {...props} />
i tend to think this is a good case _not_ to use the DRY principle. my thinking is that, since Formik already provides us the generic `Field` component, what i'd want from our wrapper components when i'm writing a form is the specific markup for that control. the implementation does give us that, but it's two levels separated from my form and has more conditionals in between. so it's my personal preference to go with a more specific route.

i'm flexible on this point; if you prefer to have the generic `FormField` managing all of them, i'm not strictly opposed to that. it's more that i feel like i'd get more value out of the more specific approach, personally.

2021-03-22 21:16 UTC, RockslideJr commented on src/components/formField/FormField.tsx
> +        !isCheckOrRadio(props) && <OtherField shouldDisplayErrors={shouldDisplayErrors} {...props} />
After a few weeks of sitting on it, my passion for a unifying singular component has waned. I moved the underlying components up.

2021-03-22 21:28 UTC, RockslideJr commented on src/containers/apply/ApplySuccess.tsx
> -        <title>Welcome to the VA API Platform</title>
This just came about as a side-effect of converting the two pages into one page. It didn't make a lot of sense to change the browser title when the page stays the same.

2021-03-23 19:32 UTC, alexandervalencia approved these changes
This looks good to me, great work on the changes @RockslideJr ! 🚀

2021-03-23 20:57 UTC, RockslideJr commented on src/components/formField/TextField/TextField.tsx
> +const TextField: FC<TextFieldProps> = ({ description, className, label, name, required, type = 'text', ...props }) => {
`undefined` works just as well for react (it won't add the required attribute if the value is falsey) but i think it's clearer with the default of false, so i'll add it back in. Good callout

2021-03-23 20:58 UTC, RockslideJr commented on src/components/formField/ChecboxRadioField/CheckboxRadioField.tsx
> +import classNames from 'classnames';
Thank you for always finding my typos. I truly, truly appreciate it.

2021-03-23 21:18 UTC, alexandervalencia approved these changes
Re-approving

2021-03-26 16:48 UTC, mjlumetta submitted a review, later dismissed
looks good by and large. i'm going to add a couple of follow-up comments based on testing, though – details that may or may not be things we want to adjust.

2021-03-26 16:48 UTC, mjlumetta commented on src/components/formField/CheckboxRadioField/CheckboxRadioField.tsx
> +  const idReadyValue = toHtmlId(value ?? '');
does this need to be id-compliant? not sure i'm following that exactly. also, it seems like it might be strange to have a `value=""` attribute if the only thing we care about is the boolean checked value?

2021-03-26 16:48 UTC, mjlumetta commented on src/store.ts
> -const saveApplicationState = (state: RootState): void => {
not really sure, it's been around forever, since before i started. i would imagine if someone needs to go back and forth between pages (like, let's say i'm looking at the APIs and then jump back to the docs to see what each of them offer, or i'm filling out the OAuth info and need to jump back to Authorization to refresh on what the client ID and redirect URL are for, etc).

2021-03-26 16:51 UTC, mjlumetta commented
small UX thing: because the URLs for the form and the result are now the same, it's not possible to navigate back to the form without going to a different page first. while that obviously _shouldn't_ be a need, it unfortunately could be right now. for example, if i look at what i requested and realize i missed something, or if i put an OAuth redirect URL that i realized doesn't make sense, i might want to re-apply (or even to add multiple redirect URLs). if i click "Request an API key", nothing happens.

2021-03-26 17:05 UTC, mjlumetta commented
some UI issues: first, if any of the checkboxes have been touched – for example, by tabbing with the keyboard, instead of clicking individually with the mouse – it marks all of the checkboxes invalid because none have been touched.

<img width="453" alt="color only validation for checkboxes" src="https://user-images.githubusercontent.com/3241493/112667166-524a2800-8e33-11eb-9aa3-4feadfe163ad.png">

second, there's no error message displayed in text; the only indication is a red border on the left. there are two issues with this: 

1. colorblind users have no idea what the new border is for and can't infer that it's an error. therefore, it violates [WCAG SC 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html).
2. users without colorblindness may not be clear on what the issue is.

finally, one smaller issue: the change in location of the "(*Required)" on the terms of service checkbox feels a little awkward to me? that issue is minor compared to the API checkboxes, though.

<img width="329" alt="NewTermsOfServiceRequiredLocation" src="https://user-images.githubusercontent.com/3241493/112667710-faf88780-8e33-11eb-836d-95848b2e1352.png">

2021-03-26 17:46 UTC, mjlumetta commented
I forget if I flagged this issue elsewhere or not, but there's an issue on VoiceOver where the description won't accept any input. I played around with it for a few minutes, and it looks like removing the `aria-describedby` pointing to an empty element fixed it? not sure why that would be, but I think we should make that attribute conditional on whether or not there's anything actually describing the input.

2021-03-26 17:50 UTC, mjlumetta requested changes
requesting changes for the a11y issues. overall i do think it's in good shape, but we should tie off those issues before merging, imo.

2021-03-29 17:25 UTC, RockslideJr commented
@mjlumetta I wasn't able to reproduce the voiceover issue (i tried on chrome and safari). Is there something i need to be doing besides just using VoiceOver?

2021-03-29 17:33 UTC, RockslideJr commented
> some UI issues: first, if any of the checkboxes have been touched – for example, by tabbing with the keyboard, instead of clicking individually with the mouse – it marks all of the checkboxes invalid because none have been selected.
> 
> <img alt="color only validation for checkboxes" width="453" src="https://user-images.githubusercontent.com/3241493/112667166-524a2800-8e33-11eb-9aa3-4feadfe163ad.png">
> 
> second, there's no error message displayed in text; the only indication is a red border on the left. there are two issues with this:
> 
> 1. colorblind users have no idea what the new border is for and can't infer that it's an error. therefore, it violates [WCAG SC 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html).
> 2. users without colorblindness may not be clear on what the issue is.

(sent on slack, but posting here for context perpetuity)
Do we have a desired state here? I'm considering creating a component for the fieldset that adds the error class at that level and also displays the error message as part of the label. This will make sure the error is displayed and the visual indicator isn't individual for the fields. It does still mean that the error will display when they tab to the second checbox though, which doesn't feel great. It looks like the current form just doesn't display any validation information on the checkbox list, but that doesn't seem great either

2021-03-30 18:19 UTC, mjlumetta commented
> What do you think about adding a 're-apply' button to the page? The button could reset the form. If not, I can split the pages back out again; although that will take a bit of finagling to get the data to pass across.

gonna tag in @brentschneider here as well. that feels like a strange UX to me, but then again, not a lot about this feels great. maybe "Apply for new APIs"?

2021-03-30 18:41 UTC, RockslideJr commented on src/components/formField/CheckboxRadioField/CheckboxRadioField.tsx
> +  const idReadyValue = toHtmlId(value ?? '');
this is being used in the id to distinguish between multiple checkboxes or radio buttons with the same name, the value on the field is just `value`

2021-03-31 21:00 UTC, brentschneider commented
I'm really close to providing new language and design for the list of APIs. 
Will post in ticket API-5081 when ready to had over.

2021-04-07 20:08 UTC, RockslideJr commented
@mjlumetta I took a stab at using sub-routers to have multiple pages, but i wasn't able to get it to a state that i was happy with in a short period of time. With the updates to the page on the horizon I say we just go with this as-is for now.

2021-04-07 21:28 UTC, mjlumetta approved these changes
looks good to me. thanks for bearing with the feedback @RockslideJr, and great job cutting out a lot of boilerplate code on this refactor!

2021-04-07 21:44 UTC, merged