Update auth docs copy, e2e helper, and visual regression test
department-of-veterans-affairs/developer-portal pull request #673
Opened 2021-03-10 20:49 UTC by ediiotero

### Description

Update auth docs copy, e2e helper, and visual regression test

2021-03-10 20:57 UTC, mjlumetta approved these changes
thanks Eddie, and sorry again for not catching the original PR. one small cleanup suggestion: can delete the old, now-unused snapshots too, although that's not absolutely necessary to commit these changes. (think that you'd have to do that manually, `jest-image-snapshot` isn't smart enough to do that by itself.)

2021-03-10 21:11 UTC, mjlumetta submitted a review, later dismissed

2021-03-20 02:25 UTC, gileswells commented
@ediiotero I completely didn't see that you had the changes for the visual regressions in a different PR. While I don't have the text change in my PR I do have the urls and updated screenshots in #679. I suspect when that merges on Monday your branch might end up with a fair number of conflicts.

2021-03-22 14:46 UTC, gileswells commented
@ediiotero #679 is now merged so you have some conflicts on this and some redundant changes I think.

2021-03-23 14:12 UTC, gileswells requested changes
I think we might have inadvertently doubled up on `/explore/authorization` tests

2021-03-23 14:12 UTC, gileswells commented on src/e2eHelpers.ts
> +  '/explore/authorization?api=claims',
Is this route needed? I had added `/explore/authorization` a few lines above in a different PR.

2021-03-23 14:39 UTC, ediiotero commented on src/e2eHelpers.ts
> +  '/explore/authorization?api=claims',
yeah you're right, removed it

2021-03-23 15:10 UTC, gileswells approved these changes

2021-03-23 15:42 UTC, merged