API-5390: Include Build Version In the Developer Portal UI
department-of-veterans-affairs/developer-portal pull request #678
Opened 2021-03-15 21:47 UTC by TS000

### Description
As a developer
I want to be able to quickly check the code version that is currently deploy in PROD
so that we can easily track the changes that are part of this version plus getting the version build to fill out MR request for future deployments.

### Process
Created a component called AppVersion.
Created a test for AppVersion.
Created stylesheet for AppVersion.

**Build time variable inclusion**: Passed the version hash from `buildspex-ci.yml`to the build process within `buildspex-ci.yml` hoping this adds the hash to the available `ENV` variables that can be accessed from the FE.

Currently experimenting with the build time variable inclusion which can only be tested in staging. The FE side of things works and is being tested.

- [ x] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [x ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

Feedback welcome

2021-03-16 17:52 UTC, johanna-adhoc requested changes

2021-03-16 17:52 UTC, johanna-adhoc commented on src/components/appVersion/AppVersion.tsx
> +  <p className="app-version">{currentAppVersion}</p>
I would rename the class app-commit so when the build version gets integrated there is no confusion

2021-03-16 17:52 UTC, johanna-adhoc commented on package.json
> +    "git-info": "git log -1 --oneline > src/components/appVersion/appInfo.txt"
I think the command git-info should not be part of the scripts

2021-03-16 17:52 UTC, johanna-adhoc commented on cicd/buildspec-ci.yml
> +        REACT_APP_COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
Should we only add the first 6 characters? I have seen that as a practice

2021-03-16 18:02 UTC, TS000 commented on package.json
> +    "git-info": "git log -1 --oneline > src/components/appVersion/appInfo.txt"
oops that was left in there from a test i was doing, ill remove. Thanks!

2021-03-16 18:03 UTC, TS000 commented on cicd/buildspec-ci.yml
> +        REACT_APP_COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
I'm not aware of any best method to serve the codebuild hash but if you say 6 char i can make that happen.

2021-03-17 12:09 UTC, anthony-kopczyk reviewed
Functionally everything looks good. I just have a couple questions/suggestions.

2021-03-17 12:09 UTC, anthony-kopczyk commented on src/components/appVersion/AppVersion.test.tsx
> +});
I think we're trying to move away from enzyme. The react testing library should work here.

2021-03-17 15:51 UTC, TS000 commented on cicd/buildspec-ci.yml
> +        REACT_APP_COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:6}
React requires REACT_APP in order for variables to be passed to the available ENV variables. All variables without REACT_APP are ignored in the build process. [See docs here](https://create-react-app.dev/docs/adding-custom-environment-variables/).

2021-03-17 17:28 UTC, TS000 commented on Makefile
> +REACT_APP_COMMIT_HASH ?= REACT_APP_COMMIT_HASH
This was a left over from the myriad of things I tried 😅

2021-03-17 18:38 UTC, TS000 commented on src/components/appVersion/AppVersion.test.tsx
> +});
Moved over to testing-library 👍

2021-03-18 13:35 UTC, johanna-adhoc requested changes

2021-03-18 13:35 UTC, johanna-adhoc commented on src/components/banner/Banner.tsx
> +              <AppVersion />
Can you move the AppVersion Element to the root of the footer?

2021-03-18 17:06 UTC, anthony-kopczyk reviewed
One question about maybe a line not being needed - I'm not sure.

And then there are two files that don't end in new lines. If there's a new commit, you can throw those in with it.

2021-03-18 17:06 UTC, anthony-kopczyk commented on cicd/buildspec-ci.yml
>          done
In the Makefile, REACT_APP_COMMIT_HASH is being set to COMMIT_HASH.
This makes me think that the REACT_APP_COMMIT_HASH in buildspec-ci.yml isn't actually being used, since Makefile is using COMMIT_HASH.

2021-03-18 17:06 UTC, anthony-kopczyk commented on .env.test
> +REACT_APP_COMMIT_HASH=123456
Could add a new line to this if you make another commit.

2021-03-18 17:06 UTC, anthony-kopczyk commented on Makefile
> +		--env REACT_APP_COMMIT_HASH=${COMMIT_HASH} \
_Just me rambling below_

This is more in line with how I was thinking of passing the environment variable. It looks like maybe it's immediately accessible to the Makefile. Thought it would need passed in, but I guess it makes sense. Oooh! I just saw the for loop in buildspec-ci.yml. I see now. Yeah.

Okay, so I was originally think (in the spike ticket), we needed to (in the buildspec-ci.yml) do `make build_app ENVIRONMENT=${env} COMMIT_HASH=${COMMIT_HASH}`.. but since the make command happens on the same machine, that environment variable is already defined. The only reason ENVIRONMENT is being set is because of the for loop.

🤯 

Well, that makes this a little less complicated. Was thinking we had to pass it through 4 or so places.

2021-03-18 17:06 UTC, anthony-kopczyk commented on src/components/appVersion/AppVersion.scss
> +}
If you make another commit, can add a new line on the end of this file.

2021-03-18 17:07 UTC, anthony-kopczyk commented on .env.test
> +REACT_APP_COMMIT_HASH=123456
Seeing it's not clear in the comments of the review. This file doesn't end in a new line.

2021-03-18 17:07 UTC, anthony-kopczyk commented on src/components/appVersion/AppVersion.scss
> +}
Seeing it's not clear in the comments of the review. This file doesn't end in a new line.

2021-03-18 18:18 UTC, johanna-adhoc requested changes

2021-03-18 18:18 UTC, johanna-adhoc commented on cicd/buildspec-ci.yml
>          done
that is a good point... if we are not using REACT_APP_COMMIT_HASH we should remove the declaration.

2021-03-18 21:59 UTC, mjlumetta submitted a review, later dismissed
changes look good to me overall, with the caveat of the comment from Johanna that i seconded. i've got a couple additional questions that maybe can't be resolved right now but are worth considering.

@duganth-va is refactoring the dev portal pipeline based on the concerns raised in [this thread](https://lighthouseva.slack.com/archives/CAZF880HW/p1614290399049100). the short version as relates to this PR is that the build in the CI job is not going to be used for either review instances or releases (and therefore not the deployed site). PR deploys are going to be part of the new job in #670, and the release job is going to be refactored later. i _think_ it'll probably be fine in both, but we need to make sure that `COMMIT_HASH` variable doesn't get lost in the process in a way that's going to break this functionality.

also, i think it'd be cool to have the tagged version in here too for the release. that won't be that relevant until the build for the release happens in the release job itself, but might be useful to think about now.

2021-03-18 21:59 UTC, mjlumetta commented on src/components/banner/Banner.tsx
> +              <AppVersion />
yeah, i'd second this suggestion. this location feels kind of arbitrary, and i'd prefer it to be closer to the top level so it's easily accessible.

2021-03-19 14:55 UTC, TS000 commented on Makefile
> +		--env REACT_APP_COMMIT_HASH=${COMMIT_HASH} \
This is a grey area and the only way to test is to remove it, build it and see if the variable is there. Just pushed a commit to test this out.

2021-03-19 14:56 UTC, TS000 commented on cicd/buildspec-ci.yml
>          done
Just pushed a commit to see if we need REACT_APP_COMMIT_HASH in the build loop or if having in the Docker build process within Makefile is enough. All i know for sure is REACT_APP_COMMIT_HASH in the build loop works.

2021-03-19 15:28 UTC, johanna-adhoc approved these changes
LGTM

2021-03-19 15:36 UTC, TS000 commented on src/components/banner/Banner.tsx
> +              <AppVersion />
Moved to Footer. Thanks you two!

2021-03-19 15:36 UTC, TS000 commented on .env.test
> +REACT_APP_COMMIT_HASH=123456
done, thanks!

2021-03-19 16:10 UTC, anthony-kopczyk commented
> also, i think it'd be cool to have the tagged version in here too for the release. that won't be that relevant until the build for the release happens in the release job itself, but might be useful to think about now.

This was the intended functionality but after looking through the pipelines we realized the best we could do in the current state is the commit hash. This is absolutely on the table once the pipelines are updated. I thought we made a jira ticket for this, but I guess we didn't. Put in https://vajira.max.gov/browse/API-5877 for it.

2021-03-19 16:12 UTC, anthony-kopczyk reviewed
It all looks good to me. There's one thing I think we should check up on, unrelated to the build version. But other than that it looks all good to go!

2021-03-19 16:12 UTC, anthony-kopczyk commented on src/components/banner/Banner.tsx
> +                  aria-label="Here's how you know this is an official website"
I've seen this in another few files. Not sure if other teams will be on board changing this over. Might want to check with someone on Okapi.

2021-03-19 16:22 UTC, TS000 commented on src/components/banner/Banner.tsx
> +                  aria-label="Here's how you know this is an official website"
That came from running a format with the lint file. I talked to Quokka and they said to go with what the linter does. I also checked the place where it's used with Wave and it was fine.

2021-03-19 16:35 UTC, anthony-kopczyk approved these changes
Looks good to go

2021-03-19 17:04 UTC, merged