API-6710: Update support to help guide veterans
department-of-veterans-affairs/developer-portal pull request #733
Opened 2021-05-14 16:46 UTC by anthony-kopczyk

### Description

Jira Ticket: https://vajira.max.gov/browse/API-6710

This set of changes is intended to help guide them to va.gov or their local VSO to find data, since the portal contact us page is intended for developers and API questions

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-05-18 17:16 UTC, gileswells commented
@anthony-kopczyk does this pass visual regressions? I know the npm audit currently fails but with on page changes I'm expecting those to fail.

2021-05-18 19:54 UTC, anthony-kopczyk commented
> @anthony-kopczyk does this pass visual regressions? I know the npm audit currently fails but with on page changes I'm expecting those to fail.

Oh! I didn't think of running them/forgot about them. They should fail with these changes. I'll get this updated with updated files. Thanks!

2021-05-19 17:13 UTC, gileswells requested changes
Unless there's a reason I'm missing for using the key I'd much prefer to see it bundled up a little bit more since it's all the same markup wrapping the actual text.

2021-05-19 17:13 UTC, gileswells commented on src/containers/support/ContactUs.tsx
> +            key="contactus"
Is there a reason you're using a key here? From my testing you don't need it and if that's the case you can move the entirety of the `<AlertBox />` component into the `ContactUsAlertComment.tsx` file.

2021-05-19 19:13 UTC, anthony-kopczyk commented on src/containers/support/ContactUs.tsx
> +            key="contactus"
That comes from copy/pasta when using this component. I pulled it from the APIDocs or something like that (haven't done the alert box before, and now it's fairly apparent to me I didn't spend enough time making sure I knew the component).

I'll look at that component and try to tidy it up. Being able to move the entire list box into that other file will make it much cleaner too.

Thanks!

2021-05-20 16:28 UTC, gileswells approved these changes
LGTM

2021-05-20 16:30 UTC, merged