API-8096 API-8097: Open redirect fixes for Fortify
department-of-veterans-affairs/developer-portal pull request #780
Opened 2021-06-22 15:07 UTC by gileswells

### Description

https://vajira.max.gov/browse/API-8096
https://vajira.max.gov/browse/API-8097

Updates no longer take the url param and directly push that into a link tag but instead grabs it from a data store item where it's static text.

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-06-23 22:15 UTC, mjlumetta requested changes
some mixup between use of categories and APIs here, i think. works for 4 categories (Appeals, Benefits, Facilities, Forms) by coincidence, in that each has an API with the same key/identifier as the category's key, but not the other 2.

2021-06-23 22:15 UTC, mjlumetta commented on src/containers/documentation/ApiNotFoundPage.tsx
> +  const api = lookupApiByFragment(apiCategoryKey) ?? { urlFragment: '' };
this doesn't appear to work (see comment below) because it doesn't follow the contract for `lookupApiByFragment` because the parameter is supposed to be an API URL fragment/key, not the category key. it coincidentally works for 4 of 6 APIs because there's an API that has the same key/identifier as the category.

can we redirect to the 404 page if the category is null? does that solve the scan issue?

2021-06-23 22:15 UTC, mjlumetta commented on src/containers/documentation/QuickstartPage.tsx
> +      return <Redirect to={`/explore/${apiLookup.urlFragment}`} />;
same thing here – works for the first 4 APIs but not the last 2. would suggest checking that the category is present (however we look that up, with `getApiDefinitions` or `lookupCategory`) rather than looking up an API (which will work accidentally in many cases but not all).

2021-06-28 21:15 UTC, gileswells commented on src/containers/documentation/ApiNotFoundPage.tsx
> +  const api = lookupApiByFragment(apiCategoryKey) ?? { urlFragment: '' };
What we should be doing is showing the 404 on the url it happens on and in fact [there's a ticket](https://vajira.max.gov/browse/API-6348) I'm about to pull in that does exactly that. The main issue is pulling the url path parameter directly into a `<Link` or `<Redirect` and Fortify isn't able to dig into the code to determine that even getting to the offending code means that it's been validated by way of everything else happening.

2021-06-28 21:16 UTC, gileswells commented
@mjlumetta I've had to rework how it functions but this satisfies the Fortify scan.

2021-06-30 15:15 UTC, gileswells commented
Going to drop this to draft status while we wait to see if these open redirects can be explained away in the Fortify scans. Depending on that result we can close / revisit this.

2021-12-21 20:12 UTC, gileswells commented
Closing since this is way out of date and there hasn't been an update saying these updates are required.

2021-12-21 20:12 UTC, closed without merging