Api 7691 create working with our apis page
department-of-veterans-affairs/developer-portal pull request #785
Opened 2021-06-24 19:25 UTC by keithosayande

### Description
As part of the Consumer Docs epic, this PR creates the Working With Our APIs page, which is part of Consumer Onboarding.

- [Design](https://www.figma.com/file/9sOD2GDAsyNTayvOqKlcJV/API-3854-Consumer?node-id=1321%3A9541)
- [Content](https://docs.google.com/document/d/1PlmJRJimCnw0n-v_aWywDQNFF5cSjDRSeBD9xnSKW_c/edit)

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-06-24 21:20 UTC, mjlumetta reviewed
some smaller requested changes here. TODO still: proofread.

no place to comment this, but I would also suggest adding `CONSUMER_APIS_PATH` to the path list in `src/e2eHelpers.ts` (and subsequently updating screenshots). this will include the page in visual regression and accessibility tests.

2021-06-24 21:20 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +    <CollapsiblePanel panelName="Thoughtful, consistent versioning to reduce the impact of changes.">
i believe the `CollapsiblePanel` component is [deprecated](https://design.va.gov/storybook/?path=/docs/components-collapsiblepanel-deprecated--default). as a result, we'll want to use the [`va-accordion` component](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default). the interface is similar, although i think it'll be a bit strange since we'll only have one accordion item for each section.

2021-06-24 21:20 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        See our <a href="/release-notes">release notes</a>.
generally, we prefer to use `Link` from `react-router-dom` for internal links because it maintains the client-side routing (no HTTP request to the S3 bucket). on the other hand, native `a` tags reload the site. same comment applies to all internal links on the page

2021-06-24 21:20 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        Our <a href="https://dev-api.va.gov">sandbox environment</a> is deployed in the VA
shouldn't this be `sandbox-api.va.gov`? I know the content says dev, but I doubt that's what we actually want?

2021-06-24 21:20 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        Our <a href="https://api.va.gov">production environment </a>is deployed in the VA Enterprise
extra space in the link instead of outside

2021-06-24 21:20 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        <a href="https://valighthouse.statuspage.io/"> status page</a>.
extra space in the link. can use &nbsp; if we need to because the code wraps lines (before `a` tag on line 92 or after "our" on line 91)

2021-06-25 14:55 UTC, gileswells requested changes
Overall looks good just some formatting and component usage updates and it should be good to go.

2021-06-25 14:55 UTC, gileswells commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +    <CollapsiblePanel panelName="Thoughtful, consistent versioning to reduce the impact of changes.">
For reference there is [a ticket](https://vajira.max.gov/browse/API-6384) that exists to update all existing CollapsiblePannel components to use the new `va-accordion` component. Ideally though, as @mjlumetta said, this is deprecated so we'd not add more just to have them replaced in the near future.

2021-06-25 14:55 UTC, gileswells commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        limits by emailing us at <a href="api@va.gov">api@va.gov</a> with the following:
This link needs to be prefixed with `mailto:` so that it would trigger the user's email client to open.

2021-06-25 14:55 UTC, gileswells commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        filling out the form on <a href="/apply">our apply page</a>, or submit the form to receive a
Same comment from Mike above to use `<Link></Link>` here.

2021-06-25 14:55 UTC, gileswells commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        <a href="https://valighthouse.statuspage.io/"> status page</a>.
Looks like Mike's comment got actually parsed, which is odd, but one option is to use ` &nbsp;` at the end of the previous line or you can use `{' '}`. Depending on your code formatter it should make this change for you once you remove the space within the link tag.

Example: https://github.com/department-of-veterans-affairs/developer-portal/pull/785/files#diff-87e2d12712640a9afa59c01340b4889d402510f9ef5872cf0382b4fe0a0e4899R180

2021-06-25 14:55 UTC, gileswells commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        <a href="/support/contact-us">support page </a>
`<Link>` tag

2021-07-09 15:42 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +    <CollapsiblePanel panelName="Thoughtful, consistent versioning to reduce the impact of changes.">
saving for the other ticket, resolving

2021-07-09 16:18 UTC, mjlumetta reviewed
two very small touch-ups. can get this merged today if you've got time to make them.

2021-07-09 16:18 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +        filling out the form on <Link to="/apply">our apply page</Link>, or submit the form to
rather than linking to `/apply` here, let's use `CONSUMER_SANDBOX_PATH`. when the feature flag is on, `/apply` will redirect there anyway, so let's use the direct URL.

2021-07-09 16:18 UTC, mjlumetta commented on src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
> +    <h2>Rate limiting</h2>
i would suggest adding an `id` attribute to each `h2` (and optionally `h3`, although that's less important). this is to support linking directly to each section. we definitely need it for this one; the Working with Our APIs page links directly here (see [this line in that PR](https://github.com/department-of-veterans-affairs/developer-portal/pull/786/files#diff-dfc63aae71d384d0c14862aa0a732e08b4fbcc3ac553d4dc797bb2d6bd373b5dR9)).

2021-07-09 19:23 UTC, mjlumetta approved these changes
lgtm! ✨

2021-07-09 20:10 UTC, mjlumetta approved these changes
re-approving

2021-07-13 17:29 UTC, merged