Dynamically create apply page checkbox list
department-of-veterans-affairs/developer-portal pull request #791
Opened 2021-06-29 15:20 UTC by ediiotero

Story: [API-7515](https://vajira.max.gov/browse/API-7515)

### Description

Currently the Apply page is using it's own custom JSON representations for APIs that are displayed as checkboxes. 
This PR is using the api query to get api definitions to populate the checkbox list on the Apply page.

- [X] Tests added or updated for change

2021-06-29 15:21 UTC, ediiotero commented on src/apiDefs/data/benefits.ts
> +    altID: 'claims',
added altIDs to match the kong keys on the backend

2021-06-29 20:55 UTC, gileswells requested changes
Looks great but I had some ideas on possible improvements.

2021-06-29 20:55 UTC, gileswells commented on src/apiDefs/data/facilities.ts
> + import { facilitiesContent, FacilitiesReleaseNotes } from '../../content/apiDocs/facilities';
Extra space added inadvertently

2021-06-29 20:55 UTC, gileswells commented on src/apiDefs/schema.ts
> +  readonly altID?: string;
Is this optional because it's not required for previously deactivated APIs?

2021-06-29 20:55 UTC, gileswells commented on src/containers/apply/Apply.test.tsx
> +      expect(screen.getByRole('checkbox', { name })).toBeInTheDocument();
This test is an additive test where it's checking to make sure they've all been added. I'd optionally like to see the reverse where those that shouldn't be added are confirmed to not be on the page. I can see this being either in this file or in the `ApplyForm.test.ts` file. Either one works for me and I certainly feel it doesn't need to be in both.

2021-06-29 20:55 UTC, gileswells commented on src/containers/apply/SelectedApis.tsx
> +const oauthInfo = getAllOauthApis()
I feel like this could be better placed in the `src/apiDefs/query.ts` file where we do more of these queries and then can also layer in the associated unit tests to make sure that these query tests are working. Adding a test to this query to make sure it's not grabbing more than it should would in theory make my previous test request unnecessary.

2021-06-29 20:55 UTC, gileswells commented on src/containers/apply/SelectedApis.tsx
> +const standardApi = getAllApis()
Same as above for `oauthInfo`. Could also bundle it into something like `getAllOpenRegistrationApis(oauth: boolean): APIDescription[] => {}` to kill 2 birds with one stone. Open to ideas here.

2021-06-30 15:25 UTC, ediiotero commented on src/containers/apply/SelectedApis.tsx
> +const oauthInfo = getAllOauthApis()
moved it over

2021-06-30 15:26 UTC, ediiotero commented on src/apiDefs/schema.ts
> +  readonly altID?: string;
Yeah that's one reason. I had to add this to keep the value of the checkboxes the same as they need to match the keys on the backend.

2021-06-30 15:26 UTC, ediiotero commented on src/containers/apply/Apply.test.tsx
> +      expect(screen.getByRole('checkbox', { name })).toBeInTheDocument();
moved it to the query file and added tests

2021-07-01 15:00 UTC, gileswells approved these changes
I can leave the variable name change suggestions but if you agree let me know when done and it'll be a quick re-approve.

2021-07-01 15:24 UTC, ediiotero commented on src/containers/apply/SelectedApis.tsx
> +const standardApi = getAllCurrentStandardApis()
agreed, made the change

2021-07-01 15:50 UTC, mjlumetta commented on src/apiDefs/query.ts
> +  getAllApis().filter((api: APIDescription) => api.enabledByDefault && api.altID && !api.oAuth && !isApiDeactivated(api));
i have some questions about these new functions. first, what does "current" here mean? from context, it seems like "enabled and not deactivated"; it's unclear where the `altID` factors in. to date, this data access layer kind of has the structure where `query` is the gateway to the `data` directory, and the `deprecated` and `env` files depend on `query` to dictate logic about what APIs are actually available in the UI (but `query` does not handle logic about enabled/disabled and deactivation). these functions would break that pattern; it's fine if we want to do that, but i'd be curious to hear your thoughts on why. my preference would be to use `Flag` on the apply page around these checkboxes rather than adding in additional logic here.

couple other related thoughts:
1. would still benefit from a `getAllStandardApis` function here (or "key auth" – i have a slight preference for that since it is more specific, regardless of what the UI says).
2. `enabledByDefault` does not take into account the environment variables, which are a big part of how enabled/disabled status is managed. using `Flag` would solve that, but we could also include that logic here.

2021-07-01 15:50 UTC, mjlumetta commented on src/apiDefs/query.test.ts
> +      expect(api).not.toHaveProperty('deactivationInfo');
i don't know how accurate this test is? non-deactivated APIs can still have `deactivationInfo` set. in general, i'm curious what the thought behind these tests are.

also, when these tests are run, do they have unique names? i would suggest writing it in such a way that they can be distinguished, if we're going to use `it.each` here.

2021-07-01 15:50 UTC, mjlumetta commented on src/apiDefs/schema.ts
> +  readonly altID?: string;
can you add a comment for this field to describe why it exists (vs `urlFragment`)? also, why optional vs required?

2021-07-01 16:44 UTC, gileswells commented on src/containers/apply/SelectedApis.tsx
> +    id: api.altID ?? '',
There wouldn't be an empty name here though. In order to get in the list of standard APIs you have to have an `altID`. This is just TypeScript being TypeScript.

2021-07-06 20:27 UTC, alexandervalencia approved these changes
Looks good!

2021-07-06 20:27 UTC, alexandervalencia commented on src/containers/apply/Apply.test.tsx
> -  });
I'm curious if we're still doing the same testing elsewhere now?

2021-07-07 14:58 UTC, ediiotero commented on src/containers/apply/Apply.test.tsx
> -  });
I feel like the SelectedApis test in ApplyForm.test.tsx covers this

2021-07-07 14:59 UTC, merged