API-6348 - Provide better URL validation and 404 handling in Routes.tsx
department-of-veterans-affairs/developer-portal pull request #806
Opened 2021-07-12 17:17 UTC by gileswells

### Description

https://vajira.max.gov/browse/API-6348

One of the overall goals here is to ensure that the proper 404 page shows up in place (without a redirect) within the dev portal. There are many paths that currently will render a black content block but not show the 404 page. [example with redirect](https://developer.va.gov/release-notes/banana) [example of blank content](https://developer.va.gov/explore/vaForms/banana)

### Process

Test all page urls to ensure that all pages are rendering the proper content and also check pages, especially wildcard routes, to ensure the proper 404 page shows up as expected.

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

This is a pretty substantial change as it aims to consolidate a lot of the routing logic into this single Routes.tsx file (which as an added benefit helps make the sitemap setup easier). Very much looking for thoughts and comments or places to improve.

2021-07-19 14:38 UTC, Cgfor3 submitted a review, later dismissed
Updates all look good - I'd wait for someone more knowledgeable to approve though :D

2021-07-19 15:13 UTC, SlakrHakr submitted a review, later dismissed
i havent looked at a ton of typescript previously but everything looks alright to my novice eyes.
i did at least pull down both master and this branch to compare locally and i cant reproduce the redirects in this new branch at all 👍🏻

2021-07-19 19:51 UTC, mjlumetta commented
getting blank content for the following routes (including no side nav):

- /explore/fake
- /explore/benefits/fake
- /explore/benefits/docs
- /explore/fake/docs/fake
- /release-notes/fake
- /support/fake

2021-07-19 19:54 UTC, mjlumetta requested changes
some holes in the logic - see [this comment](https://github.com/department-of-veterans-affairs/developer-portal/pull/806#issuecomment-882814239). think this is a good idea but needs a little tightening up, probably?

i think the thing we really need here is some integration tests for this `Routes` file. all this handling of routes and wildcard routes in particular is getting confusing, so there's no basis for confidence when you're making changes. having a test suite both to catch regressions and provide a specification of expected behavior would solve those problems; i think that would ideally be part of this change.

2021-07-19 19:54 UTC, mjlumetta commented on src/containers/documentation/DocumentationRoot.tsx
> -          {!shouldRouteCategory && <Redirect from="/explore/:apiCategoryKey" to="/404" />}
do we still want this safeguard to protect against wholes in the logic higher up? `/explore/fake` is currently not working.

2021-07-20 13:58 UTC, gileswells commented
> I think the thing we really need here is some integration tests for this `Routes` file.

@mjlumetta That was always the plan. Part of the reason I didn't fix the currently broken tests / write the new ones to make sure we were covering all our bases was I wanted to get some feedback to see if people would be on board with this style of declaring the routes directly like this before passing off to secondary routes per section (like in `DocumentationRoot`).

I'm working on those tests now and some of the holes that I apparently missed.

2021-07-20 14:02 UTC, gileswells commented on src/Routes.tsx
> +      {Object.entries(apiDefinitions)
I tried that a few different times BUT always with the shorthand `<></>` instead of the longhand `<React.Fragment></React.Fragment>` and now I'm feeling abundantly silly. I'll give that a go.

2021-07-21 15:07 UTC, gileswells commented on src/Routes.tsx
> +      {Object.entries(apiDefinitions)
Ended up reworking this to use a route builder method that loops over the APIs to create a simple array of paths. Much simplier in the end over this and avoids the issue of using a [`<React.Fragment>` within a `<Switch>`](https://stackoverflow.com/questions/58169397/redirect-doesnt-work-inside-switch-when-fragment-has-been-used).

2021-07-21 15:08 UTC, gileswells commented on src/containers/documentation/DocumentationRoot.tsx
> -          {!shouldRouteCategory && <Redirect from="/explore/:apiCategoryKey" to="/404" />}
I don't think it's necessary with the updates to the routes changes made today/yesterday.

2021-07-21 15:09 UTC, gileswells commented on src/content/explorePage.mdx
> +<h1 style={{ 'marginTop': '0' }}>
I believe that this page in it's entirety was only ever visible in the very weirdest of circumstances and with the routing changes this page should, in theory at least, never be routed. Will confirm before killing off.

2021-07-21 21:38 UTC, gileswells commented on src/content/explorePage.mdx
> +<h1 style={{ 'marginTop': '0' }}>
Well it would be routed to if an API was disabled in the config. While I can see how we might want to use that in the event of discontinuing an API without a replacement the `ApiNotFoundPage` component is a much better way to do that. I'd suspect that any true sunset of an API would be accompanied by a redirect to it's replacement or at least to the main category page.

2021-07-21 21:38 UTC, gileswells commented on src/content/explorePage.mdx
> +<h1 style={{ 'marginTop': '0' }}>
I've updated this to use the `ApiNotFoundPage` component and killed this file (and it's associated unit / e2e testing) off.

2021-07-22 13:31 UTC, gileswells commented
> getting blank content for the following routes (including no side nav):
> 
> * /explore/fake
> * /explore/benefits/fake
> * /explore/benefits/docs
> * /explore/fake/docs/fake
> * /release-notes/fake
> * /support/fake

All of these should now show the 404 page without a redirect. Also there's now e2e coverage to enforce this.

2021-07-22 14:31 UTC, mjlumetta reviewed
looking good. my main question is about potentially incorporating all these tests into one `Routes.e2e.ts` file – i think that could be beneficial to test all the routing in one place if we're trying to encapsulate the main logic inside `Routes.tsx`. open to discussion on that. everything else is minor comments.

2021-07-22 14:31 UTC, mjlumetta commented on src/containers/consumerOnboarding/ConsumerOnboardingRoot.e2e.ts
> +  it('should show the 404 page on /onboarding/invalid', async () => {
my preference for these tests would probably be to have them all in a single `Routes.e2e.ts` file rather than in the test suite for each top-level page. if the motivation for this PR is to consolidate the routing logic into a single place (`Routes.tsx`), it makes sense to also test that logic in the same place, imo. it also makes looking up routing behavior easier; if i want to know what should happen when i go to `/explore/fake/docs/appeals`, i know i can look at that file and see the tests. thoughts?

2021-07-22 14:31 UTC, mjlumetta commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => !isApiDeactivated(item) && flags[item.urlFragment])
why aren't we just using `Flag` here?

2021-07-22 14:31 UTC, mjlumetta commented on src/containers/documentation/ApiPage.tsx
> +  const flags = useFlag([FLAG_API_ENABLED_PROPERTY]);
why not

```suggestion
  const flags = useFlag([FLAG_API_ENABLED_PROPERTY, api.urlFragment]);
```

(if you move it after line 62)

i would also suggest clarifying what type of flag it is in the variable name so it's easier to remember exactly which value we're using here.

2021-07-22 14:31 UTC, mjlumetta commented on src/utils/routesHelper.ts
> +        apiRoutes.push(`/explore/${key}/docs/${api.urlFragment}`);
how does this work with disabled APIs (or categories)?

2021-07-26 15:03 UTC, gileswells commented on src/Routes.tsx
> -        <>
The main issue was that the sitemap generator wasn't able to go into sub-routes files. The whole section at the bottom of the Routes.tsx file was specifically for the sitemap. With the changes to how we do routes we don't need this last section (notice how there's no listed component on these routes).

2021-07-26 15:04 UTC, gileswells commented on src/containers/consumerOnboarding/ConsumerOnboardingRoot.e2e.ts
> +  it('should show the 404 page on /onboarding/invalid', async () => {
I like that. I'll do that today.

2021-07-26 15:15 UTC, gileswells commented on src/utils/routesHelper.ts
> +        apiRoutes.push(`/explore/${key}/docs/${api.urlFragment}`);
This helper doesn't care if something is disabled or depreciated. Because it takes in the categories (and their apis) as a parameter it just builds from there based on what it's given. If there was ever a need to build all the routes, even including deactivated routes, this helper would be already good to go. It assumes that you've made the decisions about deactivated routes before calling this helper.

2021-07-26 15:47 UTC, gileswells commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => !isApiDeactivated(item) && flags[item.urlFragment])
Personally I prefer a single place for the conditions with in a filter/map situation. Having a filter and then following it up with a flag later when it can all be handled in one filter method seems less straight forward. Also by waiting to use `<Flag` later you're passing more items to the `.map()` loop which caused more processing time. Milliseconds at worst but still why loop if it might return empty anyways?

2021-07-26 19:13 UTC, gileswells commented on src/Routes.tsx
> +    paramsConfig: {},
That is a concern that I have too but part of the primary drive behind this was the issue that wildcard routes within React Router aren't really that stellar in terms of what to do with a 404. There's no standard way of loading up a wildcard route but allow it to skip past if there's no matching value on the passed route parameter. 

Like `/explore/invalid` would, on a route of `/explore/:apiCategory`, always load the `DocumentationRoot` component and once you're in there it's impossible to kick back up to the parent and continue on through the routes till you hit the 404 catchall at the end. You can do that with a redirect, as we previously did / as many tutorials recommend, but the better user experience is to show the 404 in the place it happens.

2021-07-26 19:27 UTC, gileswells commented on src/utils/routesHelper.ts
> +        apiRoutes.push(`/explore/${key}/docs/${api.urlFragment}`);
I now see how this is a mistake with the current routes and it returning all paths to the sitemap rather than just the active ones / the ones enabled via .env configs. Sorting it out now.

2021-07-27 17:37 UTC, gileswells commented on src/containers/documentation/ApiPage.tsx
> +  const flags = useFlag([FLAG_API_ENABLED_PROPERTY]);
That suggestion as written wouldn't work. The available `api.urlFragment` values aren't flag names. Also if I tried to use it at the end of the `useFlag()` method then the api is possibly undefined (impossible in this routing but TypeScript doesn't know that) causing it to fallback using an inline conditional which just makes this turn ugly IMO.

```ts
const apiEnabledFlag = useFlag([FLAG_API_ENABLED_PROPERTY])[api?.urlFragment ?? ''];
```

I did end up changing the variable name to clarify things though which I think helps nicely.

2021-07-27 23:19 UTC, mjlumetta approved these changes
bunch of comments but they're all stylistic. i think this looks good overall and can be merged if you want to. there are some comments that i'd like to see resolved a bit more than others, but none of them are blocking.

2021-07-27 23:19 UTC, mjlumetta commented on src/components/Routes.e2e.ts
> +    const pageNotFound = await page.evaluate(() => document.querySelector('h1')?.innerHTML);
i'd have a slight preference for going with the [`pptr-testing-library`](https://testing-library.com/docs/pptr-testing-library/intro#usage) query here. don't think it's a huge issue with such a small query, but i think it's good to be in the habit of using the library since it expresses things in a user-centered way.

if you're interested in current examples:

```
mikelumetta@Mike-Lumettas-MacBook-Pro alt-developer-portal$ grep -rns pptr-testing-library src/
src//containers/documentation/AuthorizationDocs.e2e.ts:1:import { getDocument, queries } from 'pptr-testing-library';
src//containers/News.e2e.ts:1:import { getDocument, queries } from 'pptr-testing-library';
src//containers/releaseNotes/ReleaseNotes.e2e.ts:1:import { getDocument, queries } from 'pptr-testing-library';
src//containers/releaseNotes/CategoryReleaseNotes.e2e.ts:1:import { getDocument, queries } from 'pptr-testing-library';
src//App.e2e.ts:9:import { getDocument, queries } from 'pptr-testing-library';
```

this one is also up to you, no strong preference

2021-07-27 23:19 UTC, mjlumetta commented on src/Routes.tsx
> +/* eslint-disable no-console */
delete

2021-07-27 23:19 UTC, mjlumetta commented on src/Routes.tsx
> +    paramsConfig: {},
thanks, that makes sense. we can cross that bridge when we come to it

2021-07-27 23:19 UTC, mjlumetta commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => !isApiDeactivated(item) && flags[item.urlFragment])
oh, i agree we shouldn't use `Flag` and `filter()` together. but there's already a single flag for it, so i think we can just get rid of the filter function if we want? i'd prefer to use the flag because it's sort of a canonical way of figuring out what is and isn't available in React components, but this is okay if you prefer it. (also, i think using the flag would have been better before when it was just deactivated, too.)

[example](https://github.com/department-of-veterans-affairs/developer-portal/blob/master/src/containers/documentation/CategoryPage.tsx#L30)

2021-07-27 23:19 UTC, mjlumetta commented on src/containers/documentation/ApiPage.tsx
> +  const flags = useFlag([FLAG_API_ENABLED_PROPERTY]);
you could do this if you wanted:

```
const api = getApi(params.apiName);
const category = lookupApiCategory(params.apiCategoryKey);
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const apiEnabledFlag = useFlag([FLAG_API_ENABLED_PROPERTY, api!.urlFragment]);
```

but given your point, i'm fine with the current approach if that's your preference. 

also, did you push the variable change commit? don't see it right now

2021-07-27 23:19 UTC, mjlumetta commented on src/Routes.tsx
> -        <>
oh i was referring to the fragment use, not the rendering in the live site. that totally makes sense because of what you said, but i'm surprised that the sitemap generator worked for these routes given the trouble we ran into trying to use fragments earlier. maybe `react-router-sitemap` is doing its own thing there

2021-07-28 13:28 UTC, gileswells commented on src/containers/documentation/ApiPage.tsx
> +  const flags = useFlag([FLAG_API_ENABLED_PROPERTY]);
Forgot to commit / push. Will do with other tweaks.

2021-07-28 13:30 UTC, gileswells commented on src/Routes.tsx
> -        <>
I think the fragment issue was related to redirect or something else I recall. This shouldn't have been affected in my testing.

2021-07-28 17:02 UTC, gileswells commented on src/apiDefs/query.ts
> +import { isHostedApiEnabled } from './env';
I think @wwanamaker could create us a backlog ticket to do the refactor of this and personally I'd vote for option 3. Having a single condition to trigger inclusion or not is ideal to me.

2021-07-28 17:45 UTC, wwanamaker commented on src/apiDefs/query.ts
> +import { isHostedApiEnabled } from './env';
API-8933 in Jira!

2021-07-28 18:42 UTC, mjlumetta commented on src/apiDefs/query.ts
> +import { isHostedApiEnabled } from './env';
thanks to both of you! sounds good

2021-07-28 18:49 UTC, mjlumetta reviewed
one functional question about the `ApiNotFoundPage` component

2021-07-28 18:49 UTC, mjlumetta commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => flags[item.urlFragment])
wait – we don't want to show deactivated APIs here, do we? here's what the Health category looks like, including Urgent Care:

<img width="1242" alt="Screen Shot 2021-07-28 at 2 47 52 PM" src="https://user-images.githubusercontent.com/3241493/127379080-2829348f-9870-4b9a-8c88-272b6e95640b.png">

2021-07-28 19:06 UTC, gileswells commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => flags[item.urlFragment])
We don't. I got your previous comment backwards in my head thinking that just the flags would be enough to turn off the deactivated APIs for us. I've reverted this.

2021-07-28 19:47 UTC, mjlumetta approved these changes

2021-07-28 19:47 UTC, merged

2021-07-28 20:15 UTC, mjlumetta commented on src/containers/documentation/ApiNotFoundPage.tsx
> +          .filter((item: APIDescription) => flags[item.urlFragment])
ohhhh. yes, the flag could be enough, but it's a different flag