[API-5748]: Scaling font-size
department-of-veterans-affairs/developer-portal pull request #833
Opened 2021-08-17 19:33 UTC by Cgfor3

### Description

Add css to override USWDS font-size styling to the html element to allow content to change dynamically according to the browser font-size
Tested changes on Safari/Firefox/Chrome

### Process
- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [x] Accessibility concerns have been considered and addressed
  
  - [x] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback
N/A

2021-08-24 16:22 UTC, TS000 requested changes
I think we accidentally included a package upgrade in this PR.

2021-08-24 16:22 UTC, TS000 commented on package-lock.json
> +          "integrity": "sha512-sb9b0cp855NbkMJcskdSYA7b11Q8JsX4qe4pyUAfHp+Y6jBjJeek2ZVlwEfWayshEIwlIzXx0Fain3QG9JPm2A==",
Is there a reason these upgrades were included in this PR?

2021-08-24 16:52 UTC, mjlumetta reviewed
looks great! way better now. i have two requested changes:

1. the one issue i can see is the side nav does not scale across the site. could we please put those sizes in rem? the site will be perfect on this front if that's done (unless there's some line height discrepancies i missed, maybe? but it'll be great).
2. unless the `package-lock.json` changes are meaningfully, can we not commit them please? not the end of the world if we do but usually ideal to avoid that churn

2021-08-30 20:43 UTC, Cgfor3 commented
> 1. the one issue i can see is the side nav does not scale across the site. could we please put those sizes in rem? the site will be perfect on this front if that's done (unless there's some line height discrepancies i missed, maybe? but it'll be great).

What did you use to test this issue? I want to be sure I'm able to reproduce this

2021-09-01 14:40 UTC, Cgfor3 commented on src/components/sideNav/SideNav.scss
> +}
Using `rem` here to scale based on the value of the `html` element's `font-size` which we have now set to scale depending on the browser's `font-size` setting.

The browser's default `font-size` is `16px` which will result in our `html` element to have a `font-size` of `10px`, which is where the value of `1.5rem` comes from since we want a default `font-size` of `15px` for the list item anchor elements.

2021-09-03 16:13 UTC, mjlumetta approved these changes
thanks @Cgfor3! great to have this done and support adjustable font sizing ✨

2021-09-03 16:40 UTC, TS000 approved these changes
LGTM 🍡

2021-09-03 19:13 UTC, merged