Update CI failure slackwebhook
department-of-veterans-affairs/developer-portal pull request #881
Opened 2021-09-23 13:48 UTC by duganth-va

### Description
When CI jobs fail outside of the test a notification is sent to Slack to see if there is a problem with CodeBuild. These notifications were using the wrong webhook and being sent to DSVA workspace. 
This PR also updates the message with codebuild ID for easier identification.

2021-09-23 14:07 UTC, gileswells requested changes
I'd like to see this include a link rather than just show a build ID. Makes it more usable for AWS console users as well as AWS CLI users.

2021-09-23 14:07 UTC, gileswells commented on cicd/buildspec-ci.yml
> +          slackpost.sh "CI Pipeline failure for the developer portal. CodeBuild Job: ${CODEBUILD_BUILD_ID}"
Can we also provide a link to the build logs? If we have the job ID and job name it looks like this should be doable. This is the current build's url: `https://us-gov-west-1.console.amazonaws-us-gov.com/codesuite/codebuild/008577686731/projects/developer-portal-ci/build/developer-portal-ci%3Aefeaa8b5-6e2f-4948-aaa8-7f8198c4a19d?region=us-gov-west-1`

2021-09-23 14:09 UTC, gileswells requested changes

2021-09-23 14:09 UTC, gileswells commented on cicd/buildspec-ci.yml
>      # This webhook currently targets DSVA workspace #lighthous-deploys channel
This comment should also be updated to reflect where it's being sent to now.

2021-09-23 15:25 UTC, duganth-va commented
https://lighthouseva.slack.com/archives/C01CP09F04Q/p1632409507049300

2021-09-24 20:04 UTC, gileswells approved these changes
LGTM

2021-09-24 21:07 UTC, merged