Removing claims attributes from portal
department-of-veterans-affairs/developer-portal pull request #901
Opened 2021-11-02 15:27 UTC by ediiotero

### Description
Story: [API-10674](https://vajira.max.gov/browse/API-10674)

Removing what is left of Claims Attributes from the portal for clean up

- [X] Tests added or updated for change

2021-11-02 16:53 UTC, gileswells requested changes
Overall looks good to go but there are a couple items remaining in the `.env` files named `REACT_APP_CLAIMS_ATTRIBUTES_API_ENABLED` that can be removed.

2021-11-02 19:22 UTC, gileswells approved these changes
LGTM

2021-11-03 15:24 UTC, dsteeve commented on src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.test.tsx
> +      const filteredKeyAuthApis = allKeyAuthApis.filter(api => api !== /Benefits Intake API/);
not sure if this is what we want to do.  Was Claims Attributes being filtered out before because it was there in the allKeyAuthApis (and not really active) and now we don't need to filter out anything and can just use "allKeyAuthApis" instead?   not sure though, so am asking the question.

2021-11-03 16:02 UTC, mjlumetta commented on src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.test.tsx
> +      const filteredKeyAuthApis = allKeyAuthApis.filter(api => api !== /Benefits Intake API/);
@dsteeve i'm 99% sure you're correct here. and if not, why would Benefits Intake be filtered out? it's in the form

2021-11-03 16:04 UTC, mjlumetta commented on src/types/constants/index.ts
>  export const APPLY_STANDARD_APIS = [
seems like this array could probably be removed and computed instead, although up to you whether that's a refactor you think is worth doing now

2021-11-03 21:41 UTC, ediiotero commented on src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.test.tsx
> +      const filteredKeyAuthApis = allKeyAuthApis.filter(api => api !== /Benefits Intake API/);
good catch, I removed it

2021-11-03 23:31 UTC, dsteeve approved these changes
lgtm!

2021-11-04 13:54 UTC, merged