API-11512 Make Swagger docs go full width
department-of-veterans-affairs/developer-portal pull request #915
Opened 2021-12-02 15:40 UTC by imcgonigle

### Description
[Jira ticket API-11512](https://vajira.max.gov/browse/API-11512)

This PR updates the Swagger docs to take up the full width of the screen to make them easier to read.

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-12-07 15:44 UTC, SlakrHakr approved these changes
This looks awesome!
I have a strong feeling @jw81 is gonna be pumped for this one.
![image](https://user-images.githubusercontent.com/31224301/145060552-0eeeb277-0f14-4f4d-bbd9-59f31248d8de.png)

2021-12-07 16:20 UTC, imcgonigle commented
![visual-regression-test-ts-visual-regression-test-renders-explore-authorization-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066462-6105ff21-c0eb-4d5c-bd62-0fca30218896.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-appeals-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066468-e8d39d58-2d5c-401b-8c77-0677a4bc044e.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066473-f1eb8a8f-e823-453c-9801-9a6bbf995244.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-benefits-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066484-8eb86d2f-0b31-4114-a01d-a14d8e4b17d5.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-health-docs-quickstart-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066487-a059d415-e97f-454c-b57f-eaeaf2a9ad7f.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-health-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066490-afe41a01-edb5-4681-957a-1ae47858d23e.png)
![visual-regression-test-ts-visual-regression-test-renders-explore-properly-1-diff](https://user-images.githubusercontent.com/15026647/145066491-dcd910de-b626-4b24-941e-7078ebc53a9f.png)

2021-12-07 19:40 UTC, gileswells requested changes
If we can I think it'd be better if we keep the SwaggerUI on the left on larger screens. Everything else stays left so it looks weird when it's centered in the right column vs being aligned left. (my screen is a bit large but I don't think it's invalid)

2021-12-07 19:40 UTC, gileswells commented on src/components/contentWithNav/ContentWithNav.tsx
> +      { 'vads-l-grid-container--full vads-u-padding-x--4': fullWidth },
I think we'd be better off if we tried to incorporate `.vads-l-grid-container` vs `.vads-u-padding-x--4` here because as you get down to smaller screens the `.vads-l-grid-container` class has better support for sizing down the padding for us. Currently this `.vads-u-padding-x--4` keeps the `32px!important` padding on the left and right as it sizes down past 768px.

I wouldn't be opposed to bringing the rules into our stylesheets, with a namespaced class name, so that we can leverage those already worked through break points.

2021-12-08 19:22 UTC, imcgonigle commented
@gileswells Good catch I didn't even realize it was centered.

2021-12-14 14:31 UTC, gileswells approved these changes
LGTM

2021-12-15 16:09 UTC, merged