Api 11518/add benefits ref data to devportal dev env
department-of-veterans-affairs/developer-portal pull request #919
Opened 2021-12-13 18:28 UTC by peyton-lucas

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2021-12-17 00:46 UTC, dsteeve reviewed
leaving off approval for now until the problem from yesterday is resolved in the vaapi-platform channel  

https://github.com/department-of-veterans-affairs/developer-portal/runs/4553801031?check_suite_focus=true

once that deploy is successful, this branch should be updated with the latest code changes.

2021-12-20 19:54 UTC, gileswells requested changes
I mostly reviewed for code implementation, which looked good. Just a couple items to call out that I saw.

2021-12-20 19:54 UTC, gileswells commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +                    &#123; &quot;sta3n&quot;: &quot;993&quot;, &quot;patient&quot;:
Could this be updated to match https://github.com/department-of-veterans-affairs/developer-portal/pull/919/files?diff=unified&w=1#diff-a88672151d2074fe987d8f123352ce857234d3c4b3b68b55b12881f4f7f5868eR170 so that it's more easily readable?

2021-12-20 19:54 UTC, gileswells commented on src/content/apiDocs/benefits/benefitsReferenceDataReleaseNotes.mdx
> +### UX APPROVED/PROPOSED FIRST RELEASE NOTE VERBIAGE:
Looks like the title needs to still be updated here.

2021-12-21 16:01 UTC, peyton-lucas commented on src/components/oauthDocs/acg/AuthCodeFlowContent.tsx
> +                    &#123; &quot;sta3n&quot;: &quot;993&quot;, &quot;patient&quot;:
Sure thing.

2021-12-21 16:02 UTC, peyton-lucas commented on src/content/apiDocs/benefits/benefitsReferenceDataReleaseNotes.mdx
> +### UX APPROVED/PROPOSED FIRST RELEASE NOTE VERBIAGE:
Many thanks, I'll get it added.

2021-12-22 23:08 UTC, dsteeve approved these changes
yay!  I think this is correct.

2022-01-03 21:16 UTC, gileswells approved these changes

2022-01-03 21:17 UTC, merged