Api 10782 global nav updates [WIP]
department-of-veterans-affairs/developer-portal pull request #937
Opened 2022-01-12 17:44 UTC by Cgfor3

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2022-01-13 16:53 UTC, imcgonigle reviewed
This looks good to me. I'll add the approval once the build passes.

It seems to me that the Code scanning error can be dismissed since all of the URLs are coming from a file within the app and not from an external source. Alternatively you could change that to a regex match or create a URL object and grab the host.
```javascript
let url = new URL('https://www.youtube.com/watch?v=jmnH42Qse48');
if(url.host === 'www.youtube.com'); // true
```

2022-01-13 18:16 UTC, SlakrHakr commented
Agree with @imcgonigle above. Let me know if i can help getting the last couple of pieces of the build passing in any way.

2022-01-14 16:37 UTC, SlakrHakr commented on src/containers/about/About.tsx
> +// import { PAGE_HEADER_AND_HALO_ID } from '../../types/constants';
nit: probably worth taking out

2022-01-14 16:40 UTC, SlakrHakr approved these changes

2022-01-24 19:35 UTC, gileswells requested changes
A few small link changes to allow them to single page app link across without having to reload the whole app.

2022-01-24 19:35 UTC, gileswells commented on src/containers/about/Overview.tsx
> +        <a href="https://developer.va.gov/onboarding/working-with-lighthouse-apis">
This should use `<Link to="/onboarding/working-with-lighthouse-apis">` or better yet `<Link to={CONSUMER_APIS_PATH}>`

2022-01-24 19:35 UTC, gileswells commented on src/containers/about/Overview.tsx
> +        <a href="https://developer.va.gov/apply">request an API key</a>.
Similar to above. `<Link to="/apply">`

2022-01-24 19:35 UTC, gileswells commented on src/containers/about/Overview.tsx
> +        <a href="https://developer.va.gov/explore">our APIs</a>. We never, ever charge fees.
Should use `<Link to="/explore">`

2022-01-28 13:45 UTC, Eallan919 commented
🥰

2022-02-03 16:14 UTC, gileswells approved these changes
Changes looking good to me.

2022-02-04 15:40 UTC, merged