Afoster va 13 jan rl
department-of-veterans-affairs/developer-portal pull request #938
Opened 2022-01-12 21:24 UTC by afoster-va

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2022-01-13 15:43 UTC, joeabraun requested changes
Let me know if you have any questions!

2022-01-13 15:43 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +We changed the `referenceRange` that's returned with an `Observation` resource.
When I first read this, I wasn't sure if the bullet points were referring to 'referenceRange' or 'Observation resource.' I tried to clarify this a bit with the revised sentence. 

```suggestion
We changed the `referenceRange` data field that returns an `Observation` resource.
```

2022-01-13 15:43 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +Added the `code.text` data field to the ` PractitionerRole` resource.
I removed the space between the ' and the P, which was starting the word PractitionerRole. 

```suggestion
Added the `code.text` data field to the `PractitionerRole` resource.  
```

2022-01-13 15:43 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +Added support for `_lastUpdated` search for DSTU2 and R4 `Procedure` resource.
Added "in both the" before DTSU2 and R4.

```suggestion
Added support for `_lastUpdated` search in both the DSTU2 and R4 `Procedure` resource.
```

2022-01-13 15:43 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +Added support for `_lastUpdated` search for R4 `Observation` resource.
Just to remove the back to back fors in the sentence, I inserted "in the".
```suggestion
Added support for `_lastUpdated` search in the R4 `Observation` resource.
```

2022-01-13 15:43 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> + - It now returns the `system`, `code`, and `unit` only if all data are present.
I think it might help the clarity of the sentence to insert the word fields after listing system, code, and unit.
```suggestion
 - It now returns the `system`, `code`, and `unit` fields only if all data are present.   
```

2022-01-13 16:18 UTC, gileswells submitted a review, later dismissed

2022-01-13 16:20 UTC, joeabraun requested changes
After this one change, it looks good to me!

2022-01-13 16:20 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +We changed the `referenceRange` that is returned with the `Observation` resource.
```suggestion
We changed the `referenceRange` data field that is returned with the `Observation` resource.
```

2022-01-14 20:38 UTC, afoster-va reviewed
Done!

2022-01-14 20:42 UTC, joeabraun approved these changes
LGTM!

2022-01-18 14:28 UTC, gileswells approved these changes

2022-01-18 14:45 UTC, merged