Update fhirAPIReleaseNotes.mdx
department-of-veterans-affairs/developer-portal pull request #954
Opened 2022-01-24 18:58 UTC by afoster-va

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2022-01-26 14:50 UTC, joeabraun requested changes
Request a few small changes.

2022-01-26 14:50 UTC, joeabraun commented on src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
> +The 'manufacturer.display' field has been updated in the R4 `Immunization` resource. This field is populated based on [CVX to Manufacturer mappings from the CDC Product Name to CVX and MVX code set](
A few small edits:
1) Updated `manufacturer.display` in its first instance to match the text format of the later one.
2) Added an s to 'Product Name'.
3) Lowercase the first instance of 'manufacturer' in 'multiple manufacturers'.
4) Shortened the length of the hyperlink to 'CDC Product Names to CVX and MVX code set'.
5) Removed the extra space between the period and 'In cases where...'
6) Turned 'cannot' into 'can't'. 
```suggestion
The `manufacturer.display` field has been updated in the R4 `Immunization` resource. This field is populated based on CVX to manufacturer mappings from the [CDC Product Names to CVX and MVX code set](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=tradename). In cases where a CVX code maps to multiple manufacturers, the exact manufacturer can't be determined and thus `manufacturer.display` will be omitted from the response.
```

2022-01-26 15:05 UTC, joeabraun approved these changes
LGTM. UX approves!

2022-01-27 16:05 UTC, gileswells approved these changes

2022-01-31 15:59 UTC, dsteeve approved these changes
looks ok to me

2022-02-02 18:25 UTC, merged