Slakrhakr/api 11956
department-of-veterans-affairs/developer-portal pull request #978
Opened 2022-02-14 20:07 UTC by SlakrHakr

### Description

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

2022-03-01 15:19 UTC, gileswells requested changes
Hope we can streamline some of the new test.sh files

2022-03-01 15:19 UTC, gileswells commented on scripts/accessibility_test.sh
> +sudo kill -9 $(lsof -t -i:8080)
I'd like to see this copied at the end of the bash script so we don't have any dangling python processes if at all possible.

2022-03-01 15:19 UTC, gileswells commented on scripts/accessibility_test.sh
> +node scripts/test.js --projects=e2e.jest.config.js --testMatch='<rootDir>/src/**/?(*.)(accessibility).(j|t)s?(x)' --ci --testResultsProcessor='./node_modules/jest-junit-reporter' --forceExit --runInB
Can we look at passing in all the arguments sent to this bash file as a whole on the end of this command? If we're able to do that we can make a singular `scripts/mocked_test.sh` file and would be able to use that singular file for e2e, accessibility, and visual regressions.

2022-03-01 18:23 UTC, SlakrHakr commented on package.json
> +  "proxy": "http://localhost:8080/",
This was required to call LPB locally.

2022-03-01 18:23 UTC, SlakrHakr commented on .env.test
> +REACT_APP_DEVELOPER_PORTAL_SELF_SERVICE_URL=
This was required due to using the proxy below

2022-03-01 18:24 UTC, gileswells commented
I should change over the visual regressions script to use the token for `va-bot`.

2022-03-01 18:24 UTC, SlakrHakr commented on scripts/test.sh
> +python -m http.server 8080 &
Serves up mock LPB response for e2e, accessibility, and visual regression tests

2022-03-01 18:25 UTC, SlakrHakr commented on src/App.tsx
> +      .then(apis => dispatch(setApis(apis)));
Calls out to LPB on full page load and stores the response in redux

2022-03-01 18:28 UTC, SlakrHakr commented on src/containers/releaseNotes/CategoryReleaseNotes.tsx
> +      </div>
This is because release notes from LPB are strings in markdown format

2022-03-01 18:31 UTC, SlakrHakr commented on scripts/accessibility_test.sh
> +sudo kill -9 $(lsof -t -i:8080)
https://github.com/department-of-veterans-affairs/developer-portal/pull/978/commits/784e8883c5919682788b2e3e4672a78c2e9eabdd

2022-03-01 18:31 UTC, SlakrHakr commented on scripts/accessibility_test.sh
> +node scripts/test.js --projects=e2e.jest.config.js --testMatch='<rootDir>/src/**/?(*.)(accessibility).(j|t)s?(x)' --ci --testResultsProcessor='./node_modules/jest-junit-reporter' --forceExit --runInB
https://github.com/department-of-veterans-affairs/developer-portal/pull/978/commits/784e8883c5919682788b2e3e4672a78c2e9eabdd

2022-04-13 18:14 UTC, SlakrHakr commented
Waiting on this PR to be approved and then deployed
https://github.com/department-of-veterans-affairs/devops/pull/11059
and then this should be able to move forward.

2022-08-12 17:42 UTC, gileswells approved these changes
LGTM 🥰

2022-08-12 18:01 UTC, merged