API-13230: Release notes for claims api
department-of-veterans-affairs/developer-portal pull request #980
Opened 2022-02-15 19:20 UTC by hinzed1127

### Description

Release notes for the changes made by https://github.com/department-of-veterans-affairs/vets-api/pull/9112
### Process

~- [ ] Tests added or updated for change~
- [X] Docs updated
  ~- [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated~
  ~- [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated~
~- [ ] Accessibility concerns have been considered and addressed~
  
  ~- [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues~

### Requested feedback

2022-02-16 15:46 UTC, gileswells submitted a review, later dismissed
LGTM if UX approves or has approved feel free to merge

2022-02-16 21:16 UTC, joeabraun requested changes
Reworded the two sentences and moved the number until after the listed endpoints.

2022-02-16 21:16 UTC, joeabraun commented on src/content/apiDocs/benefits/claimsReleaseNotes.mdx
> +- Updated the v1 validation endpoints to use the same validation as their respective submission endpoints. The following endpoints validate in the same way now ([#9112](https://github.com/department-
```suggestion
- Updated the v1 validation endpoints to validate in the same way as their respective submission endpoints. These following endpoints are:
```

2022-02-16 21:16 UTC, joeabraun commented on src/content/apiDocs/benefits/claimsReleaseNotes.mdx
> +
[#9112](https://github.com/department-of-veterans-affairs/vets-api/pull/9112)

2022-02-17 04:26 UTC, hinzed1127 commented on src/content/apiDocs/benefits/claimsReleaseNotes.mdx
> +- Updated the v1 validation endpoints to use the same validation as their respective submission endpoints. The following endpoints validate in the same way now ([#9112](https://github.com/department-
@joeabraun "These following" is redundant, so I just changed to "These" and removed "following" entirely. Rest of the edits were made as commented above.

2022-02-17 14:29 UTC, joeabraun commented on src/content/apiDocs/benefits/claimsReleaseNotes.mdx
> +- Updated the v1 validation endpoints to use the same validation as their respective submission endpoints. The following endpoints validate in the same way now ([#9112](https://github.com/department-
@hinzed1127 okay, great. Looks good to me.

2022-02-17 17:20 UTC, SlakrHakr approved these changes

2022-02-17 17:57 UTC, merged